### ISSUE TITLE
note - social media share button 

### ISSUE THREAD

**Issue by awchauhdry** [paperwork/paperwork#140]
is there a ticket to work on the social media share button? the button seems inactive at the moment

**Comment by devilx** [comment]
Now there is one - #140. :-) Feel free to work on it, if you'd like!

**Comment by awchauhdry** [comment]
we are going to need oauth api keys to integrate the social media functionality, are there any specific accounts that they should be created under?

**Comment by devilx** [comment]
@awchauhdry I wouldn't implement such a deep integration, but instead use the default share-URLs. Check out this service for the URLs: http://www.sharelinkgenerator.com/

**Comment by wongalvis** [comment]
It is not necessarily to include oauth to implement sharing via social media. A simple method would be putting on a share button/retweet button etc., the shared content is provided and Facebook/Twitter would do all the stuff with authentication.

**Comment by wongalvis** [comment]
Another way to implement Facebook sharing without oauth is to include a href to a url like https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fwww.google.com

**Comment by Baldrs** [comment]
We need to do something or remove that button.

**Comment by yeannyang** [comment]
but is there any way to share within paperwork?

**Comment by wongalvis** [comment]
Does that mean sharing the note to other users or sharing it via social platforms?

**Comment by yeannyang** [comment]
@wongalvis  sharing the note to other users in paperwork. My paperwork is expected be a private notebook.
