### ISSUE TITLE
Suggestion: Add a dirty flag when in edit mode

### ISSUE THREAD

**Issue by codingmatty** [paperwork/paperwork#163]
The suggestion is to add a dirty flag when in edit mode so that if you want to cancel editing a note you don't get a pop-up asking if you really want to cancel when you didn't actually change anything.

**Comment by devilx** [comment]
This should actually be already working like that:

https://github.com/twostairs/paperwork/blob/master/frontend/app/js/paperwork/paperworkNotesEditController.js#L64

Doesn't it work for you?

**Comment by devilx** [comment]
However, besides the local dirty flag, we should consider adding a server-side dirty flag, in order to support shared notebooks/notes.

**Comment by Liongold** [comment]
The local dirty flag works in Paperwork 
b169a1e8b46a257c9b8a9248e4ab4f9224cdcb37. Thus, part of this issue. @mrusme Do you still think a server flag is needed?
