### ISSUE TITLE
Clean up angular.js code

### ISSUE THREAD

**Issue by mrusme** [paperwork/paperwork#17]
The Angular.js code is yet pretty unstructured and not DRY enough. This should be cleaned soon.

**Comment by Baldrs** [comment]
I'm working on changing file structure according to this:https://github.com/johnpapa/angularjs-styleguide#application-structure

**Comment by devilx** [comment]
@Baldrs invited you to join the team. As soon as you're in, you/me can assign this issue to you.

**Comment by Baldrs** [comment]
There is also need to remove jquery usage at least into directives
