### ISSUE TITLE
Paperwork behind Nginx Reverse-Proxy?

### ISSUE THREAD

**Issue by DeviantEng** [paperwork/paperwork#197]
Hi guys.

So yeah, a few weeks ago I revisted this project, and I am very happy with it.  I've moved over my stuff from Evernote to Paperwork, and configured paperwork to proxy through my Nginx reverse proxy, and now I'm having issues.

paperwork.domain.local is my server name that paperwork is running on.  domain.com is my public facing domain, and I have my Nginx reverse-proxy setup using that already with other services.  For example, cloud.domain.com reverse proxies to owncloud.domain.local, and it works great.  notes.domain.com is what's used for my Paperwork setup.

With the same setup, I can get to the login screen for paperwork.  Once I type in my creds, I hit Sign in and get redirected from https://notes.domain.com/login, to http://paperwork.domain.local/login, which obviously isn't accessible outside my network.  

Is Paperwork hard coded to do, or something?  I have 9 other services with the same config in Nginx, and they all work just fine.  Paperwork redirects in a strange way.

Thanks!

**Comment by devilx** [comment]
@DeviantEng what's inside your ```frontend/app/config/app.php``` defined as 'url'?

**Comment by DeviantEng** [comment]
@devilx 'url' is defined as 'http://localhost'.

Should I try changing this to 'https://notes.domain.com'?

**Comment by devilx** [comment]
That's weird. Are you sure your nginx config doesn't perform the rewriting/redirecting?

**Comment by DeviantEng** [comment]
@devilx 
Yeah, my Nginx isn't doing any rewriting other than using the proxy_pass option.

Here is my default.conf for Nginx:
http://textdump.net/read/6675/

Like I said, it's working for everything else (I removed several services from the conf linked above, but there is enough there to see what I am doing).  It's so weird, and I'm not sure how to fix it.  If I can get this figured out, I am sold on using Paperwork as my only note solution!

**Comment by devilx** [comment]
Just performed a quick search on google and found this: http://fideloper.com/laravel-4-trusted-proxies

Could you try to include this piece of code:

```
Request::setTrustedProxies(array(
    '192.168.1.52' // IP address of your intermediary
));
```

For example into ```/frontend/app/filters.php```? Just to check, if that's the real problem behind your issue.

**Comment by DeviantEng** [comment]
@devilx 
That didn't change any behavior.

However, I added "proxy_set_header HOST $host;" to my Nginx config on the reverse proxy, and I am getting different behavior.

So now i have: 

server {
    listen 443 ssl;
    server_name notes.domain.com;

    ssl on;

    location / {
        proxy_pass http://paperwork.domain.local/;
        proxy_set_header HOST $host;
    }
}

And when I hit Sign in, it takes me to this URL:
https://notes.domain.com/index.php/index.php/login?

Which is still my external URL.  But of course, that page isn't found.

Hmm...

**Comment by devilx** [comment]
@DeviantEng sorry, I never tried such a setup before. It appears that a few users did so, though: http://laravel.io/forum/10-25-2014-configuration-for-running-laravel-with-nginx-and-apache

You appear to have a similar issue in which paths are being rewritten in a weird (twice?) way. Maybe check the try_files setting?

**Comment by FromBabylon** [comment]
I am able to run paperwork using proxy_pass nginx directive. My config may not be exactly yours as for now I only redirect to another port but it is working quite well. 
This is my location block : 
<pre> 
location /paperwork {
                 rewrite ^/paperwork/(.*)$ /$1 break;
                 proxy_pass https://IP:8080;
                 #proxy_set_header Host $http_host;
                 #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
<code>

If I set proxy_set_header directive,  images, css and js won't load because it will ask for https://IP/js instead of https://IP:8080/js
Using Whisprin@8445d31 all works well. Login screen is found at https://IP/paperwork/login. When I hit sign in I get redirect to https://IP:8080/#/n/0/1 which works as it is accessible but I would like it to stay https://IP/paperwork/#/n/0/1. If I manually enter url https://IP/paperwork/#/n/0/1 I don't get redirect and it works well.

**Comment by DeviantEng** [comment]
@FromBabylon Thanks for the info, but unfortunately doesn't work for me.  Still redirecting to my internal address, which obviously won't work from outside my network.  :(

**Comment by Liongold** [comment]
Is this issue still valid?

**Comment by DeviantEng** [comment]
Last I tried, I couldn't get it working.  Unfortunately I gave up shortly after my last comment.

**Comment by Liongold** [comment]
@DeviantEng Would you be interested in trying again? Or should this be closed?

**Comment by DeviantEng** [comment]
@Liongold Yes, I would love to get it working if I could get some guidance.  

Let me spin up a new CentOS 7 LXC and get it re-installed, and added to my reverse proxy.  I will then share the configs I'm using and problems I'm having (if any).  For all I know it could just be a nginx config problem.

**Comment by DeviantEng** [comment]
At this point, I have Paperwork installed and working correctly using the local address.  When browsing to `notes.local.domain.com`, which is my local domain and not externally available, Paperwork works as expected.  I have a separate box with Nginx installed, acting as a reverse proxy.  I have that set to `notes.domain.com`, and when I access that (over SSL) the login screen loads, but I am seeing several errors within the console regarding mixed content being loaded (site is loaded with HTTPS, but content in that page is loaded HTTP), while some of that content is loading with `http://172.16.1.124` instead of `https://notes.domain.com`, as I would expect.  It technically works within my local network, but from the WAN it doesn't work.  For the install, I used the guide I have on my blog, here:
https://deviantengineer.com/2014/10/paperwork-centos7/

Here is my LOCAL nginx config:
```
server {
    listen       80;
    server_name  localhost;
    set  $root_path '/var/www/html/paperwork/frontend/public';
    root  $root_path;

    index  index.php index.html index.htm;

    try_files $uri $uri/ @rewrite;

    location @rewrite {
        rewrite ^/(.*)$ /index.php?_url=/$1;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_split_path_info       ^(.+\.php)(/.+)$;
        fastcgi_param PATH_INFO       $fastcgi_path_info;
        fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~* ^/(css|img|js|flv|swf|download)/(.+)$ {
        root $root_path;
    }
    location ~ /\.ht {
        deny all;
    }
}
```

Here is the nginx config for my reverse proxy:
```
ssl_certificate         ssl/domain.us.crt;
ssl_certificate_key     ssl/domain.us.key;
ssl_dhparam             ssl/dhparam.pem;
ssl_session_timeout     5m;
ssl_protocols           TLSv1 TLSv1.1 TLSv1.2;
ssl_prefer_server_ciphers       on;
ssl_ciphers             AES256+EECDH:AES256+EDH:!aNULL;

server  {

  listen  80;
  server_name  *.domain.com;
  return 301 https://$host$request_uri;
}

server  {
  listen  443 ssl;
  server_name domain.com;
  ssl  on;
  location  / {
    return  404;
  }
}

server {
  listen  443 ssl;
  server_name  notes.domain.com;
  ssl  on;
  location  / {
    proxy_pass  http://172.16.1.124/;
  }
```

Pretty straightforward, me thinks.

Now based on various things I've read online, there seems to be some complication with running laravel apps behind a reverse proxy.

Specifically, I started here:
http://laravel.io/forum/12-26-2014-routing-with-https

From there I ended up adding a simple line to my routes.php
`URL::forceSchema("https");`

What this did was force my local site to be https, which partly solved a problem with loading mix content.  However, by setting that, I was getting another issue such as `net::ERR_CONNECTION_REFUSED` on a few files trying to be loaded (namely 2 js files, a css file, and paperwork-logo.png).  [Here](http://imgur.com/5lGM1tn) is a screenshot of the console in Chrome with this error.  So this isn't a proper solution.

I also looked at this:
http://fideloper.com/laravel-4-trusted-proxies

But it didn't resolve my issue.


So with all this said, I am confident in saying that my issue is not directly related to Paperwork, but moreso with Laravel.  I am currently looking into using something like this:
https://github.com/fideloper/TrustedProxy

To see if it will resolve my issue.  I think if Paperwork was based on Laravel 5, there might be a different outcome, but with Laravel 4 my options seem limited (unless I want to go change things in the Laravel framework, which is not ideal).

Any suggestion/feedback you have would be greatly appreciated.  If I can get things working with [Trusted Proxy](https://github.com/fideloper/TrustedProxy), I will definitely share that info for others.

**Comment by DeviantEng** [comment]
so circling back on this, I seem to have things 90% working now.  Honestly, I'm not sure if that Trusted Proxy is a requirement or not for my success, but I do still have it installed/configured.

I added two lines to my routes.php file (./paperwork/frontend/app/routes.php) that made the biggest change in how mix content was incorrectly loading, and how some uri's were loading with the local IP instead of the proxied uri.

This is what I added to the top of routes.php:
```
URL::forceRootUrl('https://notes.domain.com');
URL::forceSchema('https');
```

`forceRootUrl` change the generated paths to that of my proxied address, but I was still getting mixed content problems.  Adding `forceSchema` and setting it to https fixed that problem. 

Two seemingly simple lines, but it took me a day to find any real documentation leading me to that, so I hope that helps others.

With those two lines set (and possibly with the addition of that Trusted Proxy app -- which I will rebuild without test if it's a requirement for my success or not), pages are properly loading.

Page successfully loads, I can successfully login, and I can successfully create notebooks (and also add to the shortcuts).  I run into problems when creating a note, though.
If I create a new note from the main screen, [this](http://i.imgur.com/RsGppcX.png) is what I see.  I can't type in the box, there's nothing to select, and if I click on `Select`, I get a red dropdown bar with a warning message:
`Something went wrong while creating your note. Please try again.`

If I click on a notebook first, then select `File > New note`, it seems to create a new note as expected.  I can fill out the Title, tags, and note fields...but get an error when I click the save icon. [This](http://i.imgur.com/iB8vLjW.png) is what I see.
So if I hit the cancel icon (x in a circle), I get a message `Close without saving?`, so I hit `Yes` and it takes me back to my notebook where I just see an empty note with a title of `Untitled`.  Interestingly, the tags I added on that note did get created as tags.

Lastly, the third problem I've run into is trying to move a note to a different notebook. [This](http://i.imgur.com/XYP1Oba.png) is what I see when I click `Select`.

Looking in my Nginx error logs from today (which is when I did this testing and grabbed this screenshots), I only see one error (this is nginx error log that paperwork is directly using; not the proxy server):
```
2016/05/20 13:41:49 [error] 497#0: *510 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'DOMDocument' not found in /var/www/html/paperwork/frontend/app/lib/Paperwork/Helpers/PaperworkHelpers.php on line 27" while reading response header from upstream, client: 172.16.1.108, server: localhost, request: "PUT /api/v1/notebooks/00000000-0000-0000-0000-000000000000/notes/74e79bfb-f73b-4e2e-9232-1770e50efa30 HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "172.16.1.124", referrer: "https://notes.domain.com/"
```

FYI, `172.16.1.124` is `notes.local.domain.com`, where paperwork is installed.  `172.16.1.108` is `webproxy.local.domain.com`, which is my reverse proxy server running Nginx.
Nginx access logs look normal with no visible problems, and just showing several GET requests.  No errors from mariadb or php-fpm have been logged.

I'm not seeing any log dirs within the paperwork app, so not sure how to provide more info on those problems.  If I can provide anything else, though, just let me know.

**Comment by Liongold** [comment]
@DeviantEng Very good news to hear. Did you try installing php-xml and php-fpm (or something similar named - sorry can't give you the exact names but should be good) to fix the last issue?

**Comment by Liongold** [comment]
About the https reverse proxy problem, some work for that has already been done during the development of the Paperwork port for Sandstorm. Some of that work could help you.

**Comment by DeviantEng** [comment]
I do have php-xml and php-fpm installed.  I used remi-php56 repo so I could get version 5.6.21 of each package, instead of 5.4.16 which is included with CentOS.

One possible problem is that `dom.so` isn't listed under `/usr/lib64/php/modules/`, and is instead located in `/opt/remi/php56/root/usr/lib64/php/modules/dom.so`.  Let me try linking that to `/usr/lib64/php/modules/dom.so` and see if that helps at all.

I will look into the sandstorm port and see if that can lead to anything useful and report back.

**Comment by Liongold** [comment]
This is the URL of the port https://github.com/JamborJan/paperwork.

**Comment by DeviantEng** [comment]
Thanks for the URL.

Linking dom.so to that other directory didn't make a difference, and I'm still getting the same error message.  is Paperwork (or Laravel 4.x) supported with php 5.4, or is 5.6 or newer required?  I can't remember why I installed php 5.6 instead of using the included 5.4 packages.

**Comment by Liongold** [comment]
It should be 5.4, 5.5 and 5.6. Those are built on every pull request.

**Comment by Liongold** [comment]
The change done saeems to be here so it's like what you're using.  https://github.com/JamborJan/paperwork/blob/master/frontend/app/routes.php#L12. Of course, it isn't checking for the Sandstorm details. There's no mention of any other frameworks in that so it's likely that the Trusted proxy part is not needed.

**Comment by DeviantEng** [comment]
Yeah, I as just looking at what had been added to routes, and seems to be about the same.  I also suspect the Trusted Proxy app isn't needed, but I haven't had a chance to rebuild without it yet.

If php 5.4 is supported, I may just rebuild my instance with 5.4 and without Trusted Proxy and see where things stand.

**Comment by Liongold** [comment]
As for the DOMDocument error, you might need to add `use DOMDocument` in the file. Check it to see if it works.

**Comment by Liongold** [comment]
Forget the last post, it's already done in the code.

**Comment by Liongold** [comment]
Actually, it could be that you need to set the path in the use statement and not just DOMDocument due to your different folder structure.

**Comment by DeviantEng** [comment]
Yeah, I was thinking it might be a PATH problem with not being able to find the dom.so library.  It's odd that the rest of the php stuff I need is there, because the app at least loads and does everything but save a doc, so I'm not sure whats going on there.

I've got a new LXC spinning up to test with php 5.4.  Will let you know how that goes here in a little bit.

**Comment by DeviantEng** [comment]
Rebuilt with php 5.4, adding those 2 lines to routes.php, and without Trusted Proxy installed.  All seems to be working right now.  

I'm about to update my blog with my updated setup, in case anyone is curious.  Link is:
https://deviantengineer.com/2014/10/paperwork-centos7/

**Comment by Liongold** [comment]
@DeviantEng Do you think you could change this fix to work generally and contribute it to Paperwork?

**Comment by Liongold** [comment]
A pull request that should fix this issue has been merged. Can someone retest this on the develop branch please?
