### ISSUE TITLE
Fix documentation: Add info about ImageMagick and Tesseract

### ISSUE THREAD

**Issue by mrusme** [paperwork/paperwork#217]
For Paperwork to be able to scale uploaded images (generating thumbnails) imagemagick is needed. Also, for Paperwork's OCR capabilities (e.g. when you upload a photo of a written document, Paperwork tries to parse the text out of it) to work, you will need tesseract (+ language files) installed on your system.

We need to fix the documentations in order to provide some information on installing these additions.

**Comment by jamesrascal** [comment]
Is there anything special that will need to be configured for these to work with Paperwork? If it is just a matter of having them installed based on the the official documentation this will be easy to update.

**Comment by devilx** [comment]
@jamesrascal the only configuration needed should be enabling imagemagick within the php.ini and making sure that the tesseract binary is available within the folders listed inside the $PATH variable. Of course, tesseract needs every language installed as well - this shouldn't be a problem though, since most major distributions provide these as packages (e.g. https://packages.debian.org/search?keywords=tesseract&searchon=names&suite=stable&section=all)

**Comment by jasondavis** [comment]
This OCR with tesseract is a great idea, It's not actually implemented yet is it?

**Comment by devilx** [comment]
@jasondavis it is, that's what I stated above and in #214. The thing is, as a regular user you (currently) have no benefit from it, as the data is being written inside the attachments content column, but not displayed anywhere (yet). I'm not sure, whether the search would currently find any of the parsed text either.

**Comment by jamesrascal** [comment]
Would it be possible to add some info under the admin page that does a check to see if these items are installed. 

Example, if you login and go to the admin page you will see the current users and then under that you would see additional components. Something similar to this:

![2015-02-09 17_02_09-paperwork](https://cloud.githubusercontent.com/assets/6054150/6119437/b52d8786-b07d-11e4-8736-28ff50048e13.png)

**Comment by devilx** [comment]
This info is a good idea in general, but how about we do not add it in the admin page, but rather use this idea to extend Paperwork setup by providing a "setup.php" (similar to what Drupal, WordPress, etc. provide), which helps the user setting up the whole basics?

**Comment by jamesrascal** [comment]
@devilx I think this will need to be a new issue slated for the 1.0 or 2.0 release to create a php setup wizard.

**Comment by devilx** [comment]
@jamesrascal you are pretty damn right with that! -> #234. :+1:
