### ISSUE TITLE
Implement SJCL and allow client-side note encryption

### ISSUE THREAD

**Issue by mrusme** [paperwork/paperwork#22]
Using SJCL (http://bitwiseshiftleft.github.io/sjcl/) Paperwork could allow client-side, JavaScript note encryption, so that every note-content could be transferred and stored encrypted within the back-end.

This probably wouldn't work for all notes, like for example shared ones, but we could at least allow the user to specifically encrypt notes separately (not by default!), using a specific per-note-password. If the user then shares the note to someone, he could pass him along the password used for that note.

**Comment by devilx** [comment]
The issues regarding encrypted notes were discussed in #188. It looks like this is something that's not trivial to implement.

However, this feature should definitely be re-considered in future versions.
