### ISSUE TITLE
In place editing

### ISSUE THREAD

**Issue by PercussiveRepair** [paperwork/paperwork#259]
I'm trying paperwork having used simple-note.appspot.com for a long time. 

Simplenote has no "save" button. Notes are edited in screen and saved automatically in the background.

An easier to implement middleground would be to have paperwork open the edit screen where the notes are displayed on the home page (right half of the screen) without moving to a new, separate edit page.

**Comment by jasondavis** [comment]
Auto saving is a nice feature but for me personally I prefer the save button just so you "know" for sure the data is saved.  Technically I prefer for it to show the save button but to then be able to hit the keys "ctrl + s" on a PC and have that"click the save" button.  IT's a really nice and fast workflow for myself...I guess being a Developer I am constantly hitting "ctrl + s" in Sublimetext so it's become a natural work flow.

Loving all the ideas, looking forward to some of them getting implemented hopefully!

**Comment by Gauss--** [comment]
Both would be useful.
