### ISSUE TITLE
Tag duplication

### ISSUE THREAD

**Issue by Gauss--** [paperwork/paperwork#266]
I have the same tag twice,
when I click on them, its not the same notes that are displayed.
Looks like a blank space got there.

**Comment by joshlemer** [comment]
Thank you for reporting this.

**Comment by joshlemer** [comment]
@Gauss-- Could you give an example? I tried making a tag:

"mynote" and "mynote " (the second having a trailing space), but this doesn't create a new tag. Nor does " mynote" (leading space). Or are you talking about if you do something like "my note", which creates a new tag?

**Comment by Gauss--** [comment]
@joshlemer,
I took a look and reproduced the error. You can check on paper work demo with this email address: juju_123@yopmail.com 

**3 Steps** : 
- create new account, 
- edit the welcome note and add a new tag "tag",
- save.

**Outcome** : 
- as you can see, there are now two "welcome" tags, and they don't list the same notes.
Here are two screenshots : 

![welcome_tag_none](https://cloud.githubusercontent.com/assets/10779917/6545191/17a4b73e-c57a-11e4-8fab-01578091f464.jpg)
![welcome_tag_one](https://cloud.githubusercontent.com/assets/10779917/6545192/17a587ae-c57a-11e4-8580-649f3dbd001d.jpg)

**Comment by joshlemer** [comment]
Ah okay yes this seems to be an issue only with the "Welcome" note, and the bug is still happening in the latest develop version.

**Comment by Baldrs** [comment]
Can't reproduce this using the steps, can you confirm whether it is fixed or not with the latest develop?

**Comment by Liongold** [comment]
Can someone confirm this issue again please?
