### ISSUE TITLE
Idea: Implement WebDAV interface using sabre

### ISSUE THREAD

**Issue by mrusme** [paperwork/paperwork#27]
Here's an idea: How about Paperwork would implement a WebDAV interface using sabre (https://github.com/fruux/sabre-dav), which would allow working with Notes and Notebooks as they were files and folders?

Further thoughts: - How would attachments to notes appear? Would they appear at all?
- What would be the difference between a Notebook enclosing Notes and a Collection enclosing Notebooks only, from a filesystem point of view?
- Would this really provide a use for people?
- Would this push Paperwork too much into the "SharePoint" or "Alfresco" area?

**Comment by stevenroose** [comment]
Removed from the Milestone? No longer considering this?
