### ISSUE TITLE
When a Notebook is open and a tag is selected on the sidebar, the all notes with that tag should show, not just from that Notebook.

### ISSUE THREAD

**Issue by joshlemer** [paperwork/paperwork#273]
If you open a Notebook, then open a tag, the app searches for notes in the open Notebook with that tag. Should we clear the NotebookSelectedId and just search for any note with that tag, or should we search within the notebook? I'm personally in favor of just selecting any note with that tag.

**Comment by jasondavis** [comment]
I would vote for a global search of any note with that tag as well!

**Comment by Baldrs** [comment]
That seems sound. But I'd preferred to make it configurable.
