### ISSUE TITLE
Tour library

### ISSUE THREAD

**Issue by jasondavis** [paperwork/paperwork#311]
I have been testing and researching the available libraries for this functionality and one of the best I have found is from Hubspot, they have created a library called ShepHerd http://github.hubspot.com/shepherd/

It's really nice and easy to use.  Has some nice features like scroll to and a good UI.  It's easy to use as you define the "Tour Steps" with the content you want to show and then assign which buttons to show and an action for each button on each step.  You then assign each step a CSS Class to attach to on the page.

**Github page:** https://github.com/HubSpot/Shepherd
**Project websaite:** http://github.hubspot.com/shepherd/
**Demo Tour page:** http://github.hubspot.com/shepherd/docs/welcome/

Also another equally good one from LinkedIn is HopScotch  

**Project Page:** http://linkedin.github.io/hopscotch/
**GitHub Page:** https://github.com/linkedin/hopscotch
#53

**Comment by Liongold** [comment]
@jasondavis Are you planning on doing this yourself?

**Comment by wongalvis** [comment]
I'm interested in it.

**Comment by Liongold** [comment]
@wongalvis Are you still going to work on this?

**Comment by wongalvis** [comment]
I am interested but unfortunately I may not be free until at least a week or two later. If someone else is going to work on it I would be glad to see it, and maybe follow up when I'm free.

**Comment by wongalvis** [comment]
@Liongold Have you been working on one?

**Comment by Liongold** [comment]
@wongalvis No, I did not do anything about this. It's totally free for you to work on.

**Comment by wongalvis** [comment]
I don't know if there's a method to check if the user's logging in for the first time. If yes, that would be great and maybe I could start working on a introductory tour.

**Comment by Liongold** [comment]
@wongalvis Maybe add a "setting" field and then checking for this when opening the page? Also, preferably, you could add a "Run tour" button in the Settings to be able to run the tour even after first visit.

**Comment by wongalvis** [comment]
@Liongold I've been digging into the code but since my experience and knowledge with backend is limited, it's quite hard for me to understand it. My schedule is packed with all kinds of work so I think I'll not be able to work on it for now. It would be better if someone from the community could work on it with me together then it could be completed much quicker and easier. If there's still not a tour library after some time, I'll work on it when I'm free from the work packed in my schedule.
