### ISSUE TITLE
Define "brand" colors & logo

### ISSUE THREAD

**Issue by mrusme** [paperwork/paperwork#33]
A set of brand colors needs to be defined for Paperwork. The current colours were picked from http://www.google.com/design/spec/style/color.html#color-color-palette but I'm not sure if they fit the project, from an UI design aspect. The current logo was just something I drew to at least have a logo and surely could be done better.

This issue should be considered first, before working on #35, #36 or #38.

**Comment by devilx** [comment]
As webfont we should stick to Lato, as mentioned in #34. In order to do so, we need to fix #225.
