### ISSUE TITLE
the language support problem

### ISSUE THREAD

**Issue by CuberL** [paperwork/paperwork#341]
when the user's default language sets to "Chinese(Simplified)"(which i am translating now) and when login to this account it shows English. The dir name of lang files is "chi-sim",and i found the database of users' settings it only give a char(2) for "ui-language". so the "chi-sim" becomes "ch" and cause that problem.

**Comment by Baldrs** [comment]
Please use transifex for translations.

**Comment by Baldrs** [comment]
BTW, I always thought that simplified chinese code was zh-cn, and traditional was zh-tw, why are you using chi-sim?

**Comment by CuberL** [comment]
@Baldrs yeah,i think it must be zh-cn. but in file app/lang/en/language.php,it use 'chi-sim'.
And i will work on transifex these day.

**Comment by Liongold** [comment]
Is this issue still valid?

**Comment by Liongold** [comment]
Can someone confirm this issue please?
