### ISSUE TITLE
ownCloud integration

### ISSUE THREAD

**Issue by AnderRasoVazquez** [paperwork/paperwork#380]
Are you guys planning to integrate paperwork with ownCloud?

**Comment by Liongold** [comment]
What type of integration is possible exactly? Would you be interested in doing it or a part of it?

**Comment by ntnn** [comment]
I'd guess one way would be to append files from ownCloud to a note or export notes as documents to ownCloud. Appending files from ownCloud would actually be a nice feature imho, however you could just as well link them in the note.

**Comment by selurvedu** [comment]
@mrusme, is there some kind of integration available now?

**Comment by mrusme** [comment]
@selurvedu nope, and there won't.
