### ISSUE TITLE
Stored search with filters by tags

### ISSUE THREAD

**Issue by JamborJan** [paperwork/paperwork#381]
It would be good if it is possible to select a set of tags to be saved as stored search for filtering.

E.g. I have 3 kinds of tags: projects, persons and status of a task. Now I want to create a stored search for a certain project because it's high prio for all ongoing tasks. I will select the tag for the project and the tag for the status "Doing".

**Comment by admintome** [comment]
I too would like this.  Im trying to use Paperwork for "Getting Things Done" (GTD) and being able to filer by tags like @JamborJan mentioned would be awesome to help sort tasks.
