### ISSUE TITLE
Translation problem in French

### ISSUE THREAD

**Issue by clemlaf** [paperwork/paperwork#390]
In the french version of paperwork, there is an inversion between First Name and Last Name. The keywords.php file gives firstname=> Nom and lastname=> Prénom, instead of the other way around.

**Comment by Baldrs** [comment]
Don't get the question, does the order in french must be inverted or the translation is in wrong order? If the second, you can fix it on transifex.

**Comment by Liongold** [comment]
The translation is wrong. Do you have access to Transifex? You could start translating and updating translations for Paperwork.

**Comment by Liongold** [comment]
@Baldrs Do you think a pull request to fix this small thing is acceptable?

**Comment by Baldrs** [comment]
@Liongold it's better to do it on transifex, then pull and create a pull request because it will be lost on next sync with transifex. If you don't have access to the transifex, create request to join french translation and we'll approve it.

**Comment by Liongold** [comment]
Better let anyone else who is interested in doing it then. I don't know a lot of French and it doesn't make one sense doing only one change.

**Comment by Baldrs** [comment]
@Liongold ok then
@clemlaf can you fix that on transifex and then notify us so we can update the files from it?

**Comment by clemlaf** [comment]
I asked access to Paperwork on Transifex, I'll changed that as soon as I've joined the team.

**Comment by Baldrs** [comment]
You'll be added into French group as soon as @devilx sees you asked the
access.

**Comment by clemlaf** [comment]
I've done translation work on transifex.
In previous commits, I added some words to the keywords.php file that did not show on Transifex. On what schedule is Transifex repository synced with the github repository ?

**Comment by Baldrs** [comment]
Syncs English sources with github at regular schedule. All others are
pulled and overwritten by pulls from transifex. To appear in other
languages it must first appear in English sources.

**Comment by Liongold** [comment]
@clemlaf Has this been fixed?

**Comment by Liongold** [comment]
This can still be reproduced in Paperwork 
b169a1e8b46a257c9b8a9248e4ab4f9224cdcb37.
