### ISSUE TITLE
Running paperwork in subfolder / attachments

### ISSUE THREAD

**Issue by HazenBabcock** [paperwork/paperwork#401]
I could not get attachments to work properly when running paperwork in a subfolder. I had to add an additional rewrite directive to get the right path to the attachment. Is that just hiding some other configuration mistake that I made?

I was trying to follow the directions on the wiki, except that I did not use https. This is my /etc/nginx/sites-available/default file.

```
server {
    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;

    root /var/www/;
    index index.php index.html index.htm;

    # Make site accessible from http://localhost/
    server_name localhost;

    location / {
        try_files $uri $uri/ /index.php;
    }

    error_page 404 /404.html;

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
        }   

    location ~ \.php$ {
                try_files $uri =404;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                include fastcgi_params;
    }

    rewrite ^(/api/v1/.*)$ /apps/paperwork/$1 last;

    location ^~ /apps/paperwork {
            alias /var/www/paperwork/frontend/public/;

            try_files $uri $uri/ @paperwork;

            location ~* \.php {
                    fastcgi_pass unix:/var/run/php5-fpm.sock;
                    fastcgi_split_path_info ^(.+\.php)(.*)$;
                    include fastcgi_params;
            }
    }

    location @paperwork {
            rewrite ^/apps/paperwork/(.*)$ /apps/paperwork/index.php/$1 last;
    }
}
```

**Comment by olenchenko** [comment]
I have the same issue running under apache.
Any suggestions?

**Comment by Liongold** [comment]
@HazenBabcock Did you follow this wiki page: https://github.com/twostairs/paperwork/wiki/Running-paperwork-in-subfolder ?

@olenchenko Did you put the `.htaccess` file as explained in the bottom part of this page:https://github.com/twostairs/paperwork/wiki/Initial-installation ?

Sorry to both for the really late reply.

**Comment by HazenBabcock** [comment]
I was trying to. The last two location directives are directly from that example. My knowledge of nginx is minimal, but I believe that these are the only two paperwork specific directives.

**Comment by Liongold** [comment]
Could the `apps/` part of each URL be the problem? However, I don't know Nginx so can't really help more than this.

**Comment by Liongold** [comment]
Is this issue still valid?

**Comment by HazenBabcock** [comment]
I'm not sure. I have not updated my version of paperwork since reporting this.

**Comment by Liongold** [comment]
@HazenBabcock Do you want to test this? Or anyone else can? Else, we have to close it, I think.
