### ISSUE TITLE
Opnion: Improvement about Design

### ISSUE THREAD

**Issue by andre-faria** [paperwork/paperwork#404]
I was thinking In, if I could change, what to change to add more agility to paperwork:

When We add or edit a note the page switch to the edit mode, if we could edit/add a note in the main menu we can have more agility, and if we want a "no distraction mode" so we change to the "actual edit mode"

Add a button in "edit mode" to save and go to main window, because I´m lazy and hate to click, click...
![clipboard02](https://cloud.githubusercontent.com/assets/12632275/8007679/d2d1fb18-0b73-11e5-8dae-ecf68be0b673.jpg)

Where is the File menu, change it to " Add note" (so if you click in the word you will add a note) with a arrow to more options, this will help us to just click and add a note without have to click, click..
![clipboard01](https://cloud.githubusercontent.com/assets/12632275/8007678/d1151be8-0b73-11e5-934b-209bf8f9b3a0.jpg)

Instead to popup where the note should insert in (what notebook), put a dropdown to select it when the note is being edited.

**Comment by xadium** [comment]
+1
