### ISSUE TITLE
Mobile version design

### ISSUE THREAD

**Issue by vephinx** [paperwork/paperwork#416]
I tried out Paperwork on my iPhone 5s and found it not very user friendly. I've created some designs for how it could look. 

The login screen. Changed the size of the logo to avoid scrolling.
![login](https://cloud.githubusercontent.com/assets/2012398/8148273/9d0e11aa-1295-11e5-997e-11c09ca59846.png)

An article. Only an edit button added.
![article](https://cloud.githubusercontent.com/assets/2012398/8148276/b94e745e-1295-11e5-836f-d3c127f512ce.png)

List of articles. 
![list-articles](https://cloud.githubusercontent.com/assets/2012398/8148278/c6d430d2-1295-11e5-8ae0-9810d200b3bd.png)

Side menu.
![side-menu](https://cloud.githubusercontent.com/assets/2012398/8148279/ce22ac88-1295-11e5-99d3-d182f01b8f09.png)

**Comment by Baldrs** [comment]
Nice! Thank you for this!

**Comment by ekacnet** [comment]
Do you have some html/css wireframe so that it could be implemented ?

I think that the size of the fonts should be a bit smaller too.

**Comment by mrusme** [comment]
v2 [web](https://github.com/paperwork/web) is a responsive design and works on mobile as well.
