### ISSUE TITLE
provide instruction on how to recreate services.json without wiping the database

### ISSUE THREAD

**Issue by ekacnet** [paperwork/paperwork#470]
I moved from a tarball installation of paperwork to a git based instalation.
In order to get this file created (and maybe some others) I had to re-run artisan migrate, the thing is that it wiped my database content it seems.

Would be nice to have instruction on how to recreate those files (and also for instance the compiled CSS) without wiping the database.

**Comment by Baldrs** [comment]
Have you tried just to run it? It's the metadata file generated by the framework, not the part of the codebase or whatever.
