### ISSUE TITLE
API: Error 500 when creating new note

### ISSUE THREAD

**Issue by LukasDrude** [paperwork/paperwork#473]
Hello.

I am trying to work trough the API documentation [1] using Python 3. I used this guide [2] to install it on my local machine (Ubuntu 15.04).

When I do this (against your test server):

```
from urllib.request
import Request, urlopenfrom json
import dumps

values = dumps({"title":"asdf","content":"asdf"}).encode()
headers = {"Content-Type": "application/json", "Authorization": "Basic dGVzdEBwYXBlcndvcmsucm9ja3M6dGVzdDEyMw=="}
request = Request("http://private-anon-c6652c2a4-paperwork.apiary-proxy.com/api/v1/notebooks/{notebookId}/notes", data=values, headers=headers)response_body = urlopen(request).read()
print(response_body)
```

I get sucess.

When I do the same against my local installation, it fails with Error Code 500.

Whereas when I use the Curl command from [3], it won't accept PUT commands. I therefore changed it to a POST command:

```
curl --include \
     --request POST \
     --header "Content-Type: application/json" \
     --header "Authorization: Basic myBase64Token" \
     --data-binary '{"title":"New Note","content":"<p>This is a new note!</p>\n"}' \
     'http://localhost/api/v1/notebooks/358061bb-dfd9-4af4-8cb9-6704fc57b24a/notes'
```

I now get more detailed feedback:

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'content_preview' cannot be null (SQL: insert into `versions` (`title`, `content`, `content_preview`, `user_id`, `id`, `updated_at`, `created_at`) values (New Note, <p>This is a new note!</p> , , 495d4243-bf4b-4742-96e4-a35c085a33d8, fe386441-1fb4-46ce-9a2a-c828a76602f3, 2015-08-02 21:09:41, 2015-08-02 21:09:41))
```

It appears as if I always have to provide `content_preview`. Is this right? It appears as if the demo server is not running the git head (which I am running locally.

Is the node creation broken or just the docs not up to date?

[1] http://docs.paperwork.apiary.io/
[2] https://github.com/twostairs/paperwork/wiki/Installing-Paperwork-on-Ubuntu-14.10#installing-paperwork-on-ubuntu-1410
[3] http://docs.paperwork.apiary.io/#put-%2Fapi%2Fv1%2Fnotebooks%2F{notebookId}%2Fnotes%2F{noteId}

**Comment by Liongold** [comment]
Yes, the demo site is not running the latest version of Paperwork. So, this issue regards the need to always put content_preview? If yes, please rename the issue as appropriate.
