### ISSUE TITLE
Save and Close Note (Single Button)

### ISSUE THREAD

**Issue by LukasDrude** [paperwork/paperwork#477]
I wish, there was an Save-And-Close button.
The necessary modifications are probably:
- Merge the functions `$scope.updateNote = function()` and `$scope.closeNote = function()` in [1].
- Change [2] lines from 16 according to:

```
<div class="btn-group" ng-controller="SidebarNotesController">
    <a id="updateNote" href="" ng-click="updateNote()" class="btn btn-default navbar-btn"
        title="[[Lang::get('keywords.save')]]"><i class="fa fa-floppy-o"></i></a>
    <a href="" ng-click="updateAndCloseNote()" class="btn btn-default navbar-btn"
        title="[[Lang::get('keywords.close')]]">
        <i class="fa fa-floppy-o"></i>
        <i class="fa fa-times-circle"></i>
    </a>
    <a href="" ng-click="closeNote()" class="btn btn-default navbar-btn"
        title="[[Lang::get('keywords.close')]]"><i class="fa fa-times-circle"></i></a>
</div>
```

The result might look like this:
![example1](https://cloud.githubusercontent.com/assets/1886882/9047491/a698b864-3a32-11e5-9df0-c450bb57a09a.png)

 [1] https://github.com/twostairs/paperwork/blob/b238ffee31a4f3f86fbd2d7b6ba395ddfa62adc4/frontend/app/js/paperwork/sidebar/notes.controller.js#L111

 [2] https://github.com/twostairs/paperwork/blob/b238ffee31a4f3f86fbd2d7b6ba395ddfa62adc4/frontend/app/views/templates/paperworkNoteEdit.blade.php

**Comment by jamesrascal** [comment]
I like this idea. It would be handy to have a save a close feature.

**Comment by Liongold** [comment]
@LukasDrude Why don't you open a pull request? Also, what do you think about replacing the Close button with Save and close instead of adding another?

**Comment by theSoenke** [comment]
Why not autosave the note and just a close button?

**Comment by daeavelwyn** [comment]
@theSoenke I agree with you, it would be a really easier option to implement and easier to use.
