### ISSUE TITLE
Export does not contain notes without notebook

### ISSUE THREAD

**Issue by JamborJan** [paperwork/paperwork#483]
When exporting your data the export does not contain notes which are not assigned to an notebook. This because of this `join` statement during export: https://github.com/twostairs/paperwork/blob/master/frontend/app/controllers/UserController.php#L395

Question: is it a bug or a feature that you can have notes which are not assigned to a notebook? To get this scenario you simply delete a notebook which contains notes. After you did this the notes are still there when going to the "all notes" default notebook.

Please let me know if this is an export issue, then I can correct it or if this is an issue when deleting notebooks or even a design issue with the all notes default notebook view.

**Comment by JamborJan** [comment]
Hey @Liongold I guess the "pending feedback" label doesn't mean I need to deliver more details. If something is required from my side please let me know.

**Comment by Liongold** [comment]
@JamborJan No, nothing is needed from your side. However, you can of course leave your own opinion on this.

**Comment by Liongold** [comment]
@JamborJan I have contacted @devilx for more information about this and he replied saying that the deletion is working as it should. However, he said that a checkbox should be added to the notebook deletion modal, something similar to "Delete notes as well". If you want to implement this checkbox, you're more than welcome. Thus, to answer your question, the exporter should be ready for notes that do not have a notebook associated with them.

**Comment by JamborJan** [comment]
Thanks for the feedback. I will try to work on these things.

**Comment by Liongold** [comment]
@JamborJan Anything done for this as well?
