### ISSUE TITLE
Special characters in note titles are not encode in exports

### ISSUE THREAD

**Issue by JamborJan** [paperwork/paperwork#484]
When exporting a note which contains special characters like  `&`  `<`  `>` in the title, these characters are not encoded properly. This causes the import of such notes to crash.

I will try to fix that and send a PR. 

PS: if you like you can add me to the team and assign the issue to me.

**Comment by JamborJan** [comment]
The title needs to be converted with e.g. ```'title'   => htmlentities($note->title)``` then it works. I have tested this implementing it in export / import but I think this is the wrong place. It should be done when the note is saved like it is done with the note content. I have not found the right place for that in the code to test it. Will look for it further. Let me know if you have a different opinion.

**Comment by Baldrs** [comment]
Can you look into code that turns `{{` into `[[`? `{{` must escape by default.

**Comment by JamborJan** [comment]
Short status update.

I didn't find the proper place for that part of code you mentioned @Baldrs yet. Still looking into it.

I implemented a workaround for my app version which is only intend to export data from old databases in ENEX files. There I have ```'title' => htmlentities($note->title)``` in the export function. 

Doing this solves the issue for the moment but I agree that the data must be saved properly in the database and the export should only retrieve this data. Anyway for this EOL version of the package it is enough.

By doing this I found an odd situation. I managed to create a note title with an ```&nbsp;``` character which is a non-breaking space not a normal space. The importer crashes when this occurs.

There are two things to do now from my point of view and I will try to work on them:
1. make sure note titles are saved properly (this issue)
2. make the import more robust against special signs and stuff like the ```&nbsp;``` the files containing this stuff are for example import-able without any issues into evernote

**Comment by JamborJan** [comment]
Hey @Baldrs ... I'm a bit lost in the code of paperwork where to find the point where the note version is saved and a check or conversion of special signs is required. The closest I'm right now is here:

https://github.com/twostairs/paperwork/blob/master/frontend/app/controllers/api/v1/ApiNotesController.php#L340

Also here I could replace the existing code with ```'title' => htmlentities($note->title)``` but this makes no sense.

Maybe someone of the Paperwork team can look into this to find the root cause why special characters in titles are not saved properly. In the body of the note everything is done right and the special characters are encoded properly.

Thanks!

(cc @Liongold)

**Comment by Liongold** [comment]
@JamborJan From a little research I did it seems like CKEditor takes care of encoding special characters itself and thus that might explain the fact that the body is encoded well. I think special characters are not encoded simply because there's nothing asking for that in the code and thus still has to be implemented. Let me know if you have any more info. I hope I helped a little.

**Comment by JamborJan** [comment]
Hi @Liongold thats sounds reasonable. Thanks for your thoughts, I'm still not 100% sure how every single part of paperwork works which make some analysis more time consuming. I will try to implement something and make a suggestion via PR. You / a maintainer can then decide if it is good or not.

**Comment by Liongold** [comment]
@JamborJan Thanks for your work.

**Comment by Liongold** [comment]
@JamborJan Can this be closed?
