### ISSUE TITLE
Authentication required at first opening of frontend/public (popup)

### ISSUE THREAD

**Issue by ghost** [paperwork/paperwork#488]
So I followed the guide ( https://github.com/twostairs/paperwork/wiki/Initial-installation , as I'm on a shared hosting and added the RewriteBase / Rule to .htaccess in frontend/public )
and am pointing to that folder with a symlink:

> paper.x-ra.de -> html/paperwork/frontend/public/

The Problem is that there now an input form pops up, aksing me for authentication, as if it's set with the .htaccess file.

The installation is fresh and there's no problem connecting to the database.

So how do I turn that check off or how do I know the right credentials, if this is required for the first setup.

EDIT: Mine is an [uberspace](https://uberspace.de/) machine running CentOS 6, too.
Adding a new account via sub.domain.tld/login solved it for me, too.
It seems that the redirect doesn't work properly on the serverside.

**Comment by geoextra** [comment]
Had exactly the same problem a few minutes ago:
```bash
$ php paperwork/frontend/public/index.php 
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="1;url=http://:/login" />
        <title>Redirecting to http://:/login</title>
    </head>
    <body>
        Redirecting to <a href="http://:/login">http://:/login</a>.
    </body>
</html>
```

**This is not what you see in the browser!**

My server is a typical [Uberspace](uberspace.de) machine …

The solution for me was to sign up with a new user in `/login` … This need to be fixed or at least documented.

**Comment by alsternerd** [comment]
As the code that @geoextra mentions I think there's just a need to get the file where the login-redirect is being composed and set it to just
> /login

I'm still searching for that file...

**Comment by geoextra** [comment]
I think the problem could be [here](https://github.com/twostairs/paperwork/blob/master/frontend/app/filters.php#L70) …
Because of a configuration error in the `.htaccess` file Laravel things it's an AJAX request …

**Comment by Liongold** [comment]
@alsternerd @geoextra Sorry for the late reply. Can you check if this is happening only when the `.htaccess` file is pointing to a symlink? Does it happen if no symlink is used?
