### ISSUE TITLE
Restoring autosaves seems unreliable

### ISSUE THREAD

**Issue by kentonv** [paperwork/paperwork#508]
After typing some data into a note and then pausing for a moment, the words "Auto saved" briefly appear at the bottom of the note, and some data has been stored in `localStorage`. However, it seems like recovering these "auto saves" is pretty unreliable. If I literally just refresh the note-editor page, it usually seems to work, but I have yet to see it prompt to restore an auto save when I browse back to the note from the front page (as I would have to do if e.g. my browser crashed or my machine died).

This problem was originally reported by a Sandstorm user, but I was able to reproduce it on demo.paperwork.rocks, so I don't think it is Sandstorm related.

**Comment by Liongold** [comment]
I've tested this. It seems to happen after logout. Actually, I don't know whether that should be the correct behaviour.

**Comment by ardichoke** [comment]
My opinion would be that it is not the correct behavior. What good is an auto-save feature, if you lose your auto save on session timeout (which seems like it would be the most common case for a note not being saved). 

Honestly, it seems like there should be an auto-save to the server feature even if it is something optional that needs to be turned on. Perhaps something that automatically saves the note your working on as a draft every so often, and having draft saves skip the historical versioning? I don't think there are any cloud based note taking apps that rely on the user to manually save their work, and I can't think of any modern offline note taking apps that do either. If history has taught us anything, relying on the user to remember to save something is just asking for upset users when they lose data.

**Comment by Liongold** [comment]
@ardichoke Can you open a new issue for your suggestion please?

**Comment by Liongold** [comment]
@kentonv In pull request #737, the plugin used for autosaving will be updated. Can you please re-check if this issue still persists in that branch or wait until the request is merged and then re-test?

**Comment by kentonv** [comment]
Sorry, I'm not actually a Paperworks user but was just relaying a report from others, so testing out a git PR is more effort than I'm able to commit to this.

Maybe @JamborJan is interested in taking a look, though.

**Comment by JamborJan** [comment]
Hey guys, I will test this as soon as the fix is merged. I will also build a new Sandstorm version then.
