### ISSUE TITLE
为什么安装过程 有这么多的错误呢 

### ISSUE THREAD

**Issue by ghost** [paperwork/paperwork#519]
Error in exception handler: The stream or file "/var/www/html/edi/paperwork/frontend/app/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in /var/www/html/edi/paperwork/frontend/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:87

解决了一个还有 解决了 还有 都他妈的解决3天了 还没有弄完 重装服务器 多次

一开始数据库选择的时候就问题非常多

**Comment by Baldrs** [comment]
我不知道中国的语言。你需要让“storage”文件夹可写的。

**Comment by Baldrs** [comment]
能否请你用英文写的问题，或者你不知道吗？

**Comment by kongdeyuan** [comment]
![windows_chrome45](https://cloud.githubusercontent.com/assets/2070046/9872646/513f8d9a-5bcd-11e5-912a-0429f3fca1a8.png)
![linux_firefox demo](https://cloud.githubusercontent.com/assets/2070046/9872645/4e3ce49e-5bcd-11e5-95f1-f6471070bfe9.png)

**Comment by kongdeyuan** [comment]
![windows_chrome45_own](https://cloud.githubusercontent.com/assets/2070046/9872682/9ce45212-5bcd-11e5-944b-81324ea5d879.png)

**Comment by kongdeyuan** [comment]
![windows_chrome45](https://cloud.githubusercontent.com/assets/2070046/9872646/513f8d9a-5bcd-11e5-912a-0429f3fca1a8.png)
![linux_firefox demo](https://cloud.githubusercontent.com/assets/2070046/9872645/4e3ce49e-5bcd-11e5-95f1-f6471070bfe9.png)

**Comment by renyidong** [comment]
I can translate for you.

请检查你是否有/var/www/html/edi/paperwork/frontend/app/storage/logs/的写权限
Please check if you have write permission of /var/www/html/edi/paperwork/frontend/app/storage/logs/

**Comment by cenxun** [comment]
要显示**中文**的话需要更改CSS中的 font-family
记得是这个文件***paperwork-v1.min.css***
这是我修改后的
```
body {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 12px;
  line-height: 1.42857143;
  color: #424242;
  background-color: #ffffff;
}
```
