### ISSUE TITLE
sudo composer update or sudo composer install does not do anything

### ISSUE THREAD

**Issue by ellipsonic** [paperwork/paperwork#525]
Hi There, First of all I tried the demo, excellent project :), wanted to set this on my server, but whenever i do sudo composer update or sudo composer install, it does not do much

I tried googling for it and got this answer in stack-overflow

``` php
sudo rm -rf ~/.composer/cache
sudo COMPOSER=composer.json composer update 
```

but nothing seems to work

Below is my screenshot, any help will be really appreciated
![image](https://cloud.githubusercontent.com/assets/12976856/9977405/de9fe4b2-5f30-11e5-83ea-461ac17d1171.png)
- By the way, I installed composer globally as per the https://getcomposer.org/ documentation

**Comment by Liongold** [comment]
This isn't directly related to Paperwork, if I understand correctly. However, I'd suggest that either you try without sudo, or try leaving out the `COMPOSER=composer.json`argument or as a last resort, uninstall and reinstall everything. Sorry if I can't help much.

**Comment by Liongold** [comment]
Let us know how you solve the problem.

**Comment by mattcurrycom** [comment]
The "sudo COMPOSER=composer.json composer update " line should really be 2. 

Try setting:
echo "COMPOSER=composer.json" >> ~/.bash_profile 
then relogin, and try composer update.

Might have to do them with sudo, depending on your install.

**Comment by mgayanov** [comment]
Had the same problem. Solution was to configure SWAP

```
sudo dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
sudo mkswap /var/swap.1
sudo swapon /var/swap.1
```
