### ISSUE TITLE
Request: Exportables

### ISSUE THREAD

**Issue by DavidJacobson** [paperwork/paperwork#526]
Hello, I have a request for a feature that I think would be useful. This would be a way to export all notes from a notebook to a pdf, or some other format. Currently I am facing the issue of wanting to print out all notes, but there is no good way to do it. Any suggestions would be appreciated :) Thanks

**Comment by Liongold** [comment]
Thanks for your report. I don't think it can be done, unfortunately. However, you are free to improve Paperwork yourself. If you find anyway, let us know. :).

**Comment by jamesrascal** [comment]
This is related to #71 and may be a duplicate.
