### ISSUE TITLE
'New Notebook' button in 'Manage Notebooks' popup window does nothing.

### ISSUE THREAD

**Issue by berndblume** [paperwork/paperwork#528]
I just installed the latest version of paperwork today. The 'New Notebook' button in the 'Manage Notebooks' popup window is dead.
When I click 'New Notebook' under 'File', it does work.

**Comment by DavidJacobson** [comment]
I'm running into the same issue, new install of paperwork.

**Comment by Liongold** [comment]
Did you run `bower install` and `gulp`, please? Can you post the console output?

**Comment by berndblume** [comment]
Yes, I ran both. Both seemed to run through fine, no error messages.

Can’t send the console output because I already did it a few days ago… :-)

On Sep 24, 2015, at 8:17 AM, Liongold <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you run bower install and gulp, please? Can you post the console output?

**Comment by Liongold** [comment]
@berndblume The browser console output? Where? Also, is this on develop branch?

**Comment by berndblume** [comment]
Oh, sorry, you mean the browser console output! :-)

I thought you mean the console/terminal output when running `bower install` and `gulp`…

I’m using the master branch, not develop.

Here’s the browser console output:

downloadable font: Layout: lookup flag asks for mark attachment that is bad 256 (font-family: "Lato" style:normal weight:normal stretch:normal src index:2) source: https://paperwork.hau.to/fonts/Lato-Regular.woff <unknown>
downloadable font: Layout: Failed to parse lookup 6 (font-family: "Lato" style:normal weight:normal stretch:normal src index:2) source: https://paperwork.hau.to/fonts/Lato-Regular.woff <unknown>
downloadable font: GSUB: Failed to parse lookup list table, table discarded (font-family: "Lato" style:normal weight:normal stretch:normal src index:2) source: https://paperwork.hau.to/fonts/Lato-Regular.woff <unknown>
downloadable font: Layout: lookup flag asks for mark attachment that is bad 256 (font-family: "Lato" style:normal weight:normal stretch:normal src index:2) source: https://paperwork.hau.to/fonts/Lato-Regular.woff paperwork-v1.min.css:6320:12
downloadable font: Layout: Failed to parse lookup 6 (font-family: "Lato" style:normal weight:normal stretch:normal src index:2) source: https://paperwork.hau.to/fonts/Lato-Regular.woff paperwork-v1.min.css:6320:12
downloadable font: GSUB: Failed to parse lookup list table, table discarded (font-family: "Lato" style:normal weight:normal stretch:normal src index:2) source: https://paperwork.hau.to/fonts/Lato-Regular.woff paperwork-v1.min.css:6320:12
downloadable font: Layout: lookup flag asks for mark attachment that is bad 256 (font-family: "Lato" style:normal weight:bold stretch:normal src index:2) source: https://paperwork.hau.to/fonts/Lato-Bold.woff paperwork-v1.min.css:6390:12
downloadable font: Layout: Failed to parse lookup 6 (font-family: "Lato" style:normal weight:bold stretch:normal src index:2) source: https://paperwork.hau.to/fonts/Lato-Bold.woff paperwork-v1.min.css:6390:12
downloadable font: GSUB: Failed to parse lookup list table, table discarded (font-family: "Lato" style:normal weight:bold stretch:normal src index:2) source: https://paperwork.hau.to/fonts/Lato-Bold.woff paperwork-v1.min.css:6390:12
Error: $(...).editable is not a function
@https://paperwork.hau.to/js/paperwork.min.js:1145:7
$RootScopeProvider/this.$get</Scope.prototype.$emit@https://paperwork.hau.to/js/angular.min.js:13028:15
.link/<@https://paperwork.hau.to/js/paperwork.min.js:338:11
timeout/timeoutId<@https://paperwork.hau.to/js/angular.min.js:14417:28
completeOutstandingRequest@https://paperwork.hau.to/js/angular.min.js:4411:7
Browser/self.defer/timeoutId<@https://paperwork.hau.to/js/angular.min.js:4725:7
 angular.min.js:10126:18

downloadable font: Layout: lookup flag asks for mark attachment that is bad 256 (font-family: "Lato" style:normal weight:600 stretch:normal src index:2) source: https://paperwork.hau.to/fonts/Lato-Semibold.woff paperwork-v1.min.css:6360:12
downloadable font: Layout: Failed to parse lookup 6 (font-family: "Lato" style:normal weight:600 stretch:normal src index:2) source: https://paperwork.hau.to/fonts/Lato-Semibold.woff paperwork-v1.min.css:6360:12
downloadable font: GSUB: Failed to parse lookup list table, table discarded (font-family: "Lato" style:normal weight:600 stretch:normal src index:2) source: https://paperwork.hau.to/fonts/Lato-Semibold.woff paperwork-v1.min.css:6360:12
Use of getAttributeNode() is deprecated. Use getAttribute() instead. libraries.min.js:4180:0
Error: $(...).editable is not a function
@https://paperwork.hau.to/js/paperwork.min.js:1145:7
$RootScopeProvider/this.$get</Scope.prototype.$emit@https://paperwork.hau.to/js/angular.min.js:13028:15
.link/<@https://paperwork.hau.to/js/paperwork.min.js:338:11
timeout/timeoutId<@https://paperwork.hau.to/js/angular.min.js:14417:28
completeOutstandingRequest@https://paperwork.hau.to/js/angular.min.js:4411:7
Browser/self.defer/timeoutId<@https://paperwork.hau.to/js/angular.min.js:4725:7
 angular.min.js:10126:18

downloadable font: Layout: lookup flag asks for mark attachment that is bad 256 (font-family: "Lato" style:normal weight:500 stretch:normal src index:2) source: https://paperwork.hau.to/fonts/Lato-Medium.woff paperwork-v1.min.css:6340:12
downloadable font: Layout: Failed to parse lookup 6 (font-family: "Lato" style:normal weight:500 stretch:normal src index:2) source: https://paperwork.hau.to/fonts/Lato-Medium.woff paperwork-v1.min.css:6340:12
downloadable font: GSUB: Failed to parse lookup list table, table discarded (font-family: "Lato" style:normal weight:500 stretch:normal src index:2) source: https://paperwork.hau.to/fonts/Lato-Medium.woff paperwork-v1.min.css:6340:12
downloadable font: Layout: lookup flag asks for mark attachment that is bad 256 (font-family: "Lato" style:normal weight:300 stretch:normal src index:2) source: https://paperwork.hau.to/fonts/Lato-Light.woff paperwork-v1.min.css:6300:12
downloadable font: Layout: Failed to parse lookup 6 (font-family: "Lato" style:normal weight:300 stretch:normal src index:2) source: https://paperwork.hau.to/fonts/Lato-Light.woff paperwork-v1.min.css:6300:12
downloadable font: GSUB: Failed to parse lookup list table, table discarded (font-family: "Lato" style:normal weight:300 stretch:normal src index:2) source: https://paperwork.hau.to/fonts/Lato-Light.woff paperwork-v1.min.css:6300:12

On Sep 26, 2015, at 5:39 AM, Liongold <notifications@github.com<mailto:notifications@github.com>> wrote:


@berndblume<https://github.com/berndblume> The browser console output? Where? Also, is this on develop branch?

**Comment by nebulade** [comment]
I am getting the same error:
```
Error: $row.find(...).editable is not a function
$scope.addNotebook@https://paper-berlin.cloudron.me/js/paperwork.min.js:1215:7
Parser.prototype.functionCall/<@https://paper-berlin.cloudron.me/js/angular.min.js:10903:15
ngEventHandler/</callback@https://paper-berlin.cloudron.me/js/angular.min.js:19259:17
$RootScopeProvider/this.$get</Scope.prototype.$eval@https://paper-berlin.cloudron.me/js/angular.min.js:12811:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@https://paper-berlin.cloudron.me/js/angular.min.js:12909:18
ngEventHandler/<@https://paper-berlin.cloudron.me/js/angular.min.js:19264:17
jQuery.event.dispatch@https://paper-berlin.cloudron.me/js/jquery.min.js:4669:15
jQuery.event.add/elemData.handle@https://paper-berlin.cloudron.me/js/jquery.min.js:4338:6
EventListener.handleEvent*jQuery.event.add@https://paper-berlin.cloudron.me/js/jquery.min.js:4388:7
.on/<@https://paper-berlin.cloudron.me/js/jquery.min.js:5249:4
.each@https://paper-berlin.cloudron.me/js/jquery.min.js:384:14
jQuery.prototype.each@https://paper-berlin.cloudron.me/js/jquery.min.js:136:10
.on@https://paper-berlin.cloudron.me/js/jquery.min.js:5248:1
ngEventHandler@https://paper-berlin.cloudron.me/js/angular.min.js:19257:13
nodeLinkFn@https://paper-berlin.cloudron.me/js/angular.min.js:6752:13
compositeLinkFn@https://paper-berlin.cloudron.me/js/angular.min.js:6146:13
compositeLinkFn@https://paper-berlin.cloudron.me/js/angular.min.js:6149:13
compositeLinkFn@https://paper-berlin.cloudron.me/js/angular.min.js:6149:13
compositeLinkFn@https://paper-berlin.cloudron.me/js/angular.min.js:6149:13
nodeLinkFn@https://paper-berlin.cloudron.me/js/angular.min.js:6746:1
compositeLinkFn@https://paper-berlin.cloudron.me/js/angular.min.js:6146:13
compositeLinkFn@https://paper-berlin.cloudron.me/js/angular.min.js:6149:13
publicLinkFn@https://paper-berlin.cloudron.me/js/angular.min.js:6042:30
bootstrap/doBootstrap/</<@https://paper-berlin.cloudron.me/js/angular.min.js:1449:11
$RootScopeProvider/this.$get</Scope.prototype.$eval@https://paper-berlin.cloudron.me/js/angular.min.js:12811:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@https://paper-berlin.cloudron.me/js/angular.min.js:12909:18
bootstrap/doBootstrap/<@https://paper-berlin.cloudron.me/js/angular.min.js:1447:9
invoke@https://paper-berlin.cloudron.me/js/angular.min.js:3965:14
bootstrap/doBootstrap@https://paper-berlin.cloudron.me/js/angular.min.js:1445:1
bootstrap@https://paper-berlin.cloudron.me/js/angular.min.js:1459:1
angularInit@https://paper-berlin.cloudron.me/js/angular.min.js:1368:5
@https://paper-berlin.cloudron.me/js/angular.min.js:22149:5
jQuery.Callbacks/fire@https://paper-berlin.cloudron.me/js/jquery.min.js:3148:10
jQuery.Callbacks/self.fireWith@https://paper-berlin.cloudron.me/js/jquery.min.js:3260:7
.ready@https://paper-berlin.cloudron.me/js/jquery.min.js:3472:1
completed@https://paper-berlin.cloudron.me/js/jquery.min.js:3503:3
EventListener.handleEvent*jQuery.ready.promise@https://paper-berlin.cloudron.me/js/jquery.min.js:3522:4
jQuery.fn.ready@https://paper-berlin.cloudron.me/js/jquery.min.js:3428:2
jQuery.fn.init@https://paper-berlin.cloudron.me/js/jquery.min.js:2868:5
jQuery@https://paper-berlin.cloudron.me/js/jquery.min.js:73:10
@https://paper-berlin.cloudron.me/js/jquery.min.js:3586:1
@https://paper-berlin.cloudron.me/js/jquery.min.js:34:3
@https://paper-berlin.cloudron.me/js/jquery.min.js:15:1
```

I am also on develop branch revision be9946a047388e334d1d5eea8c2f33945d04108c

**Comment by Liongold** [comment]
Sorry for asking too much. @berndblume can you try the develop branch? @nebulade Do you notice any 404 errors in the Network tab of your developer tools console? Do you have a folder named x-editable in the bower_components folder, please?

**Comment by nebulade** [comment]
indeed, I do get 404 twice for the same file:

```
GET 
https://paper-berlin.cloudron.me/js/bootstrap-editable.min.js [HTTP/1.1 404 Not Found 324ms]
GET 
https://paper-berlin.cloudron.me/js/bootstrap-editable.min.js [HTTP/1.1 404 Not Found 174ms]
```
I also miss the *x-editable* folder in bower_components, the content is:
```
angular              angular-highlightjs  angular-route               bootstrap            bootstrap3-ie10-viewport-bug-workaround  html5shiv                jquery.scrollTo  rangy     textAngular
angular-animate      angular-loading-bar  angular-ui-bootstrap-bower  bootstrap-css-only   es5-shim                                 jquery                   ngDraggable      respond   typeahead.js
angular-file-upload  angular-resource     angular-utf8-base64         bootstrap-tagsinput  font-awesome                             jquery-overscroll-fixed  placeholders     retinajs
```

So I assume that's the missing part then.

**Comment by Liongold** [comment]
@nebulade Soory again. But did you run bower install after git pull?

**Comment by nebulade** [comment]
@Liongold sorry, I was looking at an older commit, earlier. The current HEAD is working just fine now. Interesting concept to have the notebook edit field in an additional popup dialog/bubble on top of the notebooks dialg. :smirk:

**Comment by Liongold** [comment]
@berndblume Any progress on your side?

**Comment by berndblume** [comment]
Can you help me find a description how to upgrade without losing my database contents?

I can clone HEAD, and then? Everything again, as if it’s a fresh install?

Thanks, Bernd

On Sep 29, 2015, at 9:55 AM, Liongold <notifications@github.com<mailto:notifications@github.com>> wrote:


@berndblume<https://github.com/berndblume> Any progress on your side?

**Comment by Liongold** [comment]
Try `git checkout develop`, `git pull`, `composer install`, `npm install`, `bower install` and `gulp`. Do not run `php artisan migrate`. To be 100% sure, you can also take a backup of the whole database before doing this.

**Comment by berndblume** [comment]
Hi and thanks.
I did what you suggested, made sure database.php points to the same database I was using in the old paperwork installation.
I then navigated to (the new) paperwork in my browser. I was told paperwork cannot connect to github to check for the latest version. No hint about why not - I *can* connect from the command line. I added an env[HOME] directive to my php-fpm.conf to make sure php has the right HOME in order to find $HOME/.ssh in order to connect to github: Still the same message.

I just clicked Next, then I was asked to enter database credentials even though I have entered them into my database.php. So I entered the database credentials again in the GUI (I was asked for URL, Port, user and password, but not for the database name. Then obviously paperwork created a new database (without asking), may overwriting my old “paperwork” database. Then I was asked to register my “first” user (even though the user was already registered in my “old” database”. So I filled out all the fields in “Registering your first user”, clicked on the button “Sign Up”, and nothing happens. The form stays there and I can click and click that button.

In essence, paperwork seems to be pretty much unusable at the current state of affairs…

Thanks, Bernd

On Oct 1, 2015, at 7:47 AM, Liongold <notifications@github.com<mailto:notifications@github.com>> wrote:


Try git checkout develop, git pull, composer install, npm install, bower install and gulp. Do not run php artisan migrate. To be 100% sure, you can also take a backup of the whole database before doing this.

**Comment by Liongold** [comment]
@berndblume I'm very sorry that you're having this trouble. However, it is happening because of the delicate situation you are in. Firstly, if you still have the old database, please make a backup of it because it will be overwritten. About the git message, it can be because of various reasons. Most likely, it is that either the Github API did not work or your install lacks the php curl package. Reagarding database.php, the details there should not be considered. Since the Setup Wizard was implemented, that file isn't used to set options anywhere. If you want to configure Paperwork without using the wizard, please follow the instructions in this page: https://github.com/twostairs/paperwork/wiki/Installing-and-configuring-Paperwork-without-using-the-Setup-Wizard. Regarding the registration problem, can you show us the console output?

Sorry again. However, Paperwork is usable but as expected from software in a stage of development where we are, it is expected that some thigns might now be 100% polished. And I admit that the Setup Wizard is one of the least polished areas but it should still work and is still in progress.

**Comment by Liongold** [comment]
Is this issue still valid? Paperwork now has an updated setup wizard feature.

**Comment by berndblume** [comment]
Hi there and thanks for letting me know!

I didn’t try paperwork anymore because of the problems I had. I’ll try again now and let you know…

Thanks, Bernd
