### ISSUE TITLE
Implement a "guided tour through Paperwork"

### ISSUE THREAD

**Issue by mrusme** [paperwork/paperwork#53]
To make it even more easy for users to start using Paperwork, something like a "guided tour through Paperwork" would be cool. This should be something similar to what other services do: A message right at the beginning, asking the user whether he'd like a guided tour. If the user accepts, bubble-tooltips should pop up above the UI, showing the user the most important features of Paperwork. These tooltips should appear one after another and advance as soon as the user clicks/taps.

**Comment by jamesrascal** [comment]
To start this could be added as a "default" note. So when you register you have a note with an overview of what Paperwork is and how to use it.

**Comment by devilx** [comment]
Info: @Liongold already implemented one point from this issue by fixing #52.

**Comment by jasondavis** [comment]
I have been testing and researching the available libraries or this functionality and on of the best I have found is from Hubspot, they have created a library called ShepHerd http://github.hubspot.com/shepherd/

It's really nice and easy to use.  Has some nice features like scroll to and a good UI.  It's easy to use as you define the Tour "Steps" with the content and then assign which buttons to show and an action for each button on each step.

**Github page:** https://github.com/HubSpot/Shepherd

**Project websaite:** http://github.hubspot.com/shepherd/

**Demo Tour page:** http://github.hubspot.com/shepherd/docs/welcome/
