### ISSUE TITLE
New Notebook button broken

### ISSUE THREAD

**Issue by tommyhp2** [paperwork/paperwork#534]
Hi,

I've installed Paperwork to use Apache/2.4.16 (Fedora 22) PHP/5.6.13 as follow since the MariaDB is on another server and httpd is already configured:

$ dnf install curl git php php-cli php-gd php-mcrypt php-mysqlnd wget nodejs

$ mkdir -p /var/www/html && cd /var/www/html
$ git clone https://github.com/twostairs/paperwork.git
$ cd /var/www/html/paperwork/frontend
$ curl -sS https://getcomposer.org/installer | php

Create the DB and credential.  Modify the DB configuration in database.php in:
- paperwork/frontend/app/config/database.php
- paperwork/frontend/app/config/local/database.php

$ php composer.phar install
$ php artisan migrate
$ wget https://www.npmjs.org/install.sh
$ bash ./install.sh
$ npm install -g gulp bower
$ npm install
$ bower install
$ gulp
$ chown -R apache:apache /var/www/html/paperwork

I could create a new account and login OK.  When I try to create a new notebook, the button doesn't do anything (in Chrome 45.0.2454.99, Chrome 45.0.2454.101, FireFox 40.0.3, and FireFox 41.0).  Did I skipped a step?

Thanks,
Tommy

**Comment by tommyhp2** [comment]
Checking the DB, I see the following entries in the DB:

select * from notebooks;
+--------------------------------------+-----------+------+---------+---------------------+---------------------+------------+
| id                                   | parent_id | type | title   | created_at          | updated_at          | deleted_at |
+--------------------------------------+-----------+------+---------+---------------------+---------------------+------------+
| 2a2a1804-6ce1-465b-b44c-29e5b7311669 | NULL      |    0 | Welcome | 2015-09-26 15:03:32 | 2015-09-26 15:03:32 | NULL       |
+--------------------------------------+-----------+------+---------+---------------------+---------------------+------------+
1 row in set (0.00 sec)

 select * from notebook_user;
+----+--------------------------------------+--------------------------------------+-------+---------------------+---------------------+
| id | user_id                              | notebook_id                          | umask | created_at          | updated_at          |
+----+--------------------------------------+--------------------------------------+-------+---------------------+---------------------+
|  1 | c10f129e-d3d0-4bac-be2b-e6632f1af769 | 2a2a1804-6ce1-465b-b44c-29e5b7311669 |     7 | 2015-09-26 15:03:32 | 2015-09-26 15:03:32 |
+----+--------------------------------------+--------------------------------------+-------+---------------------+---------------------+
1 row in set (0.00 sec)

select id,username,is_admin,created_at,updated_at,deleted_at from users;
+--------------------------------------+--------------+----------+---------------------+---------------------+------------+
| id                                   | username     | is_admin | created_at          | updated_at          | deleted_at |
+--------------------------------------+--------------+----------+---------------------+---------------------+------------+
| c10f129e-d3d0-4bac-be2b-e6632f1af769 | dev@corp.net |        1 | 2015-09-26 15:03:32 | 2015-09-26 15:07:45 | NULL       |
+--------------------------------------+--------------+----------+---------------------+---------------------+------------+
1 row in set (0.00 sec)


Shouldn't I see the 'Welcome' notebook in GUI but I don't? :-(

**Comment by tommyhp2** [comment]
![paperwork_20150926](https://cloud.githubusercontent.com/assets/6822623/10118270/50ce6ea8-6429-11e5-9eca-bb0eb13c6b7d.PNG)

**Comment by Liongold** [comment]
Did you use the Setup Wizard? Are you on develop branch?

**Comment by tommyhp2** [comment]
Hi Liongold,

I used the install instructions at:

https://github.com/twostairs/paperwork/wiki/Initial-installation
https://github.com/twostairs/paperwork/wiki/Installation-----CentOS-Fedora

As for branch, I don't know which branch is provided by:

git clone https://github.com/twostairs/paperwork.git

Thanks.

**Comment by Liongold** [comment]
@tommyhp2 Can you try doing `git checkout develop` and then the normal `composer install, npm installl, bower install and gulp`? Any difference in the result?

**Comment by tommyhp2** [comment]
Different results but app is now broken.
![paperwork_20150929_not_latest_version](https://cloud.githubusercontent.com/assets/6822623/10184482/f9c6e4ac-66f1-11e5-8cef-2f4e2211164f.PNG)
Seems to be missing textbox for DB name.. ?
![paperwork_20150926_setting_up_db](https://cloud.githubusercontent.com/assets/6822623/10184490/01e5e278-66f2-11e5-8a0b-a290de4b9e23.PNG)
![paperwork_20150929_registering_1st_user_account](https://cloud.githubusercontent.com/assets/6822623/10184496/078e5890-66f2-11e5-81a7-dba709b05f4d.PNG)
![paperwork_20150929_configurating](https://cloud.githubusercontent.com/assets/6822623/10184501/10f55b72-66f2-11e5-8547-67f9b83190c8.PNG)

Clicking next on configurating screen does nothing :(.

I've create a shell script to install paperwork on Fedora 22 that will log output to a file for troubleshooting but unable to attach both shell script and log file. :(

**Comment by tommyhp2** [comment]
I've uploaded both the Linux shell script (please feel free to distribute with the source if you like) and the logs to my profile at: https://github.com/tommyhp2/misc/tree/master/paperwork.  Install logs shows installed RPMs for nodejs and npm.  Also shows installed npm modules with versions.

**Comment by Liongold** [comment]
The database name is always paperwork. That's why it isn't included. Try running the source code as available. Also, did you have the database paperwork available when you tried the Check Connection and Install Database? Sorry for asking so much questions. About the scripts, very interesting and could be very useful. However, you should open a pull request to develop branch for them.

**Comment by tommyhp2** [comment]
The "Check connection and Install database" is broken even when I change the DB host in paperwork/frontend/app/config/database.php.  There's no outgoing connection in netstat and I know the account works by mysql -u paperwork -h db-host -p paperwork works just fine from the web server.

**Comment by Liongold** [comment]
database.php should not be changed. If you want to configure everything but skipping the wizard, please follow this wiki page: https://github.com/twostairs/paperwork/wiki/Installing-and-configuring-Paperwork-without-using-the-Setup-Wizard.

**Comment by tommyhp2** [comment]
still broken :(

![paperwork_20151005](https://cloud.githubusercontent.com/assets/6822623/10293197/1b8e2c60-6b68-11e5-95a2-e044e760c155.png)

My PHP code to verify the credentials works fine as it able to connect and run a select statement.  So I know the problem isn't the credential.

**Comment by tommyhp2** [comment]
Same error occurs when recreating the DB and credential.
![paperwork_20151005_recreate](https://cloud.githubusercontent.com/assets/6822623/10293557/e9ff4b1e-6b69-11e5-88a5-9a943acdc18e.png)

**Comment by Liongold** [comment]
@tommyhp2 What's the content of the `app/storage/db_settings` file?

**Comment by tommyhp2** [comment]
[root@d-f22-web frontend]# cat app/storage/db_settings
mysql, 10.110.0.2, 3306, paperwork, paperwork

**Comment by sdiver78** [comment]
"The database name is always paperwork." ... I know my host won't allow this as it's appended by the account name such as account_paperwork. Would suggest all be changeable/parameterized in the new db_settings file.

**Comment by tommyhp2** [comment]
I found the bug... I modified the:

```
paperwork/frontend/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php
```
to 
```
var_dump($dsn, $config, $options);
```
to verify the parameters which are correct but still failed...
![paperwork_20151007](https://cloud.githubusercontent.com/assets/6822623/10357180/15defd3a-6d34-11e5-8551-42662dc166d4.png)
Note the EOL char after the password? So I modified the same file from 
```
        public function createConnection($dsn, array $config, array $options)
        {
                $username = array_get($config, 'username');
                $password = array_get($config, 'password');

                return new PDO($dsn, $username, $password, $options);
        }
```
to
```
        public function createConnection($dsn, array $config, array $options)
        {
                $username = array_get($config, 'username');
                $password = trim(array_get($config, 'password'));

                return new PDO($dsn, $username, $password, $options);
        }
```
and tada!!!
![paperwork_20151007_works](https://cloud.githubusercontent.com/assets/6822623/10357285/30775a1a-6d35-11e5-8c1d-de640251dab6.png)
Instead of modifying the ```Connector.php```, I'm proposing modifying the file:
```
app/config/database.php
```
from
```
if(File::exists(storage_path()."/db_settings")) {
    $wholeString = file_get_contents(storage_path()."/db_settings");
    $databaseInfo = explode(", ", $wholeString);
}else{
```
to
```
if(File::exists(storage_path()."/db_settings")) {
    $wholeString = file_get_contents(storage_path()."/db_settings");
    $databaseInfo = explode(", ", $wholeString);
    $databaseInfo[4] = trim($databaseInfo[4]);
}else{
```

**Comment by tommyhp2** [comment]
But the new Notebook button is still broken :(... I'm back to square one.. LOL
![paperwork_20151007_ui](https://cloud.githubusercontent.com/assets/6822623/10357399/a854659a-6d36-11e5-86eb-343c1f4df307.png)

**Comment by Liongold** [comment]
@tommyhp2 Not really. You've suggested 2 improvements for the Setup Wizard and now your solution can be used for all other users. Now, regarding your problem? Can you post screenshots of the Network and Console tabs of your developer tools console, please?

**Comment by tommyhp2** [comment]
After fiddling some more by removing nodejs and npm in addition to deleting ~/.npm directory, I finally got the "New Notebook" to appear.  But I can't type anything for the new entry.

![paperwork_20151127](https://cloud.githubusercontent.com/assets/6822623/11447261/459269c2-94f8-11e5-8069-4019b3e7d815.PNG)

**Comment by Liongold** [comment]
@tommyhp2 That shouldn't be needed. Further investigations are required. @sdiver78 A future update of the wizard may change this, sorry for the inconvenience.

**Comment by tommyhp2** [comment]
I just tried to install on Centos 6.7 and 7.1, C6.7 resulting in HTTP500 and C7.1 resulting the same new entry problem.  However, it seems to work on Ubuntu 14.0.4 LTS.

**Comment by Liongold** [comment]
@tommyhp2 Sorry for the late reply. Do you notice any differences in the browser console output between the different versions, please?
