### ISSUE TITLE
Display PDFs Inline

### ISSUE THREAD

**Issue by itisNathaniel** [paperwork/paperwork#535]
Hi I was wondering if there was a way for PDFs uploaded as attachments to appear inline with text instead of just a button taking you to another page. In a way allowing you to write around the PDF that's embedded and describe it if you have multiple PDFs together. 
I like the way evernote does this with PDFs and images, I've attached pictures of the way paperwork currently responds and the way evernote does.

Thanks! :)
Evernote:
![screen shot 2015-09-27 at 16 12 56](https://cloud.githubusercontent.com/assets/4061191/10123500/d610e0aa-6532-11e5-8a4c-ad778e009984.png)
Paperwork:
![screen shot 2015-09-27 at 16 13 03](https://cloud.githubusercontent.com/assets/4061191/10123501/d62c8c92-6532-11e5-9b9d-955078381b2a.png)

**Comment by Liongold** [comment]
That isn't possible for PDFs right now. You can have that effect for images if you put the image in the note itself (not as an attachment). However, you or someone else from the community can implement this.
