### ISSUE TITLE
Missing Jquery Bootstrap and Angular.js files -> empty content window

### ISSUE THREAD

**Issue by shinedown99** [paperwork/paperwork#550]
Hi I was installing step by step after the manual. 

The Main screen stays empty and I can see following in the errors in the browser log:

Still it is missing the Javascript libs:
Failed to load resource: the server responded with a status of 404 (Not Found)
Failed to load resource: the server responded with a status of 404 (Not Found)
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught ReferenceError: jQuery is not defined
Uncaught ReferenceError: angular is not defined
Uncaught Error: Bootstrap's JavaScript requires jQuery
Failed to load resource: the server responded with a status of 404 (Not Found)

How can I install the libs?
Thank you Hank

**Comment by burakkaptan** [comment]
Hello, 

Did you follow installation process for your OS ?  For example i installed it by looking this page: https://github.com/twostairs/paperwork/wiki/Initial-installation

**Comment by Liongold** [comment]
Any progress on this?
