### ISSUE TITLE
Public Note Sharing

### ISSUE THREAD

**Issue by jamesrascal** [paperwork/paperwork#556]
Now that the sharing feature is working in the master build. Would it be possible to implement a public sharing of some kind?

Maybe have it as an option when you click share to select public as the "user" then have paperwork generate a link. 

There would also need to be an option to remove the sharing feature from public as well. 

Additional the ability to share an entire notebook publicly would be beneficial.

**Comment by nikohd** [comment]
Could we also have a control to limit shares?
