### ISSUE TITLE
Admin web front-end

### ISSUE THREAD

**Issue by mrusme** [paperwork/paperwork#56]
As soon as #55 was implemented, an administrative web front-end could be built. For that, an additional menu-entry in between of "Settings" and "Help" could appear, as soon as the user has admin rights.

The admin area could contain initially of the following features:
- User management:
  - Listing all registered users
  - Showing information about each individual user (account data, usage, account activity, etc.)
  - Administrative functions (changing the login e-mail address, disabling the account, permanently deleting the account, quota settings, etc.)
- Paperwork settings
  - Basically a web front-end that allows configuration of `/app/config/paperwork.php`
- Server settings
  - A web front-end that allows configuration of `/app/config/auth.php` (as soon as #28 was being implemented)
  - A web front-end that allows configuration of `/app/config/cache.php`
  - A web front-end that allows configuration of `/app/config/mail.php`
  - A web front-end that allows configuration of `/app/config/queue.php`
  - A web front-end that allows configuration of `/app/config/session.php`
  - A web front-end that allows configuration of `/app/config/mail.php`

Thoughts?

**Comment by jamesrascal** [comment]
The addition of a one click "upgrade" option would be nice.

**Comment by devilx** [comment]
@jamesrascal :+1:

**Comment by joshlemer** [comment]
Currently working on this in https://github.com/joshlemer/paperwork/tree/admin-console

**Comment by jamesrascal** [comment]
I think there needs to be a check in place, if you are upgrading from an older version and there is only one users is should change the "is_admin" to 1. Otherwise you are stuck going through and making that change in your database.

**Comment by devilx** [comment]
@joshlemer :+1: if you'll push the branch to the official repo, make sure to keep the current naming convention ("issue-<xy>-<type>", as in "issue-56-feature").

**Comment by joshlemer** [comment]
@devilx yep sorry about that

**Comment by joshlemer** [comment]
@jamesrascal What if there are multiple users? Should the earliest-created user become admin?

**Comment by jamesrascal** [comment]
@joshlemer The idea was yes the earliest user would become the admin. This might even be a non-issue as it will only effect early builds. Newer builds will auto make the first user and admin.
