### ISSUE TITLE
[QUESTION] Docker -> DB running local?

### ISSUE THREAD

**Issue by Berndinox** [paperwork/paperwork#584]
Hy,

cause i have running PHP7 on my Webserver, i would like to run the Webapp inside Docker, but use the localy installed MySQL DB. Storing the files in a local Path woudl also be great.

Are there any Documents available to achive this solution?

Thanks, BR

**Comment by Baldrs** [comment]
You can add /var/run/mysql of host as volume

**Comment by Liongold** [comment]
Is this fixed?
