### ISSUE TITLE
Sponsor a demo

### ISSUE THREAD

**Issue by jasondavis** [paperwork/paperwork#585]
I am curious what kind of costs would be involved to sponsor an up to date demo server?  Would a basic 5-10$ a month Digital Ocean server be enough or is the traffic too high?

**Comment by Baldrs** [comment]
$10 should be enough

**Comment by kmf** [comment]
is there a paypal account?

**Comment by Baldrs** [comment]
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=TVXPLDTDYHRK8
