### ISSUE TITLE
Unable to setup on ubtunu  15.10

### ISSUE THREAD

**Issue by ddonindia** [paperwork/paperwork#587]
Hi,

I am following installation steps on https://github.com/twostairs/paperwork/wiki/Installing-Paperwork-on-Ubuntu-14.10.
But after hosing paperwork on my nginx server and mysql db I am seeing following problems
1. Even if I go for manual configuration by creating db_settings file I am always getting setup wizard.
2. If i go with setup wizard when I try to create new user on next screen I am getting error stack:

> 1. Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
>    …/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­RouteCollection.php210
> 2. Illuminate\Routing\RouteCollection methodNotAllowed
>    …/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­RouteCollection.php197
> 3. Illuminate\Routing\RouteCollection getOtherMethodsRoute
>    …/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­RouteCollection.php145
> 4. Illuminate\Routing\RouteCollection match
>    …/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Router.php1054
> 5. Illuminate\Routing\Router findRoute
>    …/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Router.php1022
> 6. Illuminate\Routing\Router dispatchToRoute
>    …/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Router.php1001
> 7. Illuminate\Routing\Router dispatch
>    …/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Application.php775
> 8. Illuminate\Foundation\Application dispatch
>    …/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Application.php745
> 9. Illuminate\Foundation\Application handle
>    …/­vendor/­laravel/­framework/­src/­Illuminate/­Session/­Middleware.php72
> 10. Illuminate\Session\Middleware handle
>     …/­vendor/­laravel/­framework/­src/­Illuminate/­Cookie/­Queue.php47
> 11. Illuminate\Cookie\Queue handle
>     …/­vendor/­laravel/­framework/­src/­Illuminate/­Cookie/­Guard.php51
> 12. Illuminate\Cookie\Guard handle
>     …/­vendor/­stack/­builder/­src/­Stack/­StackedHttpKernel.php23
> 13. Stack\StackedHttpKernel handle
>     …/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Application.php641
> 14. Illuminate\Foundation\Application run
>     …/­public/­index.php49

can someone please help?

**Comment by ddonindia** [comment]
anyone ?

**Comment by ddonindia** [comment]
Is this project still maintained ?

**Comment by Baldrs** [comment]
@ddonindia it is but don't expect us to do everything instead of you. Also please try docker version as it is less platform-dependent

**Comment by mattcurrycom** [comment]
yeah they haven't really created good documentation; and the install instructions are incorrect even for the ones 'supported'; very dissapointed at this point in this project.  I really thought it had promise.  But if managed like this going forward it will fail.

**Comment by Baldrs** [comment]
@mattcurrycom this is open source software, if you feel that documentation, which was made for free by contributors is bad, feel free to improve it, otherwise just go away.

**Comment by ddonindia** [comment]
@Baldrs sorry I didn't mean disrespect for you or any other developer of this project. I was not able to figure out of my own whats going on in my env thats why I asked.
I see lots of potential in this project.

**Comment by mattcurrycom** [comment]
@Baldrs no need to get butt hurt, I was just being honest. I am actually trying to help. Sorry if it came across hostile.  I just really like the project, and want it to succeed. I just am a bit disappointed that its not a bit more stable. I personally have tried 3 installs and still don't have it running.  If I get time, I will dig into them and see what I can do to help.  I am just not a node/php guy.  As far as the documentation, I would be happy to help improve it once I get a working install that I understand a little better.

**Comment by davidtorcivia** [comment]
I also ran into this problem and the setup wizard kept looping (Ubuntu 15.04). I found that manually creating a db_settings file with the mysql info described in the manual set up page followed by removing the setup file (all in the storage folder) fixed the issue and I was able to login successfully.

There's some frustration in this thread so I wanted to take a moment and thank the developers for this software. There's a desperate need for open source, self hosted note taking software and paperwork fills that void with style. Thanks to everyone involved!

**Comment by jamesrascal** [comment]
I am working on an updated wiki for this https://github.com/twostairs/paperwork/wiki/Installing-Paperwork-on-Ubuntu-16.04-(WIP)

**Comment by necrevistonnezr** [comment]
It would be great to include instructions for PostgreSQL, as well....

**Comment by jamesrascal** [comment]
It wouldn't be to hard to update the wiki to include them. This gives a baseline for the install.

**Comment by mrusme** [comment]
Sorry to hear that contributors behaved badly here. Hope this won't happen again.
