### ISSUE TITLE
Unable to install: (autoload.php) failed to open stream

### ISSUE THREAD

**Issue by eroji** [paperwork/paperwork#596]
Following the install documentation on CentOS 7. I changed the database to Percona 5.6 only. However, when I get to the step to run

```
php artisan migrate
```

I get:

```
PHP Warning:  require(/var/www/html/paperwork/frontend/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/paperwork/frontend/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/html/paperwork/frontend/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/paperwork/frontend/bootstrap/autoload.php on line 17
```

**Comment by Liongold** [comment]
Can you try installing composer and then running `composer install`, and then tell us your results please? It seems like that article might need to be updated. Thanks for your interest in Paperwork. 

More information about Composer can be found [here](getcomposer.org/).

**Comment by eroji** [comment]
I rebuilt the VM and redid the install from beginning to end. It seemed to have worked but when I browse to the homepage, it is asking me to configure the database connection and errors when I tell it to test the connection after that.

**Comment by Liongold** [comment]
Can you show a screenshot of the Network tab of the Developer Tools, please? If you can, please also post a shot of the request content that has a URL similar to `/checkDB`.

**Comment by Liongold** [comment]
The setup wizard has been updated. Can you recheck this issue, please?

**Comment by whodafly** [comment]
Just to add a note here: I'm running PHP7 on Ubuntu 16.04, and I got the same error as @eroji and it "went away" after running composer. The site says to install composer, but it doesn't say to run it. That would be a helpful addition.

Now, however, artisan is segfaulting on me. No idea how to fix that yet, or where the segfault is happening.

**Comment by whodafly** [comment]
My bad, I just re-read the installation instructions and it says to run "composer install". Perhaps OP missed it like I did.

I still can't figure out why php is segfaulting when running artisan though.

**Comment by Liongold** [comment]
Can this be closed then?

**Comment by whodafly** [comment]
From my side, yes. Not sure about OP.
