### ISSUE TITLE
OpenLDAP compatible?

### ISSUE THREAD

**Issue by patriclougheed** [paperwork/paperwork#605]
I cannot get my instance to authenticate with my OpenLDAP server. I have around a dozen other open source apps working fine (Owncloud,Moodle) but all attempts have failed to connect Paperwork. I suspect the AdLDAP library has issues and wonder has anyone else confirmed this working.

**Comment by patriclougheed** [comment]
Any chance LDAPtools can be added as an auth source:

https://github.com/ldaptools/ldaptools
 
or at least upgrade to adLDAP2:

https://github.com/Adldap2/Adldap2

**Comment by Liongold** [comment]
What are the issues with the actual library?

**Comment by patriclougheed** [comment]
https://github.com/adldap/adLDAP/issues/66

**Comment by Liongold** [comment]
Any help is accepted to help integrate the new library in Paperwork.

**Comment by JeyDee** [comment]
+1

**Comment by Liongold** [comment]
@JeyDee Do you think you could be able to build this feature and contribute it to Paperwork yourself? Unfortunately, there's no one, who is currently working on the LDAP functionality, so help is needed on this issue.

**Comment by JeyDee** [comment]
@Liongold I'm have no affinity to web technologies and therefore lack the knowledge to do so, unfortunatelly. I'm more of a C++ guy. I solved this situation for me by changing a few lines of the code, but I consider my approach a dirty hack at best.. Nothing worth contributing to the repository, I'm afraid.

**Comment by patriclougheed** [comment]
I have started looking into using adLDAP2 and the first showstopper is it requires v5 of the Laravel framework. I noticed there is a branch with some changes to upgrade to v5 so will start with that and see how far I get.

**Comment by JeyDee** [comment]
Sorry for my late reply. I just changed "samaccountname" in the login-function to whatever OpenLDAP expects (i belief it was around line 730 of the LDAP related php file, if I recall correctly). No big change and its just a hack to handle the login information correctly.
