### ISSUE TITLE
How Can I Install Paperwork On Shared Hosting With Cpanel or Other Control Panel

### ISSUE THREAD

**Issue by zzpoik** [paperwork/paperwork#639]
Is there any way can allow me install it on shared Hosting?

**Comment by jamesrascal** [comment]
This is possible but you would need a pre-compiled build first.You would also need to make some changes to how the domain directs within CPanel. I will see if I can go through the process and get you some better instructions.

**Comment by zzpoik** [comment]
I'm looking forword

**Comment by trobotham** [comment]
do you have root access to the cpanel server? if so and if you run easyapache 4, this is very easy to do as ea4 includes composer and you can install npm/node via yum and install everything locally under the user.

**Comment by jsEveryDay** [comment]
Just build it yourself!

Most CPanel hosts are running CentOS 6.8
So run CentOS on a VM or on a VPS just for the build.
Then compress it, take it... and it will run on Any CentOS or other unix with the same GCC version.

The whole build process

`wget https://github.com/twostairs/paperwork/tarball/master
tar -zxvf master

cd paperwork/frontend/
Set MYSQL login frontend/app/storage/config

curl -sS https://getcomposer.org/installer | php
php composer.phar install
php artisan migrate
npm install -g gulp bower
npm install
bower install
gulp

To RUN yourdomain/paperwork/frontend/public
`

**Comment by Liongold** [comment]
@mrusme Can you make a build to help with this, please?

**Comment by mrusme** [comment]
v2 will heavily rely on containers, hence this is not relevant anymore.
