### ISSUE TITLE
RFE: Add an option to disable Calendar

### ISSUE THREAD

**Issue by strikerttd** [paperwork/paperwork#645]

**Comment by Liongold** [comment]
Why? The calendar in the sidebar can be hidden by clicking the section header. Is this enough for your use? What is the exact requirement, removing the calendar from UI only or completely? Thanks for your feedback.

**Comment by strikerttd** [comment]
Hiding the calendar every time someone logs in can be a hassle.  Our specific usage of Paperwork doesn't require us to need to search for notes by creation date either.

**Comment by Liongold** [comment]
You are free to contribute this feature to Paperwork yourself. This should not be complicated to do, especially if you have little knowledge of Laravel. You can add a config option in app/config/paperwork.php and then check for that config setting in line 59 pf app/views/main.blade.php. Are you available to do this?

**Comment by mrusme** [comment]
v2 does not have a calendar by default.
