### ISSUE TITLE
Redirect loop after setup

### ISSUE THREAD

**Issue by Sonof8Bits** [paperwork/paperwork#649]
After setting up my first account I'm stuck in a redirect loop. Chrome gives me ERR_TOO_MANY_REDIRECTS.

Any ideas what could be causing it or how to fix it?

**Comment by jamesrascal** [comment]
Can you post your Nginx Config please?

**Comment by Sonof8Bits** [comment]
Apache even. Some background info: I did the exact same thing on a Raspberry Pi, including https, a year ago and it worked perfectly. But as you can imagine a RasPi was incredibly slow to load. So now I'm trying again on a VPS. The apache config is identical to the RasPi install.

<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerAdmin webmaster@localhost
        ServerName paperwork.my.site
        DocumentRoot /var/www/paperwork.my.site/paperwork/frontend/public

        <Directory />
                Options FollowSymLinks
                AllowOverride None
        </Directory>

        <Directory /var/www/paperwork.my.site/paperwork/frontend/public/>
                Options Indexes FollowSymLinks
                AllowOverride All
                Order allow,deny
                allow from all
        </Directory>

        SSLEngine on
        SSLCertificateFile      /etc/letsencrypt/live/paperwork.my.site/cert.pem
        SSLCertificateKeyFile   /etc/letsencrypt/live/paperwork.my.site/privkey.pem
        SSLCertificateChainFile /etc/letsencrypt/live/paperwork.my.site/fullchain.pem

        ErrorLog ${APACHE_LOG_DIR}/error.log
        LogLevel warn
        CustomLog ${APACHE_LOG_DIR}/ssl_access.log combined

        <FilesMatch "\.(cgi|shtml|phtml|php)$">
                SSLOptions +StdEnvVars
        </FilesMatch>
        <Directory /usr/lib/cgi-bin>
                SSLOptions +StdEnvVars
        </Directory>
        BrowserMatch "MSIE [2-6]" \
                nokeepalive ssl-unclean-shutdown \
                downgrade-1.0 force-response-1.0
        BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown
</VirtualHost>
</IfModule>

**Comment by TiborBiro** [comment]
A quick hack that got things going for me: 

I got the same problem. The nginx error.log was showing something like Undefined index: HTTP_X_REQUESTED_WIDTH in index.php. If you check the index.php file you see a multi-line test that determines if setup.php needs to be loaded. After some fiddling I just replaced the test with (1==2) so it is always false and the redirects stopped. Do this after you already ran setup.php once.

**Comment by Sonof8Bits** [comment]
That did the trick! I commented out the check and replaced it with (1==2){.

If someone runs into the same problem, here's the entire index.php file for your copy and paste pleasure:

```
<?php

    /** Check if all config lines are present.
     * If not, either the installation is damaged
     * or installation has not been done. Run the
     * Setup Wizard.
     */

    if (1==2){
	/*(!file_exists("../app/storage/config/setup") ||
        file_get_contents("../app/storage/config/setup") == 3 && !$_SERVER['HTTP_X_REQUESTED_WITH'] ||
        file_get_contents("../app/storage/config/setup") == 4 && !$_SERVER['HTTP_X_REQUESTED_WITH'] ||
        file_get_contents("../app/storage/config/setup") == 6 && !$_SERVER['HTTP_X_REQUESTED_WITH'] ||
        file_get_contents("../app/storage/config/setup") == 5 && !$_SERVER['HTTP_X_REQUESTED_WITH'] ||
        !file_exists("../app/storage/config/paperwork.json") && !$_SERVER['HTTP_X_REQUESTED_WITH'] ||
        !file_exists("../app/storage/config/database.json") && !$_SERVER['HTTP_X_REQUESTED_WITH']) {
            header("Location: setup.php");*/
    }else{
        /**
         * Laravel - A PHP Framework For Web Artisans
         *
         * @package  Laravel
         * @author   Taylor Otwell <taylorotwell@gmail.com>
         */

        /*
        |--------------------------------------------------------------------------
        | Register The Auto Loader
        |--------------------------------------------------------------------------
        |
        | Composer provides a convenient, automatically generated class loader
        | for our application. We just need to utilize it! We'll require it
        | into the script here so that we do not have to worry about the
        | loading of any our classes "manually". Feels great to relax.
        |
        */

        require __DIR__.'/../bootstrap/autoload.php';

        /*
        |--------------------------------------------------------------------------
        | Turn On The Lights
        |--------------------------------------------------------------------------
        |
        | We need to illuminate PHP development, so let's turn on the lights.
        | This bootstraps the framework and gets it ready for use, then it
        | will load up this application so that we can run it and send
        | the responses back to the browser and delight these users.
        |
        */

        $app = require_once __DIR__.'/../bootstrap/start.php';

        /*
        |--------------------------------------------------------------------------
        | Run The Application
        |--------------------------------------------------------------------------
        |
        | Once we have the application, we can simply call the run method,
        | which will execute the request and send the response back to
        | the client's browser allowing them to enjoy the creative
        | and wonderful application we have whipped up for them.
        |
        */

        $app->run();
    }
```

**Comment by jamesrascal** [comment]
In my opinion, this is a bug that needs to be addressed. I was running through an install this morning and found the same problem.

**Comment by Liongold** [comment]
Thanks for your feedback. On what branch is this issue happening? Also, can someone of you give the version when this is happening (as found in the Settings page) please? Does this happen only when using HTTPS? A screenshot of the Network tab of the browser's Developer Tools could also help. Are any of the request failing? Last thing, at what step is the error happening? To see this, go to the storage folder on your version, config folder and give the number written in the file named setup. Sorry for the questions but these should help with identifying the problem.

**Comment by Liongold** [comment]
Also, try to not change the code. You can skip the Setup Wizard by putting 8 in the setup file I mentioned above.

**Comment by Sonof8Bits** [comment]
Master branch. Don't know if it's https only. It happens right after the setup wizard is done and you click continue to paperwork. I hope some others can supply more info.

**Comment by Sonof8Bits** [comment]
Wait, I did try http, also looped.

**Comment by Liongold** [comment]
Can someone post a screenshot of the Network tab and the Console of the Developer Tools?

**Comment by Liongold** [comment]
A pull request is open which should avoid this issue. However, this could happen due to an incorrectly done install. Please recheck that you have all files present.

**Comment by Sonof8Bits** [comment]
I redownloaded the master.zip about 3 times before @TiborBiro's hack fixed it. I don't think that's the issue for me.

**Comment by Liongold** [comment]
The one generated by Github? If yes, then that is not the way Paperwork should be installed. There's some instructions in the Wiki. Also, develop contains the latest code so fixes may get later in the master branch.

**Comment by Sonof8Bits** [comment]
I have also tried the git method, but currently I'm running the install from the github zip.

**Comment by Sonof8Bits** [comment]
If there's any way I can contribute with making a debian8 / apache page for the wiki, let me know.

**Comment by Liongold** [comment]
If you want to, you can contribute a guide.

**Comment by Liongold** [comment]
Can you confirm whether this is happening on the develop branch please?

**Comment by teward** [comment]
Just confirmed today this happens in the Master branch via a Docker setup/install.  I'll test Develop to see if this can be replicated in the Develop branch later (within the next three days, schedule permitting)
