### ISSUE TITLE
docker-compose up not working - service 'web' failed

### ISSUE THREAD

**Issue by Rukenshia** [paperwork/paperwork#655]
docker version:

> # docker version
> 
> Client:
>  Version:      1.12.0-rc4
>  API version:  1.24
>  Go version:   go1.6.2
>  Git commit:   e4a0dbc
>  Built:        Wed Jul 13 03:35:40 2016
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      1.12.0-rc4
>  API version:  1.24
>  Go version:   go1.6.2
>  Git commit:   e4a0dbc
>  Built:        Wed Jul 13 03:35:40 2016
>  OS/Arch:      linux/amd64

output of `docker-compose up`

> # docker-compose up
> 
> paperwork_db_1 is up-to-date
> Building web
> Step 1 : FROM centurylink/apache-php:latest
>  ---> 899bdaa7fba6
> Step 2 : MAINTAINER Derek Myers arcticpro@gmail.com
>  ---> Using cache
>  ---> b3dabfb8b4f6
> Step 3 : RUN apt-get update &&  DEBIAN_FRONTEND=noninteractive apt-get -y upgrade &&  DEBIAN_FRONTEND=noninteractive apt-get -y install supervisor pwgen &&  apt-get -y install mysql-client libmcrypt4 php5-mcrypt php5-json php5-curl  php5-ldap php5-cli nodejs nodejs-legacy npm git git-core
>  ---> Using cache
>  ---> ff657bb7cf67
> Step 4 : ADD ./deploy/apache.conf /etc/apache2/sites-enabled/000-default.conf
>  ---> Using cache
>  ---> 023df8552a29
> Step 5 : RUN a2enmod rewrite && php5enmod mcrypt &&     mkdir -p /app && rm -rf /var/www/html && ln -s /app/public /var/www/html
>  ---> Using cache
>  ---> 627f6ebfcb91
> Step 6 : ADD . /app
>  ---> Using cache
>  ---> a661c52b6084
> Step 7 : WORKDIR /app
>  ---> Using cache
>  ---> 8f37694747bc
> Step 8 : RUN find ./app/storage -type d -print0 | xargs -0 chmod 0755 &&     find ./app/storage -type f -print0 | xargs -0 chmod 0644 &&     composer install && npm update && npm install &&     npm install -g gulp bower && bower --allow-root install && gulp &&     chown -R www-data:www-data /app && chmod +x /app/docker-runner.sh
>  ---> Running in e1fc15fb3811
> Warning: This development build of composer is over 30 days old. It is recommended to update it by running "/usr/local/bin/composer self-update" to get the latest version.
> Loading composer repositories with package information
> Installing dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - laravel/framework v4.2.9 requires symfony/http-foundation 2.5.\* -> no matching package found.
>     - laravel/framework v4.2.8 requires symfony/http-foundation 2.5.\* -> no matching package found.
>     - laravel/framework v4.2.7 requires symfony/http-foundation 2.5.\* -> no matching package found.
>     - laravel/framework v4.2.6 requires symfony/http-foundation 2.5.\* -> no matching package found.
>     - laravel/framework v4.2.5 requires symfony/http-foundation 2.5.\* -> no matching package found.
>     - laravel/framework v4.2.4 requires symfony/http-foundation 2.5.\* -> no matching package found.
>     - laravel/framework v4.2.3 requires symfony/http-foundation 2.5.\* -> no matching package found.
>     - laravel/framework v4.2.2 requires symfony/http-foundation 2.5.\* -> no matching package found.
>     - laravel/framework v4.2.19 requires symfony/http-foundation 2.5.\* -> no matching package found.
>     - laravel/framework v4.2.18 requires symfony/http-foundation 2.5.\* -> no matching package found.
>     - laravel/framework v4.2.17 requires symfony/http-foundation 2.5.\* -> no matching package found.
>     - laravel/framework v4.2.16 requires symfony/http-foundation 2.5.\* -> no matching package found.
>     - laravel/framework v4.2.15 requires symfony/http-foundation 2.5.\* -> no matching package found.
>     - laravel/framework v4.2.14 requires symfony/http-foundation 2.5.\* -> no matching package found.
>     - laravel/framework v4.2.13 requires symfony/http-foundation 2.5.\* -> no matching package found.
>     - laravel/framework v4.2.12 requires symfony/http-foundation 2.5.\* -> no matching package found.
>     - laravel/framework v4.2.11 requires symfony/http-foundation 2.5.\* -> no matching package found.
>     - laravel/framework v4.2.10 requires symfony/http-foundation 2.5.\* -> no matching package found.
>     - laravel/framework v4.2.1 requires symfony/http-foundation 2.5.\* -> no matching package found.
>     - laravel/framework v4.2.0 requires symfony/http-foundation 2.5.\* -> no matching package found.
>     - Installation request for laravel/framework 4.2.\* -> satisfiable by laravel/framework[v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.13, v4.2.14, v4.2.15, v4.2.16, v4.2.17, v4.2.18, v4.2.19, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
> 
> Potential causes:
> - A typo in the package name
> - The package is not available in a stable-enough version according to your minimum-stability setting
>   see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.
> 
> Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.
> ERROR: Service 'web' failed to build: The command '/bin/sh -c find ./app/storage -type d -print0 | xargs -0 chmod 0755 &&     find ./app/storage -type f -print0 | xargs -0 chmod 0644 &&     composer install && npm update && npm install &&     npm install -g gulp bower && bower --allow-root install && gulp &&     chown -R www-data:www-data /app && chmod +x /app/docker-runner.sh' returned a non-zero code: 2

**Comment by mrusme** [comment]
v1 is not under active development/support any more. For v2 Docker works.
