### ISSUE TITLE
Peering / selective sharing

### ISSUE THREAD

**Issue by mrusme** [paperwork/paperwork#66]
Here's one idea I had, which could allow Paperwork users to share data with each other but still keep their data private.

Paperwork should provide some peering feature, that would allow the service to communicate with other Paperwork installations. Of course, all Paperwork installations therefor would need to be reachable by each other (fixed IP/domain name, VPN, etc.). However, the "peering" should allow admins to configure all the other installations their locally installed Paperwork should be allowed to communicate with.
## Example:

An admin configures his Paperwork installation ("A") to allow communication with "B" and "C". So do the admins of the installations on "B" and "C" configure access to "A" and the other counterpart ("B" -> "C", "C" -> "B"). For authentication a pre-shared-key could be used.

Now let's say, on installation "A" there's a user "user@aaa.co", on "B" there's a user "user@bbb.co" and on "C" there's a user "user@ccc.co". With the peering functionality, "user@aaa.co" could share a notebook with "user@bbb.co", without sharing everything else the installation of "A" contains with the installation "B". Only a single notebook, containing notes would be synced between those two installations. Every other notebook "user@aaa.com" and "user@bbb.com" would have, would securely remain within their own Paperwork installation and not available to anyone else but them.

This would allow users/companies set up their own Paperwork, store their data within their own database but still allow other people/teams/companies to work with selectively shared data from their database, without actually providing them access to their Paperwork installation or database at all! Only data that's being actively chosen would be synced across both installations.

One of the most challenging parts in this setup probably is the ID handling. On two different Paperwork setups, IDs are managed internally. Therefor, it would be impossible for notebooks to share the same ID, allowing users to "copy & paste" notebook links from their browser's address bar into the other peer's browser and open the notebook. This means, the whole URL structure needs to be refactored and use something like UUIDs, instead of actually database IDs, as it's done right now. These UUIDs could be share with the peer's database, unlike the primary, unique, auto-incrementing table key.

Another challenge is related to the users. What if on both Paperwork installations a user the same e-mail address exists? Example: What if the user "user@aaa.co" exists on both, "A" and "B"? How is this user supposed to share a notebook? Typing his own e-mail address into the "Share" dialog would not be precise enough. Also the ID issue pops up here as well, just like with the notebooks, the notes and pretty much everything else.

This task is quite a monster and would need a lot of code reworking, but in my opinion such a feature would be worth the work. Any thoughts?

**Comment by Liongold** [comment]
ID Question: Maybe a "me on install2" option?

Even though I'm not an enterprise user, I can see the large benefit that can be found by large organizations with a feature like this. I would recommend, however, that some sort of 'Shared' notebook is created  and not users having to type the note URL of the other server.

**Comment by devilx** [comment]
@Liongold 
> Maybe a "me on install2" option?

What do you mean here?

**Comment by devilx** [comment]
Thought:

With this kind of peering, it would be theoretically possible that 10 installation peer among each other. Or 20. Or 100. Now data synchronisation could get tricky, especially when it comes to transferring uploaded attachments. When Installation1 would upload a new document (120MB PowerPoint presentation – I know people doing that) to a peer-shared notebook, it would need to transmit it to each peer individually, in order for the other installations to be able to display this document to their users. Transferring 120MB from one peer to 9 others could take a while.

So why not put this feature on steroids by using a protocol that was made especially for such scenarios? [Libtorrent](http://www.libtorrent.org/) provides a full implementation of the torrent protocol, that would allow us to transfer the data to the "nearest" (or fastest, in terms of network speed) installations first and each of them would help transmitting the data to all the other installations.

So far I haven't found a PHP wrapper around libtorrent, but maybe someone here knows one we could use for this purpose?

**Comment by Liongold** [comment]
@devilx My comment was about it the problem you wrote about for users. 

I think that there could be a config switch to sync uploads and also have a limit on the size of files.

**Comment by clemlaf** [comment]
I worked on the implementation of a share function for notes and notebooks, to be found in [this branch](https://github.com/clemlaf/paperwork/tree/add-share). It implements share function on the API level for notes and notebooks. On the frontend level, only the notes can be shared, through the Edit menu. Caution, it is still work in progress, so the UI is not perfect.
Some adjustments had also had to be made for handling tags and attachments.
Also, see #369.

**Comment by Liongold** [comment]
@clemlaf Can this be closed?
