### ISSUE TITLE
Evernote import: "Undefined index: resource-attributes"

### ISSUE THREAD

**Issue by artin-phares** [paperwork/paperwork#665]
Receiving:
`The import failed. The technical error message is: Undefined index: resource-attributes.`

Source [.enex](https://github.com/twostairs/paperwork/files/435247/evernote_import_resource-attributes.enex.gz)

**Comment by andyforceno** [comment]
I'm getting this error too. I recently installed the develop branch, because of a different error I was getting.

**Comment by codejockey1** [comment]
Having the same problem here. Has anybody come across a fix for this?

**Comment by Liongold** [comment]
Can anyone of you test this change please?

In `frontend/app/lib/Paperwork/Import/EvernoteImport.php`, lines 163 and 164 (both lines), replace them with 
`$fileName = ($hasResourceAttr && $hasFileName) ? $attachment['resource-attributes']['file-name'] : uniqid(rand(), true);`. 

That could help fix this issue. Thank you.

**Comment by andyforceno** [comment]
I made the change, and then successfully imported two .enex files that I could not import before.

**Comment by Liongold** [comment]
@andyforceno Can you open a pull request with that change to the develop branch then please?

**Comment by codejockey1** [comment]
I made the change as well and had success with most of my notebooks. However, I did run into two other issues once I got past that hurdle. First, if 2 notes have the same exact title the import woudl fail with an error. I forgot to capture the exact response but it was something along the lines of a filename too long. Next, on some of my larger notebooks I was receiving a PHP out of memory issue. I was able to resolve this by adding the following line right above line 66:

ini_set('memory_limit', '-1');

**Comment by codejockey1** [comment]
Correction, that should be added at line 62

**Comment by Liongold** [comment]
@codejockey1 Can you open a pull request with the updated code, please? About the filename error please open a new issue. However, until the pull request fixing this issue is merged, it is difficult fixing another problem.

**Comment by codejockey1** [comment]
pardon the newbiness, but here's what I get when I attempt to push my branch before the PR:
$ git push origin issue-665-out-of-memory-fix
remote: Permission to twostairs/paperwork.git denied to codejockey1.
fatal: unable to access 'https://github.com/twostairs/paperwork.git/': The requested URL returned error: 403

**Comment by Liongold** [comment]
@codejockey1 Thank you for your interest. You'll need to first fork this repo using the button at the top and then push to your repo instead to origin. After that, when coming to this repo, you'll see a yellow bar informing of recently pushed branches. From there, you can open the pull requests. Please, target develop in the pull request not master. I hope this helps. If you have any other difficulties, please ask.
