### ISSUE TITLE
ckeditor: menu visible by default?

### ISSUE THREAD

**Issue by stueja** [paperwork/paperwork#668]
Hi,

is there a possibility to have ckeditor's menu open by default when creating a new note/editing a note?
Thanks,
Jan

**Comment by jonestristand** [comment]
Second this. I have tried editing the ckeditor config file but it seems to be overriden...

**Comment by Liongold** [comment]
What was the change you did? Sorry for the very late reply.

**Comment by stueja** [comment]
Ah, was this solved?

**Comment by mrusme** [comment]
@stueja Paperwork v1 is deprecated, hence this issue is not relevant any more.
