### ISSUE TITLE
Setup Wizard - step 'Register your first account': failing to provide all required fields creates user account anyway

### ISSUE THREAD

**Issue by kuc** [paperwork/paperwork#686]
In that case setup wizard is stuck on that step, because 'User account with this e-mail already exists'.

**Comment by kuc** [comment]
After complete reset of files and database, I tried setup wizard again. This time it showed "These credentials do not appear to be correct. Please check them again.".
And I still can't see welcome note after login. But it is added to database.

**Comment by Liongold** [comment]
So can this be closed then?

**Comment by kuc** [comment]
No, sorry for misleading, I removed outdated comment. Issue from the title and first comment is still present.

**Comment by Liongold** [comment]
I couldn't reproduce this issue. What fields do you leave out when this happens?

**Comment by kuc** [comment]
Only "last name" field.

**Comment by Liongold** [comment]
What version do you have? I mean, what is the code given in the Settings page of Paperwork.

**Comment by kuc** [comment]
@Liongold Latest `develop` branch at the time of submitting the issue.
