### ISSUE TITLE
Can I change text size? It's too small.

### ISSUE THREAD

**Issue by bu2zhouzhu** [paperwork/paperwork#690]
Can I change text size? It's too small for my eyes.

**Comment by kuc** [comment]
I think that rewriting `paperwork-v1-variables.less` from using pixels, as unit for font sizes, to `em`s/`rem`s/whatever-should-be-used-as-relative-size-unit-in-2016 should be first step.

**Comment by vavrecan** [comment]
The font family (Lato) is way too small - I recommend changing it to  sans-serif or arial or whatever you prefer :1:

**Comment by Liongold** [comment]
As a workaround, you can zoom in until you get the mobile site. That font should be bigger.
