### ISSUE TITLE
any plan to have a port for freeBSD / freeNAS ?

### ISSUE THREAD

**Issue by da-sti** [paperwork/paperwork#700]
everything is in the title

**Comment by Liongold** [comment]
Can you provide a little bit more info on what is needed?

**Comment by da-sti** [comment]
Hi 

there is a good explanation on how 3rd party softwares are available in freeBSD here -> https://www.freebsd.org/doc/en_US.ISO8859-1/books/handbook/ports.html
but in summary there are 2 forms : 
- packages
  - precompiled (faster to install but no options)
  - command is 'pkg install apache24'
- ports
  - has to be compiled (slower to install but gives compilation flexibility)
  - command is 'cd /etc/ports/www/apache24 && make install"

in order to have paperwork available in freeBSD with such a simple command, you need to have a "port" , there is a documentation about this process here (that's definitively still over my head) -> https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/
Here's also a search engine on what is available in the freeBSD's ports tree -> http://www.freshports.org/


why paperwork on freeBSD ?
- freebsd is still not great for desktop but on server it has been very solid for me
- freeNAS is a project with a lot of momentum and it's a great base for "self hosting" especially with the "light virtualization" framework available in freeBSD called "jail" : you can basically install anything that is available for freeBSD (i.e. nextcloud) even if it's not a freeNAS "plugin"
- I'm a beginner in unix/linux, I started with linux and immediately ran into those distributions problems, "use that distribution for that software and this distribution is better for that one", and also package were so out of date...After 6 months of using freeBSD, I found that there is a kind of separation between the system and the 3rd party applications. The ports tree is not perfect but quite up to date on a lot of applications I use.
- I don't know what represent the effort or porting an application on freeBSD but if you do the port yourself you can maintain/upgrade when you want without depending on somebody else to do it for you.

I hope this explains better why I'd like to play with paperwork freeBSD/freeNAS :)

**Comment by Liongold** [comment]
Sorry for the late reply. Paperwork should run on all OSes, including all Linux versions supported by PHP. Did you try it and it has not worked? I can't really understand what will the difference be if this port is done. If you're interested in doing it, however, please do.

**Comment by mrusme** [comment]
You will be able to run v2 [on FreeBSD using Docker](https://wiki.freebsd.org/Docker).
