### ISSUE TITLE
Feature Request: Notebooks nesting

### ISSUE THREAD

**Issue by robertocabellon** [paperwork/paperwork#708]
Do you plan to enable the functionallity to add notebooks as sub-notebook of a parent notebook?
This would be very useful for a better organization.

**Comment by Liongold** [comment]
Doesn't the Collection feature fit your needs?

**Comment by rcabellon** [comment]
Sorry, but I'm new with paperwork.
I was using it on sandstorm oasis and I don't have the option "New
collection" under "File" button.
I suppose it isn't an up-to-date version of the application.
Any way I tryed with the cloudron version and I could create a collection.
And still isn't completely what I meant.
I can create a collection of notebooks, but I would like to create
sub-collections within a collection, just like folders inside folders.
This way I cloud have more than 1 level nesting.



2016-10-24 12:06 GMT-03:00 Liongold <notifications@github.com>:

**Comment by Liongold** [comment]
There aren't any plans to do multiple sub folders. Can tags serve your purpose?

**Comment by mrusme** [comment]
This will be possible with v2.
