### ISSUE TITLE
Something went wrong while saving your note. Please try again. 

### ISSUE THREAD

**Issue by doc2git** [paperwork/paperwork#728]
When click save botton, top tips will which is orange will display. The contents is "Something went wrong while saving your note. Please try again. ".

**Comment by CatKeenAlert** [comment]
My linux distribute is fedora24, and do everything followed https://github.com/twostairs/paperwork/wiki/Installation-----CentOS-Fedora. when I save a note, this error repliy.
Is there any suggest? Thanks: )

**Comment by Liongold** [comment]
Did you install the `php-xml` package and then restarted Apache/Nginx? If this still persists, please post a screenshot of your browser's network console and the version code found in the Settings page. Thanks.

**Comment by sevmartinezjr1** [comment]
Hi,

I got the same error. I can create notebooks but unable to create notes within them. Not sure doc noticed the samething. I did install php-xml and still no luck after reboot screenshot below. Also, where in the settings area are you saying I should screencap and send? I've tried firefox, chrome and brave browsers.
![paperwork_err_write](https://cloud.githubusercontent.com/assets/28035210/25417894/93f15cc8-2a15-11e7-8aef-8ec5be49bd6d.png)

**Comment by sevmartinezjr1** [comment]
Disregard the first post pic. I think this is what you are looking for. I see an error with the developer tools.
![errors_devltools](https://cloud.githubusercontent.com/assets/28035210/25417987/4d616bda-2a16-11e7-88a1-436d6cf0d94a.png)

**Comment by sevmartinezjr1** [comment]
angular.min.js:8661 PUT http://172.30.1.66/api/v1/notebooks/00000000-0000-0000-0000-000000000000/notes/45f5b7c4-f24b-48a1-bc31-69c8f12f3073 500 (Internal Server Error)
(anonymous)	@	angular.min.js:8661
sendReq	@	angular.min.js:8455
serverRequest	@	angular.min.js:8175
wrappedCallback	@	angular.min.js:11735
(anonymous)	@	angular.min.js:11821
$eval	@	angular.min.js:12864
$digest	@	angular.min.js:12676
$apply	@	angular.min.js:12968
(anonymous)	@	angular.min.js:19307
dispatch	@	jquery.min.js:4670
elemData.handle	@	jquery.min.js:4338

**Comment by sevmartinezjr1** [comment]
Whats really strange is that it accepts attaching files to notes but does not allow editing of notes.

**Comment by Liongold** [comment]
You should screenshot the code found in the first tab page of the Settings. Do you have any output in your server error log? What is the actual response of the request please?

**Comment by sevmartinezjr1** [comment]
Hmm. This is what I see in the error logs for Nginx.
![screenshot from 2017-05-10 13-50-01](https://cloud.githubusercontent.com/assets/28035210/25913185/cc897142-3587-11e7-81e2-ed345221f46d.png)

**Comment by sevmartinezjr1** [comment]
![screenshot from 2017-05-12 08-45-03](https://cloud.githubusercontent.com/assets/28035210/25998511/5668dbce-36ef-11e7-9590-e519caba8193.png)

**Comment by Liongold** [comment]
Try to install the `php-xml` package, restart the web server and then retry it.

**Comment by sevmartinezjr1** [comment]
Thanks that did it! I thought the install was going through previously when I tried installing it but, it was erroring out because of a conflict with an installed package. Enjoying the app thanks again.

Sev

**Comment by Liongold** [comment]
@doc2git Are you still having this issue? Do any of the comments above fix it for you?

**Comment by marcbritten** [comment]
Hi, I'm getting this same error, and I don't have a code under settings  php-xml is installed

**Comment by Liongold** [comment]
@marcbritten Sorry for the late reply. Can you post a screenshot of the response to the save request? You can see this from the Network tab of the browser's Developer Tools.
