### ISSUE TITLE
Native App

### ISSUE THREAD

**Issue by LeonardoGentile** [paperwork/paperwork#729]
Hello,
any plan to build a native app client using a self hosted backed (in the same machine) or a backbend hosted somewhere else in the internet?
I'm mostly asking for OsX but I guess adopting Electron or similar this can be built once and distributed across different architecture.

**Comment by kuc** [comment]
Related: #345

**Comment by mrusme** [comment]
This question was directed towards v1. However, this is relevant for v2 as well. Answer: The [web](https://github.com/paperwork/web) UI v2 is going to use will be put inside an Electron container and shipped as *native* app for Linux, Mac and Windows.
