### ISSUE TITLE
Running paperwork in subfolder

### ISSUE THREAD

**Issue by c1xx** [paperwork/paperwork#733]
Hi,

I followd this instructions: https://github.com/twostairs/paperwork/wiki/Running-paperwork-in-subfolder

I see only a blank page, when I open the URL. 

I'm using Ubuntu 16.10 with Nginx 1.9.15

My Configuration file is:

> server {
>   listen 4435 ssl;
>   server_name XXXXX.ddns.net;
>   autoindex off;
>   disable_symlinks off;
>   
>   ssl_certificate /etc/letsencrypt/live/XXXXX.ddns.net/fullchain.pem;
>   ssl_certificate_key /etc/letsencrypt/live/XXXXX.ddns.net/privkey.pem;
>   ssl_trusted_certificate /etc/letsencrypt/live/XXXXX.ddns.net/chain.pem;
>   
>   root /var/www/html;
>   index index.html index.htm index.php;
>   
>   location / {
>     autoindex off;
>     try_files $uri $uri/ =404;
>   }
>   
>   location ~ \.php$ {
>     include snippets/fastcgi-php.conf;
>     fastcgi_pass unix:/run/php/php7.0-fpm.sock;
>   }
> 
>   location ^~ /apps/paperwork {
>     alias /var/www/html/paperwork/frontend/public/;
> 
>     try_files $uri $uri/ @paperwork;
> 
>     location ~* \.php {
>             fastcgi_pass unix:/run/php/php7.0-fpm.sock;
>             fastcgi_split_path_info ^(.+\.php)(.*)$;
>             include fastcgi_params;
>     }
>   }
> 
>   location @paperwork {
>     rewrite ^/apps/paperwork/(.*)$ /apps/paperwork/index.php/$1 last;
>   }
> }

What's wrong?

Thank you,
Lukas

**Comment by Liongold** [comment]
Do you have any output in your error log files?

**Comment by Liongold** [comment]
Any update here?

**Comment by Alexandero89** [comment]
I have the same problem with nearly the same nginx-config.
Here part of my config:
```
location ^~ /notizen {
                alias /var/www/paperwork/frontend/public;
                try_files $uri $uri/ @paperwork;

                location ~* \.php {
                        fastcgi_pass unix:/var/run/php5-fpm.sock;
                        fastcgi_split_path_info ^(.+\.php)(.*)$;
                        include fastcgi_params;
                }
        }

```
Please note that my location is "/notizen" instead of "/apps/paperwork".
So i changed the rewrite to:
```
        location @paperwork {
                rewrite ^/notizen/(.*)$ /index.php/$1 last;
        }
```
And my directory looks like this:
/var/www/paperwork/....

My Log looks a bit strange because allthough he finds the index.php he rewrites the location to "notizen/index.php" again:

https://pastebin.com/YiTAp46u

**Comment by Alexandero89** [comment]
Posted my problem also to StackOverFlow and they found a solution
[https://stackoverflow.com/questions/43966556/using-nginx-with-nextcloud-website-paperwork-parallel](url)

Here is the working configuration:

     location ^~ /notizen {
       alias /var/www/paperwork/frontend/public;
       index index.php index.html index.htm;

       if (!-e $request_filename) { rewrite ^ /notizen/index.php last; }

      location ~ \.php$ {
        if (!-f $request_filename) { return 404; }

        fastcgi_pass unix:/var/run/php5-fpm.sock;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $request_filename;
      }
    }

**Comment by Liongold** [comment]
Sorry I'm not familiar with Nginx. Do you think your new configuration should work in all cases. If so, could you update the Wiki page with that new configuration.
