### ISSUE TITLE
Can't connect to localhost

### ISSUE THREAD

**Issue by MalcolmMielle** [paperwork/paperwork#741]
Hello all,

Sorry for the simple question but I am really new to all this :/. I did the whole install on fedora25 and it worked flawlessly. However when trying to access localhost:8888/login I have `Unable to connect`. I've done the whole install process under ssh from a remote computer. Do you have any idea why I can't seem to access paperwork ?

Thanks !
Best,

**Comment by Liongold** [comment]
Are apache2 or nginx active? Also, are you sure that 8888 is the correct port number?

**Comment by MalcolmMielle** [comment]
Well I think they should be but I don't know how to check it out. 8888 was the port in the tutorial so that's why I tried it, how can I know the port to use?

Also I tried to reinstall it but when I try to restart php-fpm I get:
```
Job for php-fpm.service failed because the control process exited with error code.
See "systemctl status php-fpm.service" and "journalctl -xe" for details.
```
And I have 
```
[paperwork@bob frontend]$ systemctl status php-fpm.service
● php-fpm.service - The PHP FastCGI Process Manager
   Loaded: loaded (/usr/lib/systemd/system/php-fpm.service; disabled; vendor preset: disabled
   Active: failed (Result: exit-code) since Wed 2017-01-04 15:11:47 CET; 16s ago
  Process: 16043 ExecStart=/usr/sbin/php-fpm --nodaemonize (code=exited, status=78)
 Main PID: 16043 (code=exited, status=78)
```
I have no idea what is going on :S

I'm so sorry for all the question and being a real noob. Thanks a lot !

**Comment by Liongold** [comment]
Unfortunately, I don't know how Nginx works so help from my side might be limited. Did you use this article https://github.com/twostairs/paperwork/wiki/Installation-----CentOS-Fedora? It does not mention 8888 but 80 as port (I think). Try to check whether some ports are blocked by your service provider. Please reply with your results.

**Comment by MalcolmMielle** [comment]
I followed exactly this article. When I try to connect to `localhost:80/login` I have a `502 bad gateway` error.

**Comment by Liongold** [comment]
this article -> https://github.com/twostairs/paperwork/wiki/Installation-----CentOS-Fedora?

This page (http://askubuntu.com/questions/367409/nginx-unable-to-connect) seems to be similar to your problem. Can you check it out? Once you set the port change it in the paperwork-wiki code as well. I hope it works.

**Comment by MalcolmMielle** [comment]
Yes this article :)

I check out the link you sent me and this is what `netstat` is returning:

```
netstat -antp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      1696/cupsd          
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      1/systemd           
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      3989/nginx: master  
tcp        0      0 192.168.122.1:53        0.0.0.0:*               LISTEN      1077/dnsmasq        
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      2336/sshd           
tcp        0   1085 130.243.124.134:22      218.65.30.61:1557       ESTABLISHED -                   
tcp        0    196 130.243.124.134:22      10.22.2.205:50632       ESTABLISHED 3795/sshd: paperwor 
tcp        0      0 130.243.124.134:22      218.87.109.150:61039    ESTABLISHED 4059/sshd: root [pr 
tcp6       0      0 ::1:631                 :::*                    LISTEN      1696/cupsd          
tcp6       0      0 :::3306                 :::*                    LISTEN      975/mysqld          
tcp6       0      0 :::111                  :::*                    LISTEN      1/systemd           
tcp6       0      0 :::22                   :::*                    LISTEN      2336/sshd           
```

So it seems that nginx is running on the good port. I'm trying this on local so do I need to check if the port are blocked ?

For the sake of trying, I changed the port to 8080 and I still have the same result when trying to connect. The good page is really `localhost:8080/login` on firefox right :| ?

**Comment by Liongold** [comment]
Yes, you should check whether the port is blocked. So 0.0.0.0:80/login still does not work? Do you have anything in the error log of nginx and php?

**Comment by MalcolmMielle** [comment]
The file `/var/log/nginx/error.log` is empty

The file `/var/log/php-fpm/error.log`:

```
[15-Jan-2017 03:11:01] NOTICE: error log file re-opened
```

The old error files had the old error of the previous messages that I solved now.

`/var/log/php-fpm/error.log-20170115`:

```
[05-Jan-2017 13:09:56] NOTICE: fpm is running, pid 3536
[05-Jan-2017 13:09:56] NOTICE: ready to handle connections
[05-Jan-2017 13:09:56] NOTICE: systemd monitor interval set to 10000ms
[05-Jan-2017 13:45:28] NOTICE: Terminating ...
[05-Jan-2017 13:45:28] NOTICE: exiting, bye-bye!
[05-Jan-2017 15:28:07] ERROR: [pool www] the prefix '/path/to/pools/www' does not exist or is not a directory
[05-Jan-2017 15:28:07] ERROR: failed to post process the configuration
[05-Jan-2017 15:28:07] ERROR: FPM initialization failed
[05-Jan-2017 15:28:36] NOTICE: configuration file /etc/php-fpm.conf test is successful

[05-Jan-2017 15:29:05] NOTICE: configuration file /etc/php-fpm.conf test is successful

[05-Jan-2017 15:29:12] ERROR: [pool www] cannot get uid for user 'nginx # SOCKS permission': Success (0)
[05-Jan-2017 15:29:12] ERROR: FPM initialization failed
[05-Jan-2017 15:29:44] ERROR: [pool www] cannot get uid for user 'nginx # SOCKS permission': Success (0)
[05-Jan-2017 15:29:44] ERROR: FPM initialization failed
[05-Jan-2017 15:32:31] ERROR: [pool www] cannot get uid for user 'nginx # SOCKS permission': Success (0)
[05-Jan-2017 15:32:31] ERROR: FPM initialization failed
[05-Jan-2017 15:37:27] ERROR: [pool www] cannot get uid for user 'nginx # SOCKS permission': Success (0)
[05-Jan-2017 15:37:27] ERROR: FPM initialization failed
[05-Jan-2017 15:41:00] NOTICE: fpm is running, pid 7110
[05-Jan-2017 15:41:00] NOTICE: ready to handle connections
[05-Jan-2017 15:41:00] NOTICE: systemd monitor interval set to 10000ms
[10-Jan-2017 10:17:05] NOTICE: fpm is running, pid 805
[10-Jan-2017 10:17:05] NOTICE: ready to handle connections
[10-Jan-2017 10:17:05] NOTICE: systemd monitor interval set to 10000ms
```

**Comment by Liongold** [comment]
Is the problem limited to Paperwork? Or better, can you put something else and try to access it (for example a simple HTML page??

**Comment by Liongold** [comment]
@JamborJan By any chance, do you use Nginx? Maybe you could help here?

**Comment by MalcolmMielle** [comment]
I'm going to try that, if I find a tutorial on how to do it. And I'm using Nginx. At least I'm trying to :).

I wanted to say thank you for taking the time to help me out with this because I'm pretty sure that the problem is only here because I'm such a noob at this :|

**Comment by JamborJan** [comment]
Hey ho, yes I'm using nginx. No need the be sorry @MalcolmMielle :-) 

The explained issue seems to be strange. Is there maybe an issue with the setup? I'm running Paperwork in my [Sandstorm](https://github.com/sandstorm-io/sandstorm) with this setup:
- Debian (but you should be able to use any distro)
- Packages and Config like explained here: https://github.com/JamborJan/paperwork/blob/master/.sandstorm/setup.sh
- Don't do that: https://github.com/JamborJan/paperwork/blob/master/.sandstorm/setup.sh#L15-L20
- Nginx config: https://github.com/JamborJan/paperwork/tree/master/.sandstorm/service-config

Maybe you can compare your setup against this? Especially the required packages and settings?

If you don't succeed please don't hesitate to ask again. We are all new to everything at one point in time :-)

Cheers

**Comment by Liongold** [comment]
@MalcolmMielle Did you manage to do this? Can the issue be closed?

**Comment by MalcolmMielle** [comment]
Hey! Sorry I haven't time to actually try any of what was proposed before :S. Work kept pilling up and I never could go back to this.

**Comment by sevmartinezjr1** [comment]
What happens when you go directly to the address? Also, I had some problems too make test with selinux in permissive mode I know fed and cent like to have them on by default.
Sev,
