### ISSUE TITLE
Could you please reduce the size of api api/vi/notebooks/xxx/notes for better performance?

### ISSUE THREAD

**Issue by furick** [paperwork/paperwork#746]
I build my paperwork and have added 60 documents. Currently the opening speed is too slow. I check the network status and find that it has three same  xhr request (api/vi/notebooks/xxx/notes) which size is 2.9MB, see figure below:
![67d7a530-ebe4-11e6-960a-972a4adb9f76](https://cloud.githubusercontent.com/assets/15622745/22687309/675ab186-ed62-11e6-9f7f-97419d84c09d.png)

I checked the code of this api. I thought it should be loading notes' list for a notebook user selected. The response is so large because it contains every note's content. 
![image](https://cloud.githubusercontent.com/assets/15622745/22687595/af2a9836-ed63-11e6-8af0-d712b79801a8.png)

I wonder why this api is called 3 times and contains every note's full content. I thought it just for notes list which needn't full content. Could you please remove the content key for this api's response and reduce the calling times of it?

**Comment by idreamerhx** [comment]
I have 1700+ notes which is converted from youdao note.  (php memory limit to 256MB works)  In paperwork "All notes" takes a long time to dump the whole database. I suggest this api can only return titles and preview.

**Comment by mrusme** [comment]
It was reduced in v2. Please refer to the [service-notes](https://github.com/paperwork/service-notes) repo for this.
