### ISSUE TITLE
Question about "php artisan migrate" command

### ISSUE THREAD

**Issue by romu70** [paperwork/paperwork#749]
Hello,
I'm working on a Paperwork Docker image. My image will store data in an external MariaDB instance. I've written My Dockerfile and I've a question about the ```php artisan migrate``` command.

Indeed, I've tried both cases, with and without that command, and result is same, Paperwork seems to work as expected. So, could you please tell me a bit more about this command, its purpose, etc, and confirm if it's a necessary step or not.

Thanks. 

For some who may be interested, my Docker setup is here: https://github.com/romu70/self-hosting-containers/tree/master/paperwork.

**Comment by Liongold** [comment]
It should be necessary, yes. The `php artisan migrate` command generates the database tables required to store the Paperwork data. I don't know how Docker works exactly so could be missing something. Are you building the database using some other way?

**Comment by romu70** [comment]
Hi, thanks. I may be wrong but I think I've tried with a blank DB and it worked, but I'll do my testing again to be sure.

**Comment by Liongold** [comment]
@romu70 Any updates?

**Comment by romu70** [comment]
No, sorry. Didn't had the time to investigate, and don't know when I will have some.
