### ISSUE TITLE
Hide admin area when ldap is used

### ISSUE THREAD

**Issue by nebulade** [paperwork/paperwork#752]
Would it make sense to hide the admin area, or more specifically the Users view (which from what I can tell is the only thing in the admin area), in case LDAP is used? Is there any benefit in having that view, as I assume deleting a user there cannot have any effect on the LDAP server.

**Comment by Liongold** [comment]
I'm not sure since I haven't tested it but it seems that using the Delete button, removes the user from the Paperwork database regardless of whether he is logged in LDAP or not. Have you tested it and found it works otherwise?
