### ISSUE TITLE
uploading attachments increasingly fails

### ISSUE THREAD

**Issue by JamborJan** [paperwork/paperwork#782]
I have encountered an issue due to a request in the sandstorm port of Paperwork. This is not limited to the Sandstorm port. It is also happening on the cloudron instance and I guess also others.

You can create a new note and add the first attachment without a problem. When you add the next attachment it fails. With the safari browser I'm not able to add further attachments at all. The cromium based brave browser keeps openeing the upload dialogue again and again until the upload is succesfull. Funny: it seems to be always one time more than the number of already attached files. See gif below. After the third upload it stops working. The upload dialogue opens 5 times.

![untitled](https://cloud.githubusercontent.com/assets/7508960/24295459/18b2efba-109b-11e7-872d-e64fa0425f55.gif)

What exactly happens is not clear to me. When I click the green upload button the first time, I get the following error in the browsers console:

```
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (attachments, line 0)
```

**Comment by loveshizuka** [comment]
yea, I have encountered the same issue. You may select all files you want to upload at first and click the "Upload" botton at last.

**Comment by Liongold** [comment]
@JamborJan Did you test Firefox?

**Comment by JamborJan** [comment]
@Liongold I didn't test firefox. Maybe one of the users did but not sure.

**Comment by mrusme** [comment]
This issue was related to v1. Uploads in v2 will work differently, hence closing this for now.
