### ISSUE TITLE
Where is the doc for NASes?

### ISSUE THREAD

**Issue by Xaelias** [paperwork/paperwork#783]
For a system that boasts that it can run "also on small to mid-size NAS devices (Synology ®, QNAP ®, etc.)". I have to admit I was expecting the doc/wiki to mention them and have a tutorial on how to set this whole thing up on a NAS. At the very least some generic steps...
Too bad :/

**Comment by kuc** [comment]
https://nas-hosting.net/blog/2015/05/22/hosting-a-website-with-synology

**Comment by Liongold** [comment]
@Xaelias Did that article help you in installing Paperwork?

**Comment by Xaelias** [comment]
I have been neck deep in some other things. I haven't had the chance to take a look. Sorry.

**Comment by Liongold** [comment]
@Xaelias Any updates?

**Comment by mrusme** [comment]
As long as your NAS supports Docker, v2 will run on it.
