### ISSUE TITLE
Hi, can you release a precompiled version?

### ISSUE THREAD

**Issue by somas95** [paperwork/paperwork#787]
I want to run this in a standard shared host, and the last prebuilt release was in 2015. Thanks!

**Comment by jolinux** [comment]
Hello, have problems run a git-version of paperwork.

Found your prebuilt-version but no info to install.

Can you explain about install this prebuild ?

Apache or nginx Server ? DB install and migration ?

Install dir   /var/www/html/paperwork ?

Login path   ?


My install is with define/change docroot at /var/www/paperwork/frontend/public/ 
in nginx config.

login at  http://192.168.1.101/login  (virtualbox-server)   http-error 500 !


thanks

**Comment by Liongold** [comment]
@mrusme @JamborJan Can someone of you generate a pre-built version please?

**Comment by JamborJan** [comment]
Hey @Liongold, I can only build Paperwork packages for [Sandstorm](https://github.com/sandstorm-io/sandstorm). 

@mrusme I guess thats a task for you, or am I wrong?

**Comment by mrusme** [comment]
With v2 one-click-deployments via Docker are/will continue to be possible. Due to the complexity of the setup a "prebuilt binary" is not that easily possible, though. However, v2 will improve on the installation part in order to make it more easy to set up.
