### ISSUE TITLE
Note sharing pull-down options are visible only for first created account

### ISSUE THREAD

**Issue by zMietek** [paperwork/paperwork#802]
Hi,
 I have troubles with sharing function.
Only user, which was created during initial installation, can see all notes sharing options (Do not share / Read only / Read and write). Pulldown menu has partucalry antries.

If the user which is created  later, even with admin privs,tried to share a note, he can't see any sharing option, this pull-down menu is empty, without any text, just three empty places. The sharing option itself is working fine, even without text in pull-down menu ... but this blind-choose is really annoying.
![paperwork_first_user_sharing](https://cloud.githubusercontent.com/assets/28906749/26377830/4470dcc4-4012-11e7-987a-c7e7730b41bb.png)
![paperwork_next_user_sharing](https://cloud.githubusercontent.com/assets/28906749/26377850/5af64718-4012-11e7-9520-a5a6d9fa5d7f.jpg)

**Comment by Liongold** [comment]
What is the code mentioned in the About tab of the Settings page?

**Comment by Liongold** [comment]
Sorry for the late reply. Which browser are you using? Do you have any console output when opening the dialog? Is the user you're testing with the owner of the note?

**Comment by Liongold** [comment]
To try and fix this issue, I've created a test branch that includes more console output intended to gather information about the bug. If it's not a problem for you, could you please try checking if the bug exists in that branch? You can switch to it by doing `git checkout issue-80 and then `gulp`. If you do it, please post the whole browser console log, please.

**Comment by zMietek** [comment]
Hi,

"late reply" is no problem for me, especially in non-profit and volunteer-based software area :) So, no need to say "sorry" for reaction, if even this was indeed late ... everybody has own life, own families, job and something extraordinary things like holidays ;)

Unfortunately I'm moving my flat now. At this moment my whole IT-related infrastructure (incl. self-hosted server with paperwork installation) is offline and "scattered" in approx. 190+ removal boxes ==> I suppose, that in next 7 days I'm not able to check anything :( ... But after my life is back to the normal level, then I'll try your branch (thank you for the commands ... github is still new experience for me)

You have some questions ... let try to answer it:
1. I was using Edge, Internet Explorer 11 and Firefox 53 (Win 10), Firefox 53 and Midora (Fedora, repositories) ... everywhere the same effects observed
2. No, I haven't any console output.
3. Yes, the user was owner/creator of note.

**Comment by zMietek** [comment]
Hi,

sorry for late answer, moving flat can be very stressed experience, but after all "advantures" I'm online again.

I tried your branch (issue-802-information), now the code in Settings/About shows following information: a255e88ed621186b5f312ef5433e03e8effacea7

But I can't see any additional log files ... can you tell me, where you're expecting this "console log" which I should to post?

**Comment by Liongold** [comment]
@zMietek In the Browser's Developer Tools console.

**Comment by zMietek** [comment]
I didn't found the possibility of saving console output, so I marked all and just copied all output. The resullt is not satysfying me. I tried to get output in english, but browser wanted to produce all output only only in german language ,.. sorry for it:
(what I did? not too much, logged in as not first created user, starting browser developer console and tried to share one note)


>22:53:00.519 DOM-Neuberechnung: 5.02ms Funktion fix, jquery.min.js Zeile 4763
22:53:00.554 DOM-Neuberechnung: 0.38ms Funktion <anonym>, angular.min.js Zeile 24050
22:53:00.525 GET 
XHR 
https://paperwork.xxxx.de/api/v1/notebooks/98861b66-d5ff-4f31-84d2-ef4cc82acbc6/notes [HTTP/1.1 200 OK 75ms]
Kopfzeilen
Antwort
Cookies
Aufrufliste
Cache-Controlno-cacheConnectionKeep-AliveContent-Length2001Content-Typeapplication/jsonDateMon, 10 Jul 2017 20:52:59 GMTKeep-Alivetimeout=15, max=100ServerApacheSet-Cookielaravel_session=eyJpdiI6Imh2endcL2RrOFBuYjFXdUE2b0t2bHVRPT0iLCJ2YWx1ZSI6ImVHUGt5TXUxRXNBclRnWm1TTGpmUHYwd1wvdDJibkFmb3BhTjYrTFRRNVhlRlNBT0tUNE1UZWlCVTRMSndHVFlEajNxQ3NTTlNPS29YUTQ4V2crSDgxQT09IiwibWFjIjoiODRkNGVjMDViODAyOGUwYjRkZjcxYmVlYWY4MjJhYTQxMjdhNDI1ZmQ4NjUzNDE0ZDliYWFhYmU3ODA0NmM1ZCJ9; expires=Mon, 10-Jul-2017 22:52:59 GMT; Max-Age=7200; path=/; HttpOnly;HttpOnly;Secure;HttpOnly;SecureStrict-Transport-Securitymax-age=15768000; includeSubDomains; preloadX-Frame-OptionsSAMEORIGIN
Acceptapplication/json, text/plain, */*Accept-Encodinggzip, deflate, brAccept-Languageen,en-US;q=0.7,de;q=0.3Connectionkeep-aliveCookielaravel_session=eyJpdiI6Ik90T0J5dmJrS2lzdVBTelhaM0xUY1E9PSIsInZhbHVlIjoiUk8yWXRUd3c1NHhGOUVyUVBPbEJMMFlaaERyek5rVXpqS1UyNVBEb1Q0eXRUUmFNSFFXNG11N2g3VXJxQ2hmaUhcL2VUNmZGa2U5UmNlMG1jZkxOK0xBPT0iLCJtYWMiOiI3MzFjMmRiYzcwZDRmYWRhYTI2NWFjMDI0ZGJhYmY2ZDIyOTBhOWQ5YWI2ZGZkOWM1ZmYwODdhMzA2YThiYmQyIn0%3DDNT1Hostpaperwork.xxxx.deRefererhttps://paperwork.xxxx.de/User-AgentMozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36X-Requested-WithXMLHttpRequest

>22:53:00.525 GET 
XHR 
https://paperwork.xxxx.de/api/v1/notebooks/98861b66-d5ff-4f31-84d2-ef4cc82acbc6/notes/59beb962-2b0f-4fef-b4b3-806489429f1a/versions/00000000-0000-0000-0000-000000000000/attachments [HTTP/1.1 200 OK 26ms]
Kopfzeilen
Antwort
Cookies
Aufrufliste
Cache-Controlno-cacheConnectionKeep-AliveContent-Length30Content-Typeapplication/jsonDateMon, 10 Jul 2017 20:52:59 GMTKeep-Alivetimeout=15, max=100ServerApacheSet-Cookielaravel_session=eyJpdiI6Im9INnRpSGpwMW5vbjZENnZDWWVicFE9PSIsInZhbHVlIjoiRUloVWFMUitSUUpPTG84UzA4YTQ5OXJYbVwvbmttdXJ3ZDV5cVwvaDc0QXJYWlhlNk84a05Cakdld1ZMdU5pYzA2aHRscU5QUnZ3Q0VXZ3RVU3FXUVlpUT09IiwibWFjIjoiNzhkZDA0N2RkOTEyNTc0M2UyOGE3ZTJjMTc3NzlhYTk1NzBiYWMxNDBlNmViODc0ZjhiZDM4NTM4ZWY3MTViYyJ9; expires=Mon, 10-Jul-2017 22:52:59 GMT; Max-Age=7200; path=/; HttpOnly;HttpOnly;Secure;HttpOnly;SecureStrict-Transport-Securitymax-age=15768000; includeSubDomains; preloadX-Frame-OptionsSAMEORIGIN
Acceptapplication/json, text/plain, */*Accept-Encodinggzip, deflate, brAccept-Languageen,en-US;q=0.7,de;q=0.3Connectionkeep-aliveCookielaravel_session=eyJpdiI6Ik90T0J5dmJrS2lzdVBTelhaM0xUY1E9PSIsInZhbHVlIjoiUk8yWXRUd3c1NHhGOUVyUVBPbEJMMFlaaERyek5rVXpqS1UyNVBEb1Q0eXRUUmFNSFFXNG11N2g3VXJxQ2hmaUhcL2VUNmZGa2U5UmNlMG1jZkxOK0xBPT0iLCJtYWMiOiI3MzFjMmRiYzcwZDRmYWRhYTI2NWFjMDI0ZGJhYmY2ZDIyOTBhOWQ5YWI2ZGZkOWM1ZmYwODdhMzA2YThiYmQyIn0%3DDNT1Hostpaperwork.xxxx.deRefererhttps://paperwork.xxxx.de/User-AgentMozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36X-Requested-WithXMLHttpRequest

>22:53:00.525 GET 
XHR 
https://paperwork.xxxx.de/api/v1/notebooks/00000000-0000-0000-0000-000000000000/notes/59beb962-2b0f-4fef-b4b3-806489429f1a [HTTP/1.1 200 OK 29ms]
Kopfzeilen
Antwort
Cookies
Aufrufliste
Cache-Controlno-cacheConnectionKeep-AliveContent-Length2793Content-Typeapplication/jsonDateMon, 10 Jul 2017 20:52:59 GMTKeep-Alivetimeout=15, max=100ServerApacheSet-Cookielaravel_session=eyJpdiI6IlNYWXNGdnRXWWRINnpraU1SR1FwOWc9PSIsInZhbHVlIjoiVU9aWHpKT0xaVTMwNTJwWDBqQzJFcUcwcThYUXJ0eTVKQlN3VEc0bHFpZkNOZkhuTkl0QTIwYzF4d0RTMEJRREJUTUloNzllNFE4cU1mUmRaWk50cGc9PSIsIm1hYyI6IjJlNjhmNTFiODg0OTBlYTZmZTIzNWJhNTQyNDUwMDEwNDgyODhiYTE0YzRjOWQwNjEyNWE0ZTk2Mzg3YzAyMjUifQ%3D%3D; expires=Mon, 10-Jul-2017 22:52:59 GMT; Max-Age=7200; path=/; HttpOnly;HttpOnly;Secure;HttpOnly;SecureStrict-Transport-Securitymax-age=15768000; includeSubDomains; preloadX-Frame-OptionsSAMEORIGIN
Acceptapplication/json, text/plain, */*Accept-Encodinggzip, deflate, brAccept-Languageen,en-US;q=0.7,de;q=0.3Connectionkeep-aliveCookielaravel_session=eyJpdiI6Ik90T0J5dmJrS2lzdVBTelhaM0xUY1E9PSIsInZhbHVlIjoiUk8yWXRUd3c1NHhGOUVyUVBPbEJMMFlaaERyek5rVXpqS1UyNVBEb1Q0eXRUUmFNSFFXNG11N2g3VXJxQ2hmaUhcL2VUNmZGa2U5UmNlMG1jZkxOK0xBPT0iLCJtYWMiOiI3MzFjMmRiYzcwZDRmYWRhYTI2NWFjMDI0ZGJhYmY2ZDIyOTBhOWQ5YWI2ZGZkOWM1ZmYwODdhMzA2YThiYmQyIn0%3DDNT1Hostpaperwork.xxxx.deRefererhttps://paperwork.xxxx.de/User-AgentMozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36X-Requested-WithXMLHttpRequest

>22:53:00.883 DOM-Neuberechnung: 0.24ms Funktion <anonym>, angular.min.js Zeile 24050
>22:53:00.884 DOM-Neuberechnung: 0.38ms Funktion <anonym>, angular.min.js Zeile 24050
>22:53:00.884 DOM-Neuberechnung: 1.04ms Funktion <anonym>, angular.min.js Zeile 24050
>22:53:00.915 DOM-Neuberechnung: 0.28ms
>22:53:00.915 DOM-Neuberechnung: 0.29ms
>22:53:00.916 DOM-Neuberechnung: 0.26ms
>22:53:00.965 DOM-Neuberechnung: 0.26ms
>22:53:00.965 DOM-Neuberechnung: 0.26ms
>22:53:00.966 DOM-Neuberechnung: 0.3ms
>22:53:01.013 DOM-Neuberechnung: 0.3ms
>22:53:01.013 DOM-Neuberechnung: 0.29ms
>22:53:01.014 DOM-Neuberechnung: 0.31ms
>22:53:01.062 DOM-Neuberechnung: 0.29ms
>22:53:01.063 DOM-Neuberechnung: 0.34ms
>22:53:01.063 DOM-Neuberechnung: 0.29ms
>22:53:01.111 DOM-Neuberechnung: 0.3ms
>22:53:01.112 DOM-Neuberechnung: 0.28ms
>22:53:01.112 DOM-Neuberechnung: 0.28ms
>22:53:01.164 DOM-Neuberechnung: 0.3ms
>22:53:01.164 DOM-Neuberechnung: 0.26ms
>22:53:01.165 DOM-Neuberechnung: 0.31ms
>22:53:01.200 DOM-Neuberechnung: 0.28ms
>22:53:01.200 DOM-Neuberechnung: 0.26ms
>22:53:01.736 DOM-Neuberechnung: 0.42ms
>22:53:38.980 object  paperwork.min.js:1980:9
>22:53:39.009 GET 
>XHR 
>https://paperwork.xxxx.de/api/v1/users/59beb962-2b0f-4fef-b4b3-806489429f1a [HTTP/1.1 200 OK 84ms]
Kopfzeilen
Antwort
Cookies
Aufrufliste
Cache-Controlno-cacheConnectionKeep-AliveContent-Length1158Content-Typeapplication/jsonDateMon, 10 Jul 2017 20:53:38 GMTKeep-Alivetimeout=15, max=100ServerApacheSet-Cookielaravel_session=eyJpdiI6IkFMcG5LMjc5TUhwdGptdXdibkRqbXc9PSIsInZhbHVlIjoiaVRnKzBIME92NzZ3ZlBBVWRoUzljd1wvWUdlcU43aTV4dFBBYUxaMHg0dTRVOHlOUlQyS2hwbENpWjExRVRHcjRkNmxpd1BESnJqaWcrTkFnb1FVaitnPT0iLCJtYWMiOiJkMjZmYjgzMjRlMzEzNDc2ZDk2MGExYWFjM2ZhMTY3YjI5MmI3MThhZGUwYWE2NmVlN2JiMDhjYjNjZTY4MmFkIn0%3D; expires=Mon, 10-Jul-2017 22:53:38 GMT; Max-Age=7200; path=/; HttpOnly;HttpOnly;Secure;HttpOnly;SecureStrict-Transport-Securitymax-age=15768000; includeSubDomains; preloadX-Frame-OptionsSAMEORIGIN
Acceptapplication/json, text/plain, */*Accept-Encodinggzip, deflate, brAccept-Languageen,en-US;q=0.7,de;q=0.3Connectionkeep-aliveCookielaravel_session=eyJpdiI6Imh2endcL2RrOFBuYjFXdUE2b0t2bHVRPT0iLCJ2YWx1ZSI6ImVHUGt5TXUxRXNBclRnWm1TTGpmUHYwd1wvdDJibkFmb3BhTjYrTFRRNVhlRlNBT0tUNE1UZWlCVTRMSndHVFlEajNxQ3NTTlNPS29YUTQ4V2crSDgxQT09IiwibWFjIjoiODRkNGVjMDViODAyOGUwYjRkZjcxYmVlYWY4MjJhYTQxMjdhNDI1ZmQ4NjUzNDE0ZDliYWFhYmU3ODA0NmM1ZCJ9DNT1Hostpaperwork.xxxx.deRefererhttps://paperwork.xxxx.de/User-AgentMozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36X-Requested-WithXMLHttpRequest

>22:53:39.350 DOM-Neuberechnung: 0.38ms Funktion nodeHasSize, inspector.js Zeile 3112
>22:53:39.155 false  paperwork.min.js:1989:13
>22:53:39.155 false  paperwork.min.js:1990:13
>22:53:39.156 false  paperwork.min.js:1989:13
>22:53:39.156 false  paperwork.min.js:1990:13
>22:53:39.156 true  paperwork.min.js:1989:13
>22:53:39.157 true  paperwork.min.js:1990:13
<22:53:39.157 false  paperwork.min.js:1989:13
>22:53:39.157 false  paperwork.min.js:1990:13
>22:53:39.157 true  paperwork.min.js:2258:9
>22:53:39.158 59beb962-2b0f-4fef-b4b3-806489429f1a  paperwork.min.js:2272:9
>22:53:39.159 Object { notebookId: "98861b66-d5ff-4f31-84d2-ef4cc82acbc6", noteId: "59beb962-2b0f-4fef-b4b3-806489429f1a", theCallback: theCallback() }  paperwork.min.js:188:7
>22:53:39.434 DOM-Neuberechnung: 0.31ms Funktion Modal.prototype.checkScrollbar, bootstrap.min.js Zeile 1181
>22:53:39.435 DOM-Neuberechnung: 0.13ms Funktion Modal.prototype.measureScrollbar, bootstrap.min.js Zeile 1199
>22:53:39.436 DOM-Neuberechnung: 0.27ms Funktion Modal.prototype.measureScrollbar, bootstrap.min.js Zeile 1199
>22:53:39.436 DOM-Neuberechnung: 0.31ms Funktion curCSS, jquery.min.js Zeile 6164
>22:53:39.436 DOM-Neuberechnung: 0.52ms Funktion Modal.prototype.backdrop, bootstrap.min.js Zeile 1123
>22:53:39.437 DOM-Neuberechnung: 0.76ms Funktion Modal.prototype.backdrop, bootstrap.min.js Zeile 1123
>22:53:39.437 DOM-Neuberechnung: 4.04ms
>22:53:39.501 DOM-Neuberechnung: 0.29ms
>22:53:39.502 DOM-Neuberechnung: 0.27ms Funktion jQuery.fn[method]/<, jquery.min.js Zeile 10220
>22:53:39.503 DOM-Neuberechnung: 0.51ms Funktion jQuery.fn[method]/<, jquery.min.js Zeile 10220
<22:53:39.503 DOM-Neuberechnung: 1.27ms Funktion Modal.prototype.show/<, bootstrap.min.js Zeile 1006
>22:53:39.503 DOM-Neuberechnung: 0.51ms
>22:53:39.578 DOM-Neuberechnung: 0.76ms
>22:53:39.578 DOM-Neuberechnung: 0.62ms
>22:53:39.612 DOM-Neuberechnung: 0.55ms
>22:53:39.612 DOM-Neuberechnung: 0.34ms
>22:53:39.612 DOM-Neuberechnung: 0.34ms
>22:53:39.738 DOM-Neuberechnung: 0.54ms
>22:53:39.738 DOM-Neuberechnung: 0.44ms
>22:53:40.145 DOM-Neuberechnung: 0.48ms

**Comment by Liongold** [comment]
Thank you. Can you pull the latest code in that branch and re-test please? I've added an additional call. If you're using Firefox, can you also turn off all the top options and leave only the Logging button toggled? One last thing, while you have the console open, can you please write this in the command line in the browser console and paste the output, please `document.getElementsByClassName('users_select_umasks')`? Please show the full result of that command. Just for your information, you can also use a screenshot if you want to.
