### ISSUE TITLE
Serving Paperwork docker image behing Nginx Proxy with TLS? 

### ISSUE THREAD

**Issue by ulm0** [paperwork/paperwork#803]
I have a working Paperwork docker image (the docker image uses Apache to work) behind an Nginx proxy in HTTP, and now i want it to be served in HTTPS, thing is i can't figure out how to make it work, because when i used in HTTPS the site doesn't load properly

![screenshot from 2017-05-23 20-49-42](https://cloud.githubusercontent.com/assets/13160093/26382346/9ff5c316-3ff9-11e7-901f-92dd52debeb1.png)

So for it to work i need to disable the protection, and then the site can load properly again
![screenshot from 2017-05-23 20-52-12](https://cloud.githubusercontent.com/assets/13160093/26382377/cbf7c5f4-3ff9-11e7-8069-54f835396613.png)

This is the host config file
```nginx
###
# Upstream Server
###
upstream papr_backend {
  # ip_hash;
  server paperwork_paper:80 fail_timeout=0;
}

###
# HTTP Redirection
###

server {
  listen  80;
  server_name paperwork.domain.com;
  return  301 https://$server_name$request_uri;
}

###
# HTTPS
###

server {
  listen 443 ssl;
  # listen 80;
  server_name paperwork.domain.com;

  ssl_certificate /etc/letsencrypt/live/paperwork.domain.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/paperwork.domain.com/privkey.pem;
  # ssl_stapling on;
  # ssl_stapling_verify on;
  add_header Strict-Transport-Security max-age=15768000;

  # ssl_session_cache shared:SSL:10m;

  # pass the PHP scripts to backend
  location / {
    # include proxy_params;
    proxy_redirect        off;
    proxy_http_version    1.1;

    proxy_set_header    Host                $http_host;
    proxy_set_header    X-Real-IP           $remote_addr;
    proxy_set_header    X-Forwarded-Ssl     on;
    proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
    proxy_set_header    X-Forwarded-Proto   $scheme;
    proxy_set_header    X-Forwarded-Port    443;

    proxy_pass http://papr_backend;
  }
}
```
PS: I have other containers running which TLS certs are being proxied as well with no problems.

**Comment by Liongold** [comment]
Are you trying to run Paperwork as domainname/paperwork-type of structure? Or a reverse proxy?

**Comment by Liongold** [comment]
Can you also post a screenshot of your browser's Network tab in the Developer Tools?
