### ISSUE TITLE
Landing page?

### ISSUE THREAD

**Issue by cabdirazzaq** [paperwork/paperwork#810]
Hi

Love the app. I have a newbie question, currently I have paperwork installed on my main domain. I want to use a separate landing page  when someone goes to my domain, and when they click on a specific page, I want them to go to the sign-in page for the app.

How do you go about doing this?

**Comment by Liongold** [comment]
Do you mean that you want to use Paperwork as a subfolder? For example having domainname/paperwork and then domainname/otherapporpage at the same time? Or do you want just a Paperwork page that does not show the Log in form immediately?

**Comment by jacek-1210** [comment]
I want to use Paperwork as a subfolder. So: domainname/paperwork & domainname/othersomeapp1 & domainname/othersomeapp1 etc. at the same time. Is it possible ? (Frontend isn't a root folder of paperwork)

**Comment by cabdirazzaq** [comment]
@Liongold sorry for the delayed response. Thanks for the quick reply.
What I mean is that I wish to have a separate landing page on my domain name:
http://www.avidnote.com

Currently, it is linking to the app (http://www.avidnote.com/login). Instead, I want my domain name to show a landing page that I have made from which I would later link to the app page (http://www.avidnote.com/login). Is it possible to do this without reinstalling it in a new directory?

**Comment by Liongold** [comment]
@cabdirazzaq Yes, you can do something like that. Just add this code in an .htaccess file in your webroot folder. 

```
RewriteEngine on
RewriteCond %{REQUEST_URI} !home
RewriteCond %{REQUEST_URI} !paperwork/frontend/public/
RewriteRule (.*) /paperwork/frontend/public/$1 [L]
```

You can change `home` with the name of your landing page, so probably index.php. Also make sure that the path in the other lines matches that of your install. If not, fix to make it match yours. 

@jacek-1210 Paperwork is not designed to run like that. However, this seems to work in Nginx but I'm not sure. If you're using Nginx, you can try #733. 

As far as I know, there isn't someone who has found a way to do this with Apache.
