### ISSUE TITLE
Sorted notes reset to default order after opening a note 

### ISSUE THREAD

**Issue by svigneau** [paperwork/paperwork#812]
After sorting notes using the "Sort notes by" menu, if I click on a note to open it, the order of the notes is reverted back to the default order. In addition, the default order does not seem to have any apparent logic to it. I am running Paperwork on an up-to-date self-hosted Cloudron. Do you have an idea of what the problem might be and how to fix it?
Thank you in advance!

**Comment by Liongold** [comment]
Fixed in #813.
