### ISSUE TITLE
Something went wrong while sharing your note. You might not have permission to share.

### ISSUE THREAD

**Issue by lujandavid** [paperwork/paperwork#822]
hi, I can´t share notes since the amount of user grew up.

I'm getting the message,

 "Something went wrong while sharing your note. You might not have permission to share."

when I inspect the code of the error page, I can see the message --> 

GET http://localhost/api/v1/notebooks/597ca48a-1510-43ba-a184-90429ba5cf99/note…,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 414 (Request-URI Too Long)

any idea what's happening.

kind regards.

**Comment by clemlaf** [comment]
Yes ! you're trying to share with a bunch of users, and as the user ids and permissions are passed in the URL via a get request from the frontend to the backend, the URI becomes too long.

It might be a good idea to transfert to a post request.

See notes.service.js
`factory.shareNote = function(notebookId,noteId,toUserId,toUMASK,callback){
      NetService.apiGet('/notebooks/'+notebookId+'/notes/'+noteId+'/share/'+toUserId+'/'+toUMASK, function(status,data){
        if (status==200) {
          if(typeof callback != "undefined") {
            callback(notebookId, noteId);
            }
          StatusNotifications.sendStatusFeedback("success", "note_share_success");
        }else{
          StatusNotifications.sendStatusFeedback("error", "note_share_fail");
        }
});`

**Comment by Liongold** [comment]
@clemlaf Would you be interested in doing this yourself and submitting a pull request?

**Comment by clemlaf** [comment]
ok, i'll do that

**Comment by Liongold** [comment]
Thanks.

**Comment by lujandavid** [comment]
Hi guys, do we have any advance on this matter. best regards.

**Comment by clemlaf** [comment]
Hi,
I could not set a Laravel4.2 version of Paperwork on my machine so I started from the laravel5 branch to perform the modifications mentioned above (transfer from get to post request for the "share Note" and "Share Notebook" features). Is that ok with you ?
If not, I can always add a commit forked from the "develop" branch with the same modifications in the corresponding sources files, however I will not be able to test it.
Let me know if you can move on from this point by yourselves.

**Comment by mrusme** [comment]
Sharing in v2 will use a different approach, hence this v1 issue is not relevant anymore.
