### ISSUE TITLE
Content truncated after emoji

### ISSUE THREAD

**Issue by iangreenleaf** [paperwork/paperwork#823]
If an emoji character is entered into the note body or title, that character and all text after it are truncated when the note is saved. For example, try entering:

> Nothing after the 😺 character will appear

**Comment by Liongold** [comment]
@iangreenleaf Sorry for the late reply. What have you actually written in the note? Can you show a screenshot of the note content and the Network tab of the DevTools window, please?

**Comment by mrusme** [comment]
Lack of feedback.
