### ISSUE TITLE
Feature Req: Export to HTML or plain text

### ISSUE THREAD

**Issue by jsEveryDay** [paperwork/paperwork#836]
I just finished a script that uses node mysql which queries the database and returns an html file for each note on the Versions using "title" as filename and "content" as the html body. Or .txt file using "content_preview".

It's funny how we ended up here because of Evernote and yet Evernote is the only way out. More export formats should be supported and it's easier to open plain text or html in the browser in case of an emergency. (like php 7.1)

Sorry, I have limited knowledge on PHP so I can't write this and sharing my node script would be useless.

**Comment by mrusme** [comment]
Will take this on the roadmap for v2, thank you!

**Comment by mrusme** [comment]
This has been implemented and will be possible using the *Print* function in [the web UI](https://github.com/paperwork/web).
