### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by bkoffler** [paperwork/paperwork#838]
Hi - big fan of paperwork and have migrated my onenote and evermore docs over to it. Mobile interface isn't great - are there plans to work on the CSS to clean that up a bit? I would happily help if i thought i could be useful here - just wondering about the roadmap.

**Comment by RundleSG** [comment]
@bkoffler I would also be happy to contribute

**Comment by RundleSG** [comment]
@bkoffler Not sure if you've started on anything, I might spend some time on this tomorrow

**Comment by Liongold** [comment]
@RundleSG  and @bkoffler Any help with this is welcome. Feel free to open pull requests targeting the develop branch.

**Comment by Liongold** [comment]
Pull requests should target the `1` branch now instead of the `develop` branch.

**Comment by mrusme** [comment]
This is related to v1, which is not under active development nor supported anymore. However, v2 will provide a mobile client.
