### ISSUE TITLE
Docker version doesn't work

### ISSUE THREAD

**Issue by mogsub** [paperwork/paperwork#839]
Tried to install it with docker compose to two different cloud providers and both of them failed and stopped at step 

```
RUN \
    # Allow writing access into cache storage
    find ./app/storage -type d -print0 | xargs -0 chmod 0755 && \
    find ./app/storage -type f -print0 | xargs -0 chmod 0644 && \
    # Install dependencies and build the scripts and styles
    composer install && npm update && npm install && \
    npm install -g gulp bower && bower --allow-root install && gulp && \
    # Fix permissions for apache \
    chown -R www-data:www-data /app && chmod +x /app/docker-runner.sh
```

with error:

`ERROR: Service 'web' failed to build: The command '/bin/sh -c find ./app/storage -type d -print0 | xargs -0 chmod 0755 &&     find ./app/storage -type f -print0 | xargs -0 chmod 0644 &&     composer install && npm update && npm install &&     npm install -g gulp bower && bower --allow-root install && gulp &&     chown -R www-data:www-data /app && chmod +x /app/docker-runner.sh' returned a non-zero code: 137`

**Comment by alazare619** [comment]
likely has to do with the fact that /app/docker-runner.sh doesnt exist.

**Comment by alazare619** [comment]
https://github.com/twostairs/paperwork/pull/841

**Comment by Liongold** [comment]
Can someone try this again to see whether it has been fixed or not, please?

**Comment by mrusme** [comment]
Docker is now working for v2. v1 is not under active development anymore.
