### ISSUE TITLE
Get some errors from version 'Merge pull request #842 from twostairs/develop'

### ISSUE THREAD

**Issue by idreamerhx** [paperwork/paperwork#844]
1993  jquery.min.js:4388 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.

[Violation] 'readystatechange' handler took 6316ms
[Violation] Forced reflow while executing JavaScript took 322ms
angular.min.js:8605 [Violation] 'readystatechange' handler took 171ms
angular.min.js:8661 GET http://192.168.1.6:8090/api/v1/notebooks/00000000-0000-0000-0000-000000000000/notes 500 (Internal Server Error)
(anonymous) @ angular.min.js:8661
sendReq @ angular.min.js:8455
serverRequest @ angular.min.js:8175
wrappedCallback @ angular.min.js:11735
(anonymous) @ angular.min.js:11821
$eval @ angular.min.js:12864
$digest @ angular.min.js:12676
$apply @ angular.min.js:12968
done @ angular.min.js:8479
completeRequest @ angular.min.js:8693
xhr.onreadystatechange @ angular.min.js:8632
angular.min.js:24041 [Violation] 'requestAnimationFrame' handler took 1892ms
[Violation] Forced reflow while executing JavaScript took 1892ms
angular.min.js:4732 [Violation] 'setTimeout' handler took 117ms
angular.min.js:4732 [Violation] 'setTimeout' handler took 418ms
[Violation] Forced reflow while executing JavaScript took 292ms
angular.min.js:24041 [Violation] 'requestAnimationFrame' handler took 1585ms
[Violation] Forced reflow while executing JavaScript took 1585ms

ckeditor.js:21 [CKEDITOR] For more information about this error go to http://docs.ckeditor.com/#!/guide/dev_errors-section-editor-incorrect-destroy
(anonymous) @ ckeditor.js:21
m @ ckeditor.js:10
CKEDITOR.event.CKEDITOR.event.fire @ ckeditor.js:12
CKEDITOR.warn @ ckeditor.js:19
(anonymous) @ ckeditor.js:256
(anonymous) @ ckeditor.js:28
ckeditor.js:21 [CKEDITOR] Error code: editor-incorrect-destroy.
(anonymous) @ ckeditor.js:21
m @ ckeditor.js:10
CKEDITOR.event.CKEDITOR.event.fire @ ckeditor.js:12
CKEDITOR.warn @ ckeditor.js:19
(anonymous) @ ckeditor.js:256
(anonymous) @ ckeditor.js:28
ckeditor.js:21 [CKEDITOR] For more information about this error go to http://docs.ckeditor.com/#!/guide/dev_errors-section-editor-incorrect-destroy
(anonymous) @ ckeditor.js:21
m @ ckeditor.js:10
CKEDITOR.event.CKEDITOR.event.fire @ ckeditor.js:12
CKEDITOR.warn @ ckeditor.js:19
(anonymous) @ ckeditor.js:256
(anonymous) @ ckeditor.js:28
angular.min.js:4732 [Violation] 'setTimeout' handler took 123ms
angular.min.js:4732 [Violation] 'setTimeout' handler took 298ms
[Violation] Forced reflow while executing JavaScript took 180ms
ckeditor.js:958

**Comment by idreamerhx** [comment]
Request

http://daemon.com/#/n/87f04563-26af-4ea4-a016-06e3168ad413/0b1897c8-1969-4a00-a948-ce518883b999/edit

Why hit controller ApiNotesController.php/index

This method dump the whole database!

**Comment by Liongold** [comment]
Can you show a screenshot and include the version code found in the Settings page please?
