### ISSUE TITLE
No setConfig

### ISSUE THREAD

**Issue by upq** [paperwork/paperwork#848]
followed all instructions on initial install docs and getting this 
``` /setup/setConfig - No such file or directory ```
I'm not a PHP developer i just want to use paper work locally, so what I did was ``` touch setConfig ``` and re ran the server
on the last config step of creating an admin account  the server fails with ``` Segmentation fault: 11``` 

any help is appreciated.

**Comment by jadjay** [comment]
+1

**Comment by jadjay** [comment]
👍 
there is no file setConfig... in the directory 
https://github.com/twostairs/paperwork/tree/master/frontend/public/setup

Can you please explain this to us ?
Thanks,

**Comment by Liongold** [comment]
That is a route defined in Laravel. Can someone please give additional info about this?

Branch used? (master or something else)
Contents of `frontend/app/storage/config/setup`?
Do `frontend/app/storage/config/database.json` and `frontend/app/storage/config/paperwork.json` exist?
Are you using some form of reverse proxy or something similar?

**Comment by esin** [comment]
Hi

Have same problem :(

$ cat setup
4

$ ls -hlas frontend/app/storage/config/database.json
4.0K -rw-r--r-- 1 www-data www-data 127 Jan 14 19:06 frontend/app/storage/config/database.json

$ ls -hlas frontend/app/storage/config/paperwork.json
ls: cannot access frontend/app/storage/config/paperwork.json: No such file or directory

Distr: Debian 7 x86

$ node -v
v6.12.3

Thank you

**Comment by Liongold** [comment]
@esin Are you using any form of reverse proxy? Which web server are you using?

**Comment by road0001** [comment]
The same problem, I use web server caddy, the config is following:
http://xxx {
    redir https://xxx{url}
}
https://xxx {
    tls xxx@xxx
    gzip
    root /var/www/html/paperwork/frontend/public
    fastcgi / 127.0.0.1:9000 php
}

**Comment by Liongold** [comment]
@road0001 Does it work if you do not redirect?
