### ISSUE TITLE
Unable to use "Insert Math" more than once

### ISSUE THREAD

**Issue by SadieD** [paperwork/paperwork#856]
I can use insert math on a note once but once I try to use it again it will
be unresponsive when I select "ok" but allow me to exit using cancel or the dialog close "x".
Occasionally my browser will freeze and I'll be forced to close the tab containing Paperwork.
I'm using Firefox 57.0.3

Here's my console output:

Error: $rootScope.templateNoteEdit.version is undefined
thisController/<@http://paperwork.mysite.com/js/paperwork.min.js:743:21
$digest@http://paperwork.mysite.com/js/angular.min.js:12703:23
$apply@http://paperwork.mysite.com/js/angular.min.js:12968:13
done@http://paperwork.mysite.com/js/angular.min.js:8479:34
completeRequest@http://paperwork.mysite.com/js/angular.min.js:8693:7
createHttpBackend/</xhr.onreadystatechange@http://paperwork.mysite.com/js/angular.min.js:8632:11
angular.min.js:10160:18
[CKEDITOR] Error code: editor-incorrect-destroy.
ckeditor.js:21:212
[CKEDITOR] For more information about this error go to http://docs.ckeditor.com/#!/guide/dev_errors-section-editor-incorrect-destroy
ckeditor.js:21:256
[CKEDITOR] Error code: editor-incorrect-destroy.
ckeditor.js:21:212
[CKEDITOR] For more information about this error go to http://docs.ckeditor.com/#!/guide/dev_errors-section-editor-incorrect-destroy
ckeditor.js:21:256
Detecting changes using MutationObservers
ckeditor.js:958:136
ReferenceError: event is not defined
[Learn More]
ckeditor.js:667:236
Source map error: request failed with status 404
Resource URL: http://paperwork.mysite.com/js/angular.min.js
Source Map URL: angular-file-upload.js.map
[Learn More]
ReferenceError: event is not defined
[Learn More]
ckeditor.js:667:236

**Comment by Liongold** [comment]
Can you update to the latest version of Paperwork v1 and then try again? If you re-encounter this bug, can you post a screenshot please? Remember that the v1 code is not in the `master` branch anymore but has been moved to the `1` branch.
