### ISSUE TITLE
image not shown on my mobile

### ISSUE THREAD

**Issue by romu70** [paperwork/paperwork#859]
I've just setup my paperwork Docker container, and it works well. I've just a strange issue, from my PC, I added an image to a note and saved.

From my mobile photo, I can open the note, and see the text, but I don't see the image, I just see the symbol which shows the image link is broken.

Any idea?

**Comment by Liongold** [comment]
Is there any way you can get the image URL from your mobile and compare it with the image URL on PC?

**Comment by romu70** [comment]
I'll try this, and post the results.

**Comment by mrusme** [comment]
Closing due to lack of feedback and due to this issue being related to v1.
