### ISSUE TITLE
Copy/Paste seems broken

### ISSUE THREAD

**Issue by romu70** [paperwork/paperwork#860]
I'm moving my notes from Leanote to Paperwork, and found that once an image has been pasted to a note, it's impossible to paste another ones.

No error message or warning, just nothing happens. The same action works on a fresh created note.

May be related to https://github.com/twostairs/paperwork/issues/859 ?

**Comment by itsmehemant123** [comment]
@romu70 I'm curious, why are you moving from leanote to paperwork? I'm trying to decide which to use.

**Comment by romu70** [comment]
[OFF TOPIC]
I used Leanote for a few weeks. It's easy to use (even if it has some usability issues), and it's surprising lightweight (20 MB for the Leanote container). If you want to try it, my Docker files are public here: https://github.com/romu70/self-hosting-containers/. Just change back from 2.6 to 2.5.

I spent a lot of time trying to setup a Dockerfile to run Leanote. And it worked...with the 2.5. Some weeks ago, the team released the 2.6. I just changed this in my Dockerfile, and was unable to get it work. And I didn't want to perform the effort again to get something operating.

IMHO, the main problem is Leanote team is made of chinese people, and they don't answer at all in English on GitHub. I want something which just works, so I gave up with Leanote.

Now, I'm comparing Paperwork (which has issues as well) with NextCloud Notes, not sure to stay with 
Paperwork, as the team seems to be pretty unactive.[/OFF TOPIC]

**Comment by Liongold** [comment]
@romu70 Can you use the Insert image button to add those images? Also, are you using the standard paste or one of the paste buttons provided in the toolbar? Also, could you please include the version ID which can be found by going to the Settings page > About tab, please.

**Comment by Liongold** [comment]
Everyone is free to send feedback and contribute in other ways to the project. Paperwork is open source software.

**Comment by romu70** [comment]
No and No. I only did with Ctrl+C / Ctrl+V. Following your message, I've just seen the small popup which says Paperwork can't get access to the clipboard. This explains of lot of troubles I'm having with clipboard indeed!!

No version ID in the settings page, I created the image 2 weeks ago maybe, so a very recent code.

![screenshot-2018-1-23 paperwork](https://user-images.githubusercontent.com/1898319/35287830-9391b1c2-0063-11e8-87bb-de0b4fdefbfb.png)

**Comment by Liongold** [comment]
Which browser and OS are you using? Can you try with those buttons as well?

**Comment by romu70** [comment]
Firefox 57 on Fedora 27 on the client side. Yes I'll do the testing and post the results.

**Comment by romu70** [comment]
Just tried with the buttons, same problem.

1. Add some text tin the popup for pasting, OK, it works.
2. Then, reopen the popup, type something and OK. 
-> You see "Auto saved", but the popup is still there and nothing has been pasted.

Try the copy/paste but without using the buttons. Once you pasted the first time, try a second time. This "breaks" paperwork , as when using the buttons.

When "broken", Paperwork buttons like "open toolbar" or save, don't work.

**Comment by mrusme** [comment]
This is related to v1, which is not in active development anymore.
