### ISSUE TITLE
Installation failed : incomplete interface, inefficients buttons

### ISSUE THREAD

**Issue by crostif** [paperwork/paperwork#861]
Hi !
I try to install Paperwork on my vps. I installed all dependancies but here the problem : 
I install gulp with `sudo npm install -g gulp`
but there is an error at unsupported.js:28 : 
`console error('a bug known to break npm (...)`
`SyntaxError: Unexpected token ILLEGAL`

Composer and NPM are installed and i verified versions.

An idea ?

**Comment by crostif** [comment]
Here is the whole error message :
`/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:28
        console.error(`a bug known to break npm. Please update to at least ${r
                      ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
`

**Comment by Liongold** [comment]
@crostif Can you retry again? If it happens again, can you share the whole output from the `npm install` command onwards please.

**Comment by crostif** [comment]
I tried again a few days ago. I managed to reinstall and install all dependencies, but there is another issue now : i am blocked at step 4 of the installation. The "next" button is not responding... (url : http://vps381044.ovh.net/paperwork/frontend/public/setup.php). The step 3 is validating my mysql informations, but the step 4 is not working...
I haven't found any solutions anywhere...

**Comment by Liongold** [comment]
OK, good to know your initial problem has been fixed. You can skip that step, as a workaround, by putting 5 in `frontend/app/config/setup`, renaming the `default_paperwork,json` to `paperwork.json`, change its contents according to your liking and then go to the Setup again. It should skip that step. 

Also, can you indicate whether you're using any form of reverse proxy and which web server you're using please? A screenshot of your browser's Network tab showing the problem would help a lot as well.

**Comment by crostif** [comment]
Thanks, it worked !
But this application is very difficult to install !! Now that i logged up, i can't create any library because there is no interface to enable it, just a blank page...

**Comment by Liongold** [comment]
@crostif Can you show a screenshot of the Network tab in the Developer Tools of the browser please? Also, if possible, post a screenshot of the Settings' About page.

**Comment by Liongold** [comment]
Also, if possible, could you please rename the issue to describe the new issue.

**Comment by crostif** [comment]
Hi,
please find the screenshot. It seems to have some errors due to js.
The settings' page can't be loaded (error 404).

Thanks.

![capture](https://user-images.githubusercontent.com/3015118/36101639-2f54e998-100a-11e8-8efe-03e7e131134e.jpg)

**Comment by Liongold** [comment]
@crostif Can you try running `npm install`, `bower install` and `gulp` please? Sorry for the late reply. Remember that the code has now been moved to the `1` branch.

**Comment by crostif** [comment]
Here is the result of my tryout :
 
`root@vps381044:~# sudo npm install
npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/root/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /root
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! path /root/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0
root@vps381044:~# sudo bower install
bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option
root@vps381044:~#  sudo gulp install
[16:28:53] Local gulp not found in ~
[16:28:53] Try running: npm install gulp
root@vps381044:~#
`

**Comment by Liongold** [comment]
@crostif Did you `cd` to the `frontend` folder of the Paperwork code before running those commands?

**Comment by crostif** [comment]
Sorry !!! 
Here is the new result. 

`root@vps381044:/var/www# cd html
root@vps381044:/var/www/html# cd paperwork
root@vps381044:/var/www/html/paperwork# cd frontend
root@vps381044:/var/www/html/paperwork/frontend# npm install
root@vps381044:/var/www/html/paperwork/frontend# bower install
bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option
root@vps381044:/var/www/html/paperwork/frontend# gulp install
[13:44:47] Using gulpfile /var/www/html/paperwork/frontend/gulpfile.js
[13:44:47] Task 'install' is not in your gulpfile
[13:44:47] Please check the documentation for proper gulpfile formatting
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install
bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option
`

**Comment by crostif** [comment]
Same result when running from root.
With bower install --allow-root it gives :

bower invalid-meta  for:/var/www/html/paperwork/frontend/bower.json
bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower extra-resolution      Unnecessary resolution: angular-animate#~1.2
bower extra-resolution      Unnecessary resolution: angular-resource#~1.2
bower extra-resolution      Unnecessary resolution: angular-route#~1.2

**Comment by Liongold** [comment]
@crostif Was that the only output? Did you try running gulp after that?

**Comment by crostif** [comment]
Yes it was. I tried and it was without any effect.

**Comment by Liongold** [comment]
Can you try running the same command with -V added at the end please?

**Comment by Liongold** [comment]
I'm sorry for causing some more work for you but could you try installing the bower dependencies one-by-one please? You need to run `sudo bower install X --allow-root -V` for each line in the dependencies object defined in [this file](https://github.com/twostairs/paperwork/blob/1/frontend/bower.json). For each row replace X with the name of the package then # and then the version of the package referenced in the file. So, for example, `sudo bower install angular#~1.2 --allow-root -V`. Please report on the response you get.

**Comment by crostif** [comment]
The result : 


root@vps381044:/var/www/html/paperwork# cd frontend
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install angular#~1.2 --allow-root -v
1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install angular-animate#~1.2 --allow-root -v
1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install angular-animate#~1.2 --allow-root -v

1.8.2
root@vps381044:/var/www/html/paperwork/frontend#
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install angular-route#~1.2 --allow-root -v
1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install angular-resource#~1.2 --allow-root -v
1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install angular-file-upload#2.5.0 --allow-root -v
1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install jquery#~1.11 --allow-root -v
1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install angular-utf8-base64#0.0.5 --allow-root -v
1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install nDraggable#~0.1.3 --allow-root -v
1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install angular-utf8-base64#~0.0.5 --allow-root -v
1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install html5shiv#~3.7.2 --allow-root -v
1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install respond#~1.4.2 --allow-root -v
1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install jquery-overscroll-fixed#~1.7.7 --allow-root -v
1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install angular-ui-bootstrap-bower#~0.12.1 --allow-root -v
1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install bootstrap#~3.3.4 --allow-root -v
1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install jquery.scrollTo#~2.1.0 --allow-root -v
1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install retinajs#~1.3.0 --allow-root -v
1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install bootstrap-tagsinput#~0.4.2 --allow-root -v
1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install typeahead.js#~0.10.5 --allow-root -v
1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install bootstrap3-ie10-viewport-bug-workaround#~1.0.0 --allow-root -v
1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install angular-loading-bar#~0.7.1 --allow-root -v            1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install placeholders#~4.0.1 --allow-root -v
1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install textAngular#~1.3.0 --allow-root -v
1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install angular-highlightjs#~0.4.3 --allow-root -v            1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo bower install x-editable#~1.5.0 --allow-root -v
1.8.2
root@vps381044:/var/www/html/paperwork/frontend# sudo gulp install
[18:26:29] Using gulpfile /var/www/html/paperwork/frontend/gulpfile.js
[18:26:29] Task 'install' is not in your gulpfile
[18:26:29] Please check the documentation for proper gulpfile formatting
root@vps381044:/var/www/html/paperwork/frontend# gulp
[18:26:50] Using gulpfile /var/www/html/paperwork/frontend/gulpfile.js
[18:26:50] Starting 'compileLessBootstrapTheme'...
[18:26:50] Finished 'compileLessBootstrapTheme' after 8.28 ms
[18:26:50] Starting 'compileLessPaperworkThemeV1'...
[18:26:50] Finished 'compileLessPaperworkThemeV1' after 1.82 ms
[18:26:50] Starting 'compileLessFreqselector'...
[18:26:50] Finished 'compileLessFreqselector' after 914 μs
[18:26:50] Starting 'compileLessTypeahead'...
[18:26:50] Finished 'compileLessTypeahead' after 1.58 ms
[18:26:50] Starting 'less'...
[18:26:50] Finished 'less' after 6.72 μs
[18:26:50] Starting 'lint'...
[18:26:50] Finished 'lint' after 8.91 ms
[18:26:50] Starting 'compileJsBootstrap'...
[18:26:50] Finished 'compileJsBootstrap' after 2.64 ms
[18:26:50] Starting 'compileJsPaperwork'...
[18:26:50] Finished 'compileJsPaperwork' after 3.79 ms
[18:26:50] Starting 'compileJsPaperworkNative'...
[18:26:50] Finished 'compileJsPaperworkNative' after 1.77 ms
[18:26:50] Starting 'compileJsAngular'...
[18:26:50] Finished 'compileJsAngular' after 5.57 ms
[18:26:50] Starting 'compileJsJquery'...
[18:26:50] Finished 'compileJsJquery' after 2.74 ms
[18:26:50] Starting 'compileJsTagsinput'...
[18:26:50] Finished 'compileJsTagsinput' after 2.78 ms
[18:26:50] Starting 'compileJsLibraries'...
[18:26:50] Finished 'compileJsLibraries' after 3.06 ms
[18:26:50] Starting 'compileJsLtIe9Compat'...
[18:26:50] Finished 'compileJsLtIe9Compat' after 1.37 ms
[18:26:50] Starting 'compileJsLtIe11Compat'...
[18:26:50] Finished 'compileJsLtIe11Compat' after 718 μs
[18:26:50] Starting 'js'...
[18:26:50] Finished 'js' after 6.7 μs
[18:26:50] Starting 'concatLibCSS'...
[18:26:50] Finished 'concatLibCSS' after 2.2 ms
[18:26:50] Starting 'default'...
[18:26:50] Finished 'default' after 8.46 μs
root@vps381044:/var/www/html/paperwork/frontend#

**Comment by crostif** [comment]
I've got some news ! This last trying have finally been partially successfull.
Look at those screenshots, the interface is now there. But buttons are inefficients : i can't create anything. No button is working.
![paper1](https://user-images.githubusercontent.com/3015118/38351802-67595aac-38b1-11e8-86fc-749125a1dcb3.png)
![paper2](https://user-images.githubusercontent.com/3015118/38351803-677a252a-38b1-11e8-89ab-a601182f8395.png)

**Comment by Liongold** [comment]
Glad to see it works better. However, it is necessary to see the output of the browser console again.

**Comment by crostif** [comment]
Right ! Some errors refers to two folders which don't exist : /frontend/public/api an /frontend/public/templates

![paper3](https://user-images.githubusercontent.com/3015118/38376962-1316335e-38fa-11e8-9c20-3c3614263b83.png)

**Comment by Liongold** [comment]
@crostif Sorry for the late reply. Can you put the paperwork as the web folder so that Paperwork becomes accessible at the www.example.com without the /paperwork part? That should fix your issue.

**Comment by crostif** [comment]
@Liongold I'm sorry, but i don't understand what you mean...

**Comment by Liongold** [comment]
@crostif You need to identify the webroot folder and put paperwork there. The webroot folder is the folder in which you put files to have them served at the top level. So, the folder where example.php is placed to be accessible from www.example.com/example.php. Once you find this, make sure that the public folder is in the webroot.

**Comment by Liongold** [comment]
Return it to how it was to have something that works.

**Comment by Liongold** [comment]
Actually what was the error you got? Did you follow this page to skip the Setup Wizard https://github.com/twostairs/paperwork/wiki/Installing-and-configuring-Paperwork-without-using-the-Setup-Wizard
