### ISSUE TITLE
Docker compose runtime error. /app/docker-runner.sh not found

### ISSUE THREAD

**Issue by prototol** [paperwork/paperwork#863]
`>>> Docker-compose up`
`ERROR: for web  Cannot start service web: oci runtime error: container_linux.go:265: starting container process caused "exec: \"/app/docker-runner.sh\": stat /app/docker-runner.sh: no such file or directory"
ERROR: Encountered errors while bringing up the project.`

**Comment by Liongold** [comment]
The version of Paperwork you opened this issue for has been moved to the `1` branch. Can you use the code found in that branch and retry?
