### ISSUE TITLE
Used deploy to heroku button, config is not saved between dynos

### ISSUE THREAD

**Issue by dskrad** [paperwork/paperwork#864]
I am using a free dyno on heroku, and whenever the dyno stops and restarts, I lose the database configuration. It bumps me back to setup.php. I can then reenter all the database configuration data, and then I have to create a new user again. When I log in using the original user account, my notes are there, so the database connection is correct and my data is being committed. It is the configuration that is not saved between dynos. 

The only heroku config var that is set is DATABASE_URL, but the app is not using it.

**Comment by mrusme** [comment]
This is related to v1, which is not under active development nor supported anymore. Will however take Heroku deployment in consideration for v2!
