### ISSUE TITLE
Tags concept & schema

### ISSUE THREAD

**Issue by mrusme** [paperwork/paperwork#889]

**Comment by fenandosr** [comment]
Proposal for tags:
Meta-tags: tags of tags. Maybe something like "Adding Parent tag when child tag is added".
Keyboard shortcuts for tags.

**Comment by mrusme** [comment]
@fenandosr can you specify on how this would look like & work in detail? And what would be the benefit? Thanks!

**Comment by mrusme** [comment]
Tags are now part of the [service-notes](https://github.com/paperwork/service-notes) and were implemented as a first draft to build on top of.
