### ISSUE TITLE
Overall Architecture

### ISSUE THREAD

**Issue by mrusme** [paperwork/paperwork#901]
Build a concept for the overall Paperwork architecture.

**Comment by mrusme** [comment]
I'm currently investigating whether Kong could be useful for the overall Paperwork architecture, follow the [evaluation progress here](https://github.com/Kong/kong/issues/754#issuecomment-364288176).

The thought was to be able to build each component of the Paperwork back-end as individual (micro-)service – utilising whatever tech stack fits best for the specific service – and unify them using Kong. A benefit would be the plugins Kong provides (e.g. JWT, OAuth2, Logging, etc.). If this works properly, it could save many working hours.

Kong could be run with PostgreSQL, but I think having Cassandra (or better ScyllaDB, because, who wants a JVM in 2018 anyway?) could be useful in the long term.

**Comment by mrusme** [comment]
Adjusted directory structure and `docker-compose.yml` in order to run Kong: https://github.com/twostairs/paperwork/commit/6ad887284cc3c3611132510c10547eda4b43b5e6

**Comment by mrusme** [comment]
Committed the first working draft using Kong, with the draft implementation of `service-users`: https://github.com/twostairs/paperwork/commit/794fa76e377f84a1e33af7b76b3320d1df3b52af

<img width="1107" alt="screen shot 2018-02-10 at 10 53 11 pm" src="https://user-images.githubusercontent.com/151967/36067012-317ca1f8-0eb5-11e8-843e-655350c79cb1.png">

As for the URL, `service-users` needs to remove the additional `/users/` prefix, as it is not prefixed by Kong. However, auto-discovery inside the `docker-compose` setup seems to work and Kong seems to be able to find `service-users` and proxy the request towards it. For setting up the endpoint I used the following request on Kong's admin API:

```bash
## CREATE service-users API
curl -X "POST" "http://localhost:8001/apis" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "uris": "/users",
  "strip_uri": true,
  "name": "service-users",
  "upstream_url": "http://service-users:3000"
}'
```

This call needs to be built into `service-users` and probably happen during each startup, since duplicate requests with the same `name` are being rejected by Kong anyway.

However, the setup looks promising so far. Any thoughts?

**Comment by richerlariviere** [comment]
Thanks for detailing a lot your thought process.

**Comment by mrusme** [comment]
Here's an update to the overall architecture:

The initial idea of building the whole software up in a service-oriented way *and* stick to it across every layer (from code to the actual setup) progressed and lead to having the main repository (`paperwork`) being only a meta-layer that bundles each component into a ready-to-use infrastructure. Hence, all service code was removed from it and as of now there are not submodules containing the individual services anymore. Instead, each service became a separate building-block that is being publicly available through [Docker Hub](https://hub.docker.com/u/paperworkco/). The main repo only provides tools for the development environment and docker-compose files that allow setting up everything instantly.

The ultimate goal is to have a configuration that allows for Paperwork to be deployed on a Docker Swarm host without requiring too much knowledge of either Paperwork or Docker.

All services that contain in-house developed code are built on top of [Paperplane](https://hub.docker.com/r/paperworkco/paperplane/) or a [language-/framework-specific extension](https://hub.docker.com/r/paperworkco/paperplane-node/) of it. Paperplane aims to streamline the groundwork required for a service – that is ContainerPilot, Consul, health checks and at some point metrics and much more. Ideally, every externally developed service (e.g. Postgres, ScyllaDB, etc.) is being run on Paperplane as well, at some point. For every new language/framework, a new Paperplane extension should be created, that extends from Paperplane (e.g. `paperplane` -> `paperplane-elixir` -> `service-something`).

Services register on the Consul server(s) and can either directly communicate with each other or use `service-nats` as a [messaging system](https://nats.io). NATS should also be used to enable an event-driven architecture, where each service produces events that are being consumed by other services. As for the databases, each service owns its own database, that is fully independent of other services' data. Hence, each service should use a database that makes sense for the specific task, rather than just utilise any existing database, no matter what.

As of right now, databases are not persistent nor replicatable . This will change, as soon as Paperwork v2 reaches a first release candidate.

**Comment by richerlariviere** [comment]
+1 for Docker Swarm. I also have experience with those who would like to use Kubernetes. Just let me know if you are interested in that kind of support.

**Comment by mrusme** [comment]
Thanks! Do you think it'd make sense to provide a minikube setup? Not sure how many people really have K8s running locally.

For a hosted setup, on the other hand, it would be cool to have some kickstart resources for hosting Paperwork on K8s of course.

Wdyt?

**Comment by richerlariviere** [comment]
If we provide a simple way to run it locally I think a lot of users would find this interesting and relevant because some of them would like to try it locally before paying for a container service). It's also easy to write a K8s config based on Docker swarm.

**Comment by mrusme** [comment]
@richerlariviere would you be interested in doing that? I'd be happily accepting PRs regarding K8s. :)
Bear with me when the setup might change and requiring adjustments to the K8s config, though. As you see here it's still in a very early stage.

**Comment by richerlariviere** [comment]
I'm down. Don't worry I know Paperwork v2 is a young project. When the K8s configuration is mature enough I'll send you a PR. I will let you know when I'm ready to show you something.

**Comment by mrusme** [comment]
The architecture has changed to what was initially approached and documented here, to something that's more feasible as basically a "one man show". Would have loved to use Scylla, unfortunately compatibility was a big pain point. Also I would have liked to use Kong, however, it really became a PITA to integrate, especially when they basically completely changed their admin API recently. Hence the approach now is a more lightweight and stripped down solution, on top of which all the fancy stuff can be build at a later stage.
