### ISSUE TITLE
CK editor error

### ISSUE THREAD

**Issue by kypdk** [paperwork/paperwork#904]
[CKEDITOR] Error code: editor-incorrect-destroy.
ckeditor.js:21:212
[CKEDITOR] For more information about this error go to http://docs.ckeditor.com/#!/guide/dev_errors-section-editor-incorrect-destroy
ckeditor.js:21:256
[CKEDITOR] Error code: editor-incorrect-destroy.
ckeditor.js:21:212
[CKEDITOR] For more information about this error go to http://docs.ckeditor.com/#!/guide/dev_errors-section-editor-incorrect-destroy
ckeditor.js:21:256
Detecting changes using MutationObservers
ckeditor.js:958:136
[CKEDITOR] Error code: editor-incorrect-destroy.
ckeditor.js:21:212
[CKEDITOR] For more information about this error go to http://docs.ckeditor.com/#!/guide/dev_errors-section-editor-incorrect-destroy
ckeditor.js:21:256
[CKEDITOR] Error code: editor-incorrect-destroy.
ckeditor.js:21:212
[CKEDITOR] For more information about this error go to http://docs.ckeditor.com/#!/guide/dev_errors-section-editor-incorrect-destroy
ckeditor.js:21:256
Detecting changes using MutationObservers
ckeditor.js:958:136
ReferenceError: event is not defined
[Learn More]

how to fix

**Comment by Liongold** [comment]
@kypdk Does CKEditor stop working because of them? I think those errors should not affect functionality.
