### ISSUE TITLE
Founding Proposal

### ISSUE THREAD

**Issue by flohall** [paperwork/paperwork#908]
I got an idea for improving founding @twostairs

I dont't know if you heard about https://de.liberapay.com/ an open source provider for regular foundings to open source projects by anyone. I really high % of the money goes directly to the open source project.

There is already some little money raised. You just must create a new account there.
https://de.liberapay.com/on/github/twostairs

I guess with some links on your webpage and this repository - more users will give some little money to your project. 

Just want to say that you did great work so far and hope you stay motivated.

**Comment by mrusme** [comment]
Thank you for this suggestion! I've transferred it to my private to do list and will eventually take it in consideration. :-)

PS: If you got further ideas, feel free to [join the chat](https://riot.im/app/#/room/#paperwork:matrix.org) and communicate them there!
