### ISSUE TITLE
there is any demo or screenshots?

### ISSUE THREAD

**Issue by udiNur** [paperwork/paperwork#913]

**Comment by caseyhoward** [comment]
My first google search result was pretty worthless.
https://github.com/twostairs/paperwork/wiki/Screenshots
No screenshots, says to use demo, doesn't provide link to demo.

**Comment by PackElend** [comment]
I think that is urgent

**Comment by sunrez** [comment]
Hi,

The twostairs page linked for screenshots / demo is non-functional

**Comment by mrusme** [comment]
As for v1: There are no more screenshots/demos available (at least from my side, maybe some users do still host them).

For v2, you can find info about the current state and aesthetics [in the web repo](https://github.com/paperwork/web). Also, if you want to fiddle around yourself, you can [launch your own v2 infrastructure](https://github.com/paperwork/paperwork#docker-stack) now.
