### ISSUE TITLE
how to migrate all the paperwork data to another server?

### ISSUE THREAD

**Issue by fytztx** [paperwork/paperwork#914]
Deployed on the server A, but the server A is going to shutdown, now need to migrate all the data from server A to server B, how that can be done?

**Comment by jsEveryDay** [comment]
sqldump?

**Comment by mrusme** [comment]
Your safest bet is probably to use `mysqldump` and also `rsync` the attachments folder to the new location. However, with such little information provided on hosting nobody can answer this question accurately. Also: GitHub issues should not be used for questions but rather for reporting issues. Please head to the chatroom for questions, thanks!
