### ISSUE TITLE
No latest version available

### ISSUE THREAD

**Issue by mouarfff** [paperwork/paperwork#918]
When i list my paperwork docker image i see that :

```
$ docker images
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
mongo                          <none>              5976dac61f4f        4 days ago          411MB
paperwork/service-notes        <none>              09dbf1f849e2        7 days ago          61MB
paperwork/service-users        <none>              42c0da54faf0        7 days ago          61MB
paperwork/service-configs      <none>              986115b2ef5c        7 days ago          61MB
paperwork/web                  <none>              e555261aa970        2 weeks ago         31.7MB
paperwork/service-gatekeeper   <none>              ae7f3e023189        2 weeks ago         551MB
```

So i can't run it ?

Sorry if i ask for a stupid quesiton...

**Comment by mrusme** [comment]
The [latest tag is available](https://cloud.docker.com/u/paperwork/repository/docker/paperwork/service-notes/tags) and this output should not be the reason for you to not be able to run anything.

Follow the steps on [Usage](https://github.com/paperwork/paperwork#usage) if you'd like to spin up Paperwork v2 on your Docker Swarm. If any errors occur, feel free to re-open this ticket and post the actual errors here. :-)
