### ISSUE TITLE
Cannot see SMB share in open dialog

### ISSUE THREAD

**Issue by imp1sh** [paperwork/paperwork#923]
I use Ubuntu 18.04.03 and since paperwork is not in the repos I installed it via flatpak. I import scans through open dialog. My workflow is that the scanner just dumps the scans onto an SMB share which I also mount in Ubuntu via default File Manager which is Nautilus IIRC.
This mount I cannot access at all in paperwork. This stupid mechanism of mounting it to /run/user/<<userid>>/gvfs and so forth is another topic. Anyhow I can't see the directory gvfs in the open dialog of paperwork AT ALL. I linked the directory to my desktop, still cannot see it.

1. Use Ubuntu Version
2. Install Paperwork via Flatpak
3. Mount SMB share via Nautilus
4. Start Paperwork and try to import from that very share

I expect the folder to be seeable / browseable. In fact ideally my Nautilus favourite should be there instead of going into /run/user/.... because normal people have zero knowledge of that mechanism.

Ubuntu 18.04.03 LTS X86_64

**Comment by mrusme** [comment]
You've mistaken us for [someone else](https://gitlab.gnome.org/World/OpenPaperwork), I'm sorry.
