### ISSUE TITLE
Date format of system is not being used

### ISSUE THREAD

**Issue by imp1sh** [paperwork/paperwork#924]
Paperwork installation Ubuntu 18.04.03 via flatpak. Date format is American, which I cannot change through interface. In Ubuntu a different time format is already chosen but not being used by paperwork.

**Describe the solution you'd like**
Either paperwork should just use the time format from the system or you should be able to set it in the GUI. I prefer first.

Ubuntu 18.04.03

**Comment by mrusme** [comment]
You've mistaken us for [someone else](https://gitlab.gnome.org/World/OpenPaperwork), I'm sorry.
