### ISSUE TITLE
Heroku Button Install

### ISSUE THREAD

**Issue by brianjking** [paperwork/paperwork#97]
Any plans for a 1 click deploy to Heroku?

**Comment by devilx** [comment]
We're open to any enhancement. Do you (or anyone else here) have experience with Heroku, to set up the "1 click deploy"? :-)

**Comment by jacobbridges** [comment]
The most difficult part I foresee with creating a Heroku 1-click deploy is the MySQL database migrations. Heroku manages database differently than other servers--perhaps an option for using SQLite?

I'll take a look at this tonight. I really like this project though it has a long path until it's production ready.

**Comment by pwmvx1289** [comment]
@jacobbridges May you guide me on deploying on Heroku?

**Comment by jacobbridges** [comment]
@pwmvx1289 I tinkered with a Heroku deployment this evening and will continue tomorrow evening after work. It's been almost two years since I used Heroku and the system has changed (somewhat). 

I'll post a link once it's running, and if @devilx approves I'll submit a pull request to add the "one click deploy" button.

**Comment by devilx** [comment]
:+1:

**Comment by xingh** [comment]
Has any one installed on heroku recently? I could help with this, or at least test.

**Comment by khurshid-alam** [comment]
Can anyone at least post some instructions how to install it on heroku? I don't mind if its not an one-line instruction.

**Comment by wongalvis** [comment]
@Liongold What would be the database credentials if Paperwork is deployed to Heroku?

**Comment by Liongold** [comment]
@wongalvis Sorry for not replying earlier. While deploying the app, Heroku will create a new PostgreSQL database. You can get the credentials by going to the Database part of the site. You can find the credentials http://postgres.heroku.com. Please post here if you have any issues and feedback.

**Comment by leo90skk** [comment]
I tried to use the PostgreSQL DB from Heroku, but the setup script says always: 
```
These credentials do not appear to be correct. Please check them again.
```

BTW: The one-button-click installation does not seem to work correctly. It is missing **php** and **ext/mcrypt**.
How to fix that?

```
PHP Dependencies
The package laravel/framework is installed.
The package jenssegers/agent is installed.
The package erusev/parsedown is installed.
The package thiagoalessio/tesseract_ocr is installed.
The package simplesoftwareio/simple-qrcode is installed.
The package barryvdh/laravel-ide-helper is installed.
The package webpatser/laravel-uuid is installed.
The package strebl/adldap is installed.
The package php is not fully installed. Did you run composer install?
The package doctrine/dbal is installed.
The package ext/mcrypt is not fully installed. Did you run composer install?
```

**Comment by Liongold** [comment]
The composer not fully installed errors are not fully reliable. However, it should still work even with those warnings. There seems to be another issue that is not allowing it to work correctly.

**Comment by Liongold** [comment]
The latest changes done in the develop branch have been pushed to the Heroku branch. The 'Deploy to Heroku' button should be working now. Please test this and if it does, then this issue can be closed.

**Comment by leo90skk** [comment]
OK. Now it works.

I just get still this notification after setup:

> Found a bug? Paperwork cannot connect to Github to check the latest version. A solution to this can be installling the curl PHP extension. This is not mandatory, however before reporting any issues, please make sure that you are using the latest version.
> Double click to dismiss.

p.s. It would be even better when the setup script automatically gets the postgres db connection data (server, database, user, password) from heroku.

**Comment by Liongold** [comment]
That notification is normal if you do not have curl installed and enabled on your server. If you want to remove it, you can install and enable curl. If you want to get rid of the notification totally, you can turn it off during the Setup Wizard by turning off the setting Show Issue Reporting Link. Let us know if this fixes your issue and if it does, please close this issue. 

About your suggestion, it's a nice suggestion. Could you please open a new issue for it?
